### ISSUE TITLE
📱🦋[Abgeordnetenprofil] Seite und verlinken

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1003]
TESTING:
funktioniert das abgeordneten profil und die verlinkungen dorthin

icons auf dem profil ausgeschlossen (nur linking testen)

**Comment by ulfgebhardt** [comment]
Icons werden nicht richtig dargestellt.
Alles andere funktioniert

**Comment by ManAnRuck** [comment]
wie bereits in der testing beschreibung beschrieben sind die icons hier außen vor
