### ISSUE TITLE
📱🦋[Wahlkreiseinstellungen] Header umbenennen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1006]

**Comment by ManAnRuck** [comment]
TESTING: zu wahlkreiseinstellungen gehen und schauen ob der titel "Wahlkreissuche" heißt

**Comment by ulfgebhardt** [comment]
Test: failed "Constituency" ist der Titel

**Comment by ManAnRuck** [comment]
durch einen anderes issue war diese änderung in der tat wieder rausgeflogen

**Comment by ulfgebhardt** [comment]
Test: ok
