### ISSUE TITLE
📱🦋[Wahlkreiseinstellungen] markierungs icon ändern

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1007]

**Comment by ulfgebhardt** [comment]
Nicht deployed? Der Haken ist schwarz auf der Alpha

**Comment by ManAnRuck** [comment]
Ist deployed da vorher eine Blume zu sehen war 🌼
Jedoch scheint es mit dem einfärben auf Android ein Problem zu geben

**Comment by ManAnRuck** [comment]
Sollte nun wie folgt aussehen

<img width="381" alt="Bildschirmfoto 2020-01-31 um 17 26 57" src="https://user-images.githubusercontent.com/2183135/73557774-1a736a80-4452-11ea-9181-a36e6af77449.png">
<img width="428" alt="Bildschirmfoto 2020-01-31 um 17 25 43" src="https://user-images.githubusercontent.com/2183135/73557779-1cd5c480-4452-11ea-8fb4-b7017de6af1a.png">
