### ISSUE TITLE
📱🦋[Wahlurne] Headline Voting in Wahlurne umbenennen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1009]

**Comment by ulfgebhardt** [comment]
Not on Alpha

**Comment by ManAnRuck** [comment]
<img width="395" alt="Bildschirmfoto 2020-01-30 um 09 11 07" src="https://user-images.githubusercontent.com/2183135/73414143-7d74dc80-4340-11ea-95cf-695420d2d01d.png">
auf browserstack ist die headline bei andriod devices bereits drinnen ebenso auf ios. 
könntest du das noachmal validieren?

**Comment by ManAnRuck** [comment]
Fehlt in der Tat bei Navigation über den Wahl o mat

**Comment by ulfgebhardt** [comment]
test: ok
