### ISSUE TITLE
Wahlkreis Chart lädt unendlich

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1014]
Wenn noch keine Daten zum Wahlkreis verfügbar

![16357BEC-FE22-4EB3-BB2D-020883E9646A.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/4326c74f-9872-4b7d-b674-6f04a7d66237)

**Comment by ManAnRuck** [comment]
TESTIN:
wird das wahlkreischart nur angezeigt, wenn auch daten vorhanden (min. eine abstimmung für ausgewählten wahlkreis)

**Comment by ulfgebhardt** [comment]
Test ok: Approve
