### ISSUE TITLE
📱 Add Internal line to android & ios

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1017]
internal app für ios und android erstellen

Testing:
gibt es nun eine internal version auf android und iOS über die stores/testflight zu laden

**Comment by ulfgebhardt** [comment]
test: ok

**Comment by ulfgebhardt** [comment]
Also die testversion gibt es - die liste bleibt allerdings leer (?)

**Comment by ManAnRuck** [comment]
was meinst du mit leer? einfach nur weiß | endlosspinner | sitzungswoche leer? @ulfgebhardt

**Comment by ManAnRuck** [comment]
netzwerkfehler werden in folgendem ticket behandelt: https://github.com/demokratie-live/democracy-client/issues/1026

der fehler kann potentiel in allen versionen auftreten und hat daher nichts mit der internal lane alleine zu tun

**Comment by ManAnRuck** [comment]
@ulfgebhardt würdest du dir beim PR den serverteil kurz anschauen und dein review für geben?
