### ISSUE TITLE
📱 Push benachrichtigungen Deep Linken

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1019]
Wenn man auf eine push klickt sollte man zur enstprechenden Procedure kommen

**Comment by visionmakery** [comment]
Header 'Gesetz / Antrag' anstatt ![image0.png](https://images.zenhubusercontent.com/5d35a18454a8bc2dbc51e9f1/c41a24f6-a6eb-4d71-8746-db537dc82922)

**Comment by ManAnRuck** [comment]
überschrift ist nun angepasst auf den typ
