### ISSUE TITLE
[1.3] Suche // Tastatur verschwindet nicht

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1025]
## 🐛 Bugreport
Wenn man in der aktuellen Dev/Internal-Version sucht, z.B. "Parteien(finanzierung)" verschwindet a) die Tastatur nicht wenn man auf Suche (unten rechts) klickt und 
![image](https://user-images.githubusercontent.com/32302889/73756982-c1b11400-4768-11ea-9a91-7a430db58469.png)
b) nicht, wenn man in eine Prozedur reinnavigiert
![image0](https://user-images.githubusercontent.com/32302889/73756995-c5449b00-4768-11ea-8024-b2e688959b2c.png)

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1. Lupe klicken
2. "Parteien" eingeben
3. Suchen klicken
4. Ein Ergebnis klicken

**Comment by ManAnRuck** [comment]
TESTING:
verschwindet die tastatur wenn man auf suchen klickt
verschwindet die tastatur wenn man auf einen listeneintrag klickt
