### ISSUE TITLE
📱 [Filter] Zeilenabstände

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1039]
Zeilenabstände teilweise zu groß
<img width="426" alt="Bildschirmfoto 2020-02-06 um 10 31 30" src="https://user-images.githubusercontent.com/2183135/73923876-db1ea100-48cb-11ea-9ad5-66ffab20d7b2.png">

**Comment by visionmakery** [comment]
Zwischen dem letzten Auswahlelement eines Filterkriteriums und der neuen Sektion ist ein Abstand (ca. 5px), der nicht sein sollte

![image0.png](https://images.zenhubusercontent.com/5d35a18454a8bc2dbc51e9f1/19f9cebb-72ff-4868-9e88-15c02925e7c7)
