### ISSUE TITLE
📱 [Filter] Abstände nach links 

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1040]
Es gibt 3 verschiedene Abstände nach links diese sollten etwas abgestimmter sein

<img width="153" alt="Bildschirmfoto 2020-02-06 um 10 34 17" src="https://user-images.githubusercontent.com/2183135/73924107-3f416500-48cc-11ea-9e9f-3a54b82cf38e.png">

zusammen mit:
#1038 
#1039

**Comment by visionmakery** [comment]
![image0.png](https://images.zenhubusercontent.com/5d35a18454a8bc2dbc51e9f1/67c1bf04-75ff-4357-8cc6-d8b70210345a)

Zwischen dem letzten Auswahlelement eines Filterkriteriums und der neuen Sektion ist ein Abstand (ca. 5px), der nicht sein sollte
