### ISSUE TITLE
📱 [ListView] PieChart WOM Logik

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1042]
- [x] den Abstimmungskarten in der WOM-Liste auch die Untertitel geben
- [x] Wahl-O-Meter/BT und Fraktionen: Eigene Stimme hervorheben (⏱4, 🤩8)
- [x] Wahl-O-Meter/Fraktionen: Anteil der auswählten Fraktion des BT hervorheben! (⏱4, 🤩8)
- [x] Wahl-O-Meter/WK: Einfarbiger Kreis für Kandidat (⏱2, 🤩7)
- [x] Wahl-O-Meter/WK: Einfarbiger Kreis für eigene Stimme (⏱2, 🤩7)

**Comment by visionmakery** [comment]
- [ ] Wahl-O-Meter Listen Komponenten Refactoren (⏱20, 🤩7)
- [ ] Wahl-O-Meter noch keine Abstimmungen: Abstimmungsliste anzeigen (⏱2, 🤩7)
- [ ] Wahl-O-Meter/BT und Fraktionen: Eigene Stimme hervorheben (⏱4, 🤩8)
- [ ] Wahl-O-Meter/Fraktionen: Anteil der auswählten Fraktion des BT hervorheben! (⏱4, 🤩8)
- [ ] Wahl-O-Meter/WK: Einfarbiger Kreis für Kandidat (⏱2, 🤩7)
- [ ] Wahl-O-Meter/WK: Einfarbiger Kreis für eigene Stimme (⏱2, 🤩7)
