### ISSUE TITLE
📱 [Detail] iOS Teilen Symbol im header und action buttons einbinden

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1050]

**Comment by visionmakery** [comment]
nach meinem Empfinden müssen wir hier nochmal ran:
- die Icons etwas verdicken - das mache ich 
- ausgefüllte Glocke für Push aktiviert; die durchgestrichene ist maximal irritierend, weil ich denke, es ist derzeit stumm gestellt
