### ISSUE TITLE
📱 [Wahl-O-Meter] Headline

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1065]
Headline wird derzeit ohne Bindestriche angezeigt.
sollte analog zur sidebar sein

![original-1](https://user-images.githubusercontent.com/2183135/74233623-5799f100-4ccb-11ea-90ed-164a5c25fc4e.jpg)

**Comment by visionmakery** [comment]
bitte mit Bindestrichen: Wahl-O-Meter
