### ISSUE TITLE
🐛 Icons for Pushs on Android

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#1067]
### 🐛 Icons for Pushs on Android

Pushnotifications on Android do not have an icon displayed on Android. Only a grey circle appears instead of the propper icon.

**Comment by visionmakery** [comment]
gefixt @ManAnRuck?

**Comment by ManAnRuck** [comment]
das sollten wir nochmal überprüfen @visionmakery
