### ISSUE TITLE
[Android] Refresh der Detailseite - Ladekreis verschwindet nicht

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#107]
Description:

Refresh der Detailseite - Ladekreis verschwindet nicht

1. Go to Details
2. Pull down Page
3. Refresh Symbol appears
4. ... later
5. Refresh Symbol still there
6. ... much later
7. Refresh Symbol still there

Server Connection is ok - no error

On Android

Das war wohl ein Netzwerkfehler meines WLans, resultiert in einem Fehler und der Timeout sind 5min.

**Comment by ReggaePanda** [comment]
@ulfgebhardt wenn das Problem noch besteht, bitte reopen
