### ISSUE TITLE
📱🔥 Icons Sidebar & FAQ

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1075]
Sidebar
- [x] Wahl-O-Meter
- [x] Settings
- [x] FAQ & Support
- [x] Über DEMOCRACY
- [x] Rechtliches

FAQ
- [x] Phone
- [x] Github
- [x] Youtube
- [x] discord
- [x] Instagram ? (ist etwas anders als gewöhnlich)

**Comment by visionmakery** [comment]
ready
