### ISSUE TITLE
🐛 Antrag "Defender 2020 stoppen" nicht auffindbar

### ISSUE THREAD

**Issue by peerguenter** [demokratie-live/democracy-client#1085]
## 🐛 Bugreport
Der Antrag **19/17107 - Antrag: DEFENDER 2020 stoppen - Keine Unterstützung für Militäraufmarsch an der russischen Grenze - 12.02.2020** wird nicht aufgelisted bzw. über die Suchfunktion gefunden. 

Hier der Link zum Vorgang im Bundestag:
https://www.bundestag.de/dokumente/textarchiv/2020/kw07-de-us-soldaten-abzug-680766
https://dip21.bundestag.de/dip21/btd/19/171/1917107.pdf

### App-Version & Environment
- mobiler Android Client
- Firefox Brwoser

### Steps to reproduce
1. In der mobilen Client App (Android) oder im Browser (Firefox) nach "Defender" suchen

### Hinweis
Hier wurden unter einem Tagesordnungspunkt (TOP) gleich 2 Anträge behandelt. Könnte das die Quelle des Problems sein? Interessant ist auch, dass durch dieses Verfahren ein brisanter Punkt wie "Defender 2020" nicht direkt in der Liste der TOPs auftaucht, also in diesem Fall im "TOP 17 - Abzug von US-Soldaten aus Deutschland" versteckt ist.

**Comment by ManAnRuck** [comment]
@peerguenter danke für deinen report. 😊
Wir werden nachschauen woran dies liegt.

**Comment by peerguenter** [comment]
Besten Dank! Super Arbeit die ihr hier macht!

**Comment by ManAnRuck** [comment]
https://democracy-app.de/antrag/258951/defender-2020-stoppen-keine-unterstuetzung-fuer-militaeraufmarsch-an-der-russischen-grenze

Hier der link zum Antrag. Leider haben wir die genaue Ursache noch nicht gelöst. Du kannst jedoch nach der ProzedurID oder Dokumentennummer suchen.
ID: 258951
Dokumentennummer: 19/17107
