### ISSUE TITLE
📱 iPhone 4s PushTokenRequest

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1087]
iPhone 4s funktioniert das aktivieren der push's nicht

https://github.com/wix/react-native-notifications/issues/511

**Comment by visionmakery** [comment]
Ein Nutzer-Feedback dazu:

´´´
Hallo,

ich habe mir gerade die neue Version 1.3 installiert. Dabei ist mir gleich beim Start ein Fehler (Crash) aufgefallen.

Sobald ich unter "Settings" -> "Benachrichtigungen" auf "Aktivieren" klicke kommt es zum Absturz. Ich vermute, das liegt an meinem alten Gerät:

	iPod Touch 5, 16GB, Modell MGG82FD/A mit iOS 9.3.5.

Ich hänge mal den letzten Crashlog dran, vielleicht könnt ihr das ja trotz des alten Systemes fixen.

BTW: Versendet ihr automatisch generierte Crash-Reports per SentryCrash?

Herzlichen Gruß,


Hardware Model:      iPod5,1
Date/Time:           2020-03-19 21:15:00.00 +0100
Launch Time:         2020-03-19 21:09:31.31 +0100
OS Version:          iOS 9.3.5 (13G36)

```

**Comment by ManAnRuck** [comment]
drop support for iOS 9 for in App Donations
