### ISSUE TITLE
📱Production Pipeline vorbereiten

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1095]
für android und ios

- [ ] Android Bilder überarbeiten (über fastlane)
  - [ ] Handy Bilder überarbeiten
  - [ ] Tablet Bilder überarbeiten
- [ ] ios Bilder überarbeiten (über fastlane?)
  - [x] Handy Bilder überarbeiten
  - [ ] Tablet Bilder überarbeiten
- [x] App Beschreibungstext
- [ ] Update Text

**Comment by visionmakery** [comment]
<img width="830" alt="Bildschirmfoto 2020-03-03 um 11 29 10" src="https://user-images.githubusercontent.com/32302889/75766988-4e3bfb80-5d42-11ea-82b4-a640ce48d8b0.png">
