### ISSUE TITLE
🗣[Notification] eigener Push-Sound 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1113]
Push mit Tagesschau-App-Gong (⏱4, 🤩5)
Soundfile hier: https://drive.google.com/drive/folders/1_kfjwM17BTG9gY9zl0ZMU4pBkv6SjnD9

**Comment by buiand** [comment]
I may be interested in working on this in addition to #1070, but I just need clarification: this is to have the app play the soundfile whenever it sends a push notification?

**Comment by visionmakery** [comment]
exactly!

**Comment by ManAnRuck** [comment]
implemented for iOS
