### ISSUE TITLE
📱 [AsyncStorage] Passing null/undefined as value is not supported.

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1119]
Error
[AsyncStorage] Passing null/undefined as value is not supported. If you want to remove value, Use .remove method instead.
Passed value: null
Passed key: verification_code_expire_time

https://sentry.io/organizations/democracy-deutschland-ev/issues/1570116453/?project=1867209&query=is%3Aunresolved
https://sentry.io/organizations/democracy-deutschland-ev/issues/1570116425/?project=1867209&query=is%3Aunresolved

**Comment by johnpincock** [comment]
I had this error too, but it resolved by after replacing the undefined value for a null.

**Comment by girijakangutkar** [comment]
I am having the same error, and I have done this by setting null values to it but now I am getting this error " ERROR  Translation error: [Error: To language null unsupported, bypass this with setting forceTo to true if you're certain the iso is correct]"
