### ISSUE TITLE
SplashScreen: Logo

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#112]
**Description:**
Das DEMOCRACY-Logo inklusive Bubble verkleinern

Faulty Behaviour:
Das DEMOCRACY-Logo inklusive Bubble ist so groß und wirkt insofern unästhetisch
![img_1961](https://user-images.githubusercontent.com/32302889/36727924-446dac32-1bbf-11e8-88f5-9500446ca214.png)

Expected Behaviour:
@ulfgebhardt @ReggaePanda Logo verkleinern gemäß der Vorlage in Zeplin

Commit: [A12B34E](URL)

**Comment by ReggaePanda** [comment]
@visionmakery wir brauchen für iOS die entsprechenden Bilder in folgenden Dimensionen
https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/launch-screen/

**Comment by ReggaePanda** [comment]
Es fehlen leider noch ein paar. hab aber noch eine andere sehr gute liste gefunden, welche du besser abarbeiten kannst @visionmakery  😀 


**iPhone X Portrait iOS 11+**
~~iPhone X : 1125x2436px~~

**iPhone X Landscape iOS 11+**
iPhone X : 2436x1125px

**iPhone Portrait iOS 8.9**
~~Retina HD 5.5 : 1242x2208px~~
~~Retina HD 4.7 : 750x1334px~~

**iPhone Landscape iOS 8.9**
Retina HD 5.5 : 2208x1242px

**iPhone Portrait 7-9**
2x : 640x960px
~~Retina 4 : 640x1136px~~

**iPad Portrait 7-9**
~~1x ; 768x1024px~~
~~2x : 1536x2048px~~

**iPad Ladscape iOS 7-9**
1x : 1024x768px
2x : 2048x1536px

**iPhone Portrait 5,6**
1x : 320x480px
2x : 640x960
~~Retina 4 : 640x1136px~

**iPad Portrait Without Status Bar iOS 5,6**
1x : 768x1004px
2x : 1536x2008px

**iPad Portrait 5,6**
~~1x : 768x1024px~~
~~2x : 1536x2048px~~

**iPad Landscape Without Status Bar iOS 5,6**
1x : 1024x748px
2x : 2048x1496px

**iPad Landscape 5,6**
1x : 1024x768px
2x : 2048x1536px
