### ISSUE TITLE
FAQ: klarere Antworten

### ISSUE THREAD

**Issue by JonasLoos** [demokratie-live/democracy-client#1125]
Im [FAQ](https://www.democracy-deutschland.de/#!faq) (Website und App) könnten einige Fragen direkt klar beantwortet werden, bevor der Begründungstext kommt. Aktuell macht es teils etwas den Eindruck, als ob DEMOCRACY auf die Fragen keine klare Antwort geben möchte. 

Beispiele/Fragen:

    Gebt ihr meine Daten an Dritte weiter?
    [Nein.] Die Betreiber der App DEMOCRACY nehmen den Schutz Deiner persönlichen Daten sehr ernst. Unserer Meinung nach [...]

    Sensible Daten und Open Source – geht das?
    [Ja.] Open Source bedeutet, dass [...]

Ist kein wichtiges Issue, aber ich denke, dass das das FAQ besser verständlich machen könnte.

**Comment by visionmakery** [comment]
https://github.com/demokratie-live/democracy-client/commit/bdfdfbdc64e576c10fe86198545f185713f2a727 hab's geändert! Kommt mit der nächsten Version raus!
