### ISSUE TITLE
🐛[FAQ]: Webseitenlink 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1142]
Fehlerreport eines Nutzers
"Link < https://www.democracy-deutschland.de/#!engineering#help> wird aufgerufen/in den Safari-Browser als < https://www.democracy-deutschland.de/%23!engineering%23help> kopiert, was zu einer Fehlermeldung des Browsers führt. (FAQ & Support in der App, letzte Zeile)"

~In der Tat führt der Link auf die Landingpage und nicht zum Bugreportformular unter Engineering.~
EDIT: Der Link innerhalb von `Wie kann ich Mithelfen?` ist kaputt

![IMG_5856](https://user-images.githubusercontent.com/32302889/78133016-0500c980-741e-11ea-80d2-6bba859de0ee.jpg)

**Comment by ManAnRuck** [comment]
depends on: https://github.com/facebook/react-native/issues/28508

**Comment by ManAnRuck** [comment]
ebenso ist glaub ich das icon richtig verlinkt. es geht bei der e-mail um den link innerhalb des faq punktes "Wie kann ich mithelfen?"

**Comment by visionmakery** [comment]
mein Fehler...

**Comment by ManAnRuck** [comment]
Workaround .htaccess weiterleitung von
/help
auf 
https://www.democracy-deutschland.de/#!engineering#help%3E

**Comment by ManAnRuck** [comment]
funktioniert jetzt :)
