### ISSUE TITLE
❓Warum 'full network access' und 'prevent device from sleeping'?

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1157]
Über die Website fragt ein/e Nutzer/in:

Hallo.
Wozu benötigt eure App folgende Berechtigungen? Sind diese optional?

full network access
prevent device from sleeping

EDIT BY @ManAnRuck 
TODO: 
https://reactnative.dev/docs/removing-default-permissions

**Comment by ManAnRuck** [comment]
React Native scheint ein paar default permissions zu haben, die können wir in version 1.3.3 raus nehmen. 
Die Berechtigungen benötigt die App nicht und werden wir also in der nächsten Version entfernen

**Comment by ManAnRuck** [comment]
<img width="495" alt="Bildschirmfoto 2020-04-27 um 12 53 04" src="https://user-images.githubusercontent.com/2183135/80364371-1787ea80-8886-11ea-9851-c071e0ba2c86.png">
zukünftige permissions
