### ISSUE TITLE
Democracy-Logo-Überarbeitung

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1158]
Wir arbeiten derzeit mit 2 verschiedenen Logos (App & Bubble)

Diese haben je 2 verschiedene Blautöne.

- Macht es sinn das Bubble logo zu überarbeiten?
- ggf. gleicher Blauton
- in wie weit sollten diese zum zweck der wiedererkennung angeglichen werden
- in wie weit sollten diese sich unterscheiden um das Produkt und die organisation zu differenzieren

![logo-5.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/0a478286-632c-471c-8aa8-ccb7bef23fba)
![App Icon Android.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/c26f0dc9-026f-403c-a9eb-312cc39a4f53)

**Comment by visionmakery** [comment]
https://drive.google.com/drive/folders/1x78ErFmT7xBeMxc7eaovUxbHEJdIW4_o
