### ISSUE TITLE
🐛[Bug] Namentliche Abstimmungen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1168]
1. Report per Mail:
"Hallo, hier stimmt irgendwas nicht, oder? Siehe Screenshot.
Der Antrag wurde abgelehnt, hat aber auf der Grafik mehr Zustimmung als Ablehnung, vor allem haben laut Grafik die Linken und die Grünen den Antrag der Grünen abgelehnt."
![Screenshot_20200424-090427](https://user-images.githubusercontent.com/32302889/80200454-f07dae80-8622-11ea-8667-63bee8a6d33d.png)

Die Recherche in unserem BIO-Admin ergibt für 258396, dass es sich um eine namentliche Abstimmung handelt. 
<img width="1280" alt="Bildschirmfoto 2020-04-24 um 09 48 37" src="https://user-images.githubusercontent.com/32302889/80200701-4fdbbe80-8623-11ea-8649-33946b7159c8.png">

Auf der Website des Bundestages findet man den Vorgang, hier wird über die Beschlussempfehlung, die eine Ablehnung empfiehlt, abgestimmt, vgl.
https://www.bundestag.de/parlament/plenum/abstimmung/abstimmung?id=663
<img width="1235" alt="Bildschirmfoto 2020-04-24 um 09 48 53" src="https://user-images.githubusercontent.com/32302889/80200803-7a2d7c00-8623-11ea-9c29-697d6a4bbd6d.png">

Offensichtlich funktioniert hier das Inversmachen nicht.

**Comment by ManAnRuck** [comment]
TESTING: sollte morgen 29.04 auf internal korrigiert sein
