### ISSUE TITLE
🐛 [Bug] Tutorial öffnet bei jedem Start der App

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1186]
Ein Nutzer merkt an:

"Ich habe ein Problem mit dem Totorial. Bei jedem Start muss ich das Tutorial erneut durchlaufen. Beim letzten Schritt (der dritte?) bleibt die Bestätigung via "Verstanden" ohne Funktion. Es werden außerdem 4 Schritte angezeigt. Siehe Anhang."

![Screenshot_20200427-194419](https://user-images.githubusercontent.com/32302889/80718060-f29bad80-8af9-11ea-9bf4-1cfc50b05ef2.png)

**Comment by ManAnRuck** [comment]
mit V1.4 durch neue instruction-library sollte es behoben sein
