### ISSUE TITLE
🐛 [Verification] Client says "your number seems incorrect"

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1201]
Eine Nutzerin feedbackt:

Sehr geehrte Damen und Herren,
leider ist es mir nicht möglich mich zu verifizieren, da immer der gleiche Wortlaut kommt.
Trotzdem wurde mir ein Code zugesandt, den ich aber nicht eingeben kann.
Können Sie mir bitte helfen?

![image0](https://user-images.githubusercontent.com/32302889/81495795-3ab58f80-92b3-11ea-95b2-0319816e6bd4.png)

Ich habe eine Rufnummernprüfung durchgeführt. Nummer existiert.

**Comment by visionmakery** [comment]
FehlerCode von unserem Service-Provider.
NutzerIn kontaktiert.

**Comment by ManAnRuck** [comment]
@visionmakery warum haben wir das ticket wieder geöffnet? sollte ja jetzt mit der neuen anpassung (noch in kubernetes) nicht mehr erscheinen

**Comment by visionmakery** [comment]
ich hab das wieder aufgemacht, als ich den Kubernetes-Fehler entdeckt hatte. Kann jetzt natürlich wieder geschlossen werden:)
