### ISSUE TITLE
🖥 Fix named poll scraper

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1222]
Der namentliche abstimmungsscraper scheint nicht mehr zu funktinieren

wahrscheinlich hat sich die einstiegsurl geändert

**Comment by visionmakery** [comment]
Stimmt das mit der Änderung der Einstiegs-URL (noch)?

**Comment by ManAnRuck** [comment]
ne, das war der alte scraper, problem lag am bio-server und dem handling der Daten die er vom neuen scraper bekommen hat. 
hab das zwar im alten scraper gefixt, aber der wird nur inkludiert aber nicht mehr verwendet.
müsste den mal ganz rausschmeißen

ist jetzt aber gefixt, daher kann dieses ticket geschlossen werden
