### ISSUE TITLE
🐛[Bug] Weiße Liste beim WOM/Wahlkreis

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1310]
1. Wahl-O-Meter öffnen
2. zu Wahlkreis navigieren
3. Prozedur öffnen/Abgeordnetenprofil aufrufen
4. Zurück navigieren
5. führt zu leerer weiter Wahlkreis-Liste

**Comment by ManAnRuck** [comment]
ist behoben mit 1.3.9
