### ISSUE TITLE
[bug] app wird bei fast jedem detaillisteneintrag beendet

### ISSUE THREAD

**Issue by d2callya** [demokratie-live/democracy-client#1353]
Nutze android 8 lgv20
Extrem unübersichtlich die probleme hier. Wieso werden die features zb nicht ausgeblendet. Nur bugbehebung sollte oben stehen.

**Comment by ManAnRuck** [comment]
Hallo @d2callya,
danke für deinen Report.

Ja ich gebe dir recht, dass wir da noch Nachholbedarf haben.
Hier findest du alle issues welche als Bug's getagt sind: https://github.com/demokratie-live/democracy-client/issues?q=is%3Aopen+is%3Aissue+label%3A%22🐛+Bug%22

Könntest du mir bezüglich deines Fehlers noch mitteilen, welche Version der App und welchen Store (GooglePlay/FDroid) du benutzt?

**Comment by d2callya** [comment]
Hatte 1.2.2 aus F-Droid. Nun mit 1.3.9 ausm google app store funzt alles.
Bitte auch in F-Droid aktuell halten, das ist immer mein favorisierter store. Bei manchen devices hab ich auch kein google zugriff.

**Comment by ManAnRuck** [comment]
Hi @d2callya,
ich stimme dir da vollkommen zu! Vor allem dieses OpenSource Projekt sollte dort aktuell sein.
Leider ist der Entwickler, welcher die FDroid Store Version erstellt hat nicht mehr verfügbar und mir fehlt da noch etwas KnowHow und Zeit. Es ist jedoch einer der nächsten Tasks nach der Version 1.4 :)
