### ISSUE TITLE
Bevorstehende Abstimmung verursacht Absturz

### ISSUE THREAD

**Issue by FlorianKrammel** [demokratie-live/democracy-client#1354]
Android App: 1.2.2

Bei der Auswahl einer Abstimmung stürzt die App ab. Es gehen nur vergangene Abstimmumgen.

**Comment by ManAnRuck** [comment]
Hi @FlorianKrammel leider fehlen uns die Resourcen die Version des FDroid-Store (hast du die version daher?) auf den aktuellen Stand zu bringen.
Falls du den Google Store umgehen möchtest, kannst du die APK oder APP auch direkt von unserer Webseite herunterladen.
https://www.democracy-deutschland.de

ich bitte um Verzeihung für diesen umstand 🙏🏼

<img width="637" alt="Bildschirmfoto 2021-01-07 um 18 08 04" src="https://user-images.githubusercontent.com/2183135/103922009-755a1b00-5113-11eb-9078-7f6d2f4b9096.png">

**Comment by FlorianKrammel** [comment]
Hi, danke ja die App ist aus dem F-Droid Store installiert worden. Mit der v1.3.9 gehts.

**Comment by ManAnRuck** [comment]
😊 schön zu hören, dass die App jetzt bei dir funktioniert!

Dann würde ich dieses Ticket erstmal schließen. 
Hier https://github.com/demokratie-live/democracy-client/issues/771 das Ticket für die Reaktivierung vom FDroid-Store.

Falls dir noch was auffällt oder du Ideen für die App hast, kannst du gerne ein Issue oder eine Diskussion erstellen. 👍
