### ISSUE TITLE
F-Droid Version nicht mehr aktuell

### ISSUE THREAD

**Issue by Novellis** [demokratie-live/democracy-client#1357]
Die Repository von F-Droid bietet nur die alte Appversion 1.2.2 an. Eine Aktualisierung wäre klasse.

**Comment by ManAnRuck** [comment]
Hi @Novellis ja das stimmt und tut mir sehr leid :/ sind leider zeitlich sehr knapp an Ressourcen bei der Programmierung. Hier ist das aktuelle Ticket zum Thema F-Driod:
https://github.com/demokratie-live/democracy-client/issues/771

Falls du noch fragen hast, kannst du dieses Issue gerne reopen. :)
