### ISSUE TITLE
🌍 [Website] Team anpassen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1358]
Hey @ManAnRuck,

wenn Du die Website anpasst, mache bitte 2 Sektionen aus dem Team.
Ich würde es "Mitarbeiter" und "Praktikanten & Volunteers" nennen. Untertitel, wie im Design verwendet, sind m.E. nicht zwingend notwendig.

Mitarbeiter sind demnach: Marius Krüger, Manuel Ruck, Katrin Engler, Fabian B. und Jascha Fabian (bitte mit Nachnamen)
Praktikanten & Volunteers: Timo Sieg, Jasper Bennink, Henrik Sabirowski und Charlotte Liedtke.
Die Bilder findest Du im Google Drive, vgl. https://drive.google.com/drive/u/0/folders/1l8WccJZsLNybuoiVyWsY6UYZ2vKoTBAa.

![Spenden](https://user-images.githubusercontent.com/32302889/111517954-e8a48c80-8755-11eb-9e3a-99bfcbbd3e88.png)

**Comment by Justem2326** [comment]
Der einzige aktive Ehrenamtliche ist noch Jasper. Bis wir aber eine Rückmeldung haben ob er das möchte da mit dabei zu sein, das kann dauern und dann Text u. Bild. 
Die anderen die da aktuelle drin stehen, kenn ich z.T. nicht, weiß ob nicht ob das jetzt heißt, dass die jetzt mit dabei sein sollen. 
Was ich sonst noch für Informationen ergänzen sollte weiß ich ebenfalls nicht. 
Wir haben dafür auch ein Ticket bei MeisterTask.
https://www.meistertask.com/app/task/8YFnjgVY/homepage-anpassen-veranderung-praktikant-innen
Nächsten Donnerstag wird Jascha vorgestellt via Social Media. Die Homepage sollte bzgl. Mitarbeiter:innen & PraktikantInnen auch eher asap angepasst werden.

**Comment by ManAnRuck** [comment]
@visionmakery erste umsetzungsrunde ist durch, leider fällt das bild von Jasper noch etwas von der Größe aus dem Ramen und er hat wohl keine Kontaktdaten.
http://test.democracy-deutschland.de/#!donate
