### ISSUE TITLE
Möchte ich einen Eintag öffnen stürtzt die Android app ab.

### ISSUE THREAD

**Issue by KeyTamer** [demokratie-live/democracy-client#1371]
Möchte ich einen Eintag öffnen stürzt die Android app ab.
Habe es Auf 3 Geräten mit und ohne google Dienste versucht.

**Comment by visionmakery** [comment]
Hey @KeyTamer, welche Version hat Deine App denn? Ich vermute 1.2.2, oder?

**Comment by visionmakery** [comment]
Danke für die Info. Deine Version stammt aus dem F-Droid-Store, richtig?
Leider haben wir seit unserer 1.3-Version serverseitig keine Rückwärtskompatibilität zur 1.2.2, sie ist deshalb defekt.
Auf unserer Website https://www.democracy-deutschland.de/#!home kannst Du Dir die aktuelle Version 1.3.9 als .apk herunterladen.
Bei F-Droid haben wir derzeit Probleme unsere neue Version zu veröffentlichen, vgl. https://github.com/demokratie-live/democracy-client/issues/771

Liebe Grüße

**Comment by marek22k** [comment]
Die APK scheint jedoch propritäre Dinge von Google zu enthalten. Gibt es auch eine FLOSS Version der App, welche nicht abstürzt?

**Comment by IzzySoft** [comment]
As you've pinged me, @marek22k, I took a quick look – and there are 2 things speaking against inclusion with IzzyOnDroid: there was no development since 2021 (no commits or even releases) – and the APK size (close to 50 MB) is definitely beyond the per-app size limit at IoD (30 MB), sorry.

**Comment by marek22k** [comment]
Thanks for taking a look every time I ping you!
