### ISSUE TITLE
📱[Design 1.4] SplashScreen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1383]
Dieses Ticket beschäftigt sich mit der Evaluation des SplashScreen im derzeitigen 1.4-Design (Internal Version 1.4.0 (12)) im Vergleich zur 1.3.9

- [ ] SplashScreen 1.4 links; SplashScreen 1.3.9 Mitte; SplashScreen Zukunft rechts
- [ ] am liebsten mit einer Animation in der das DEMOCRACY-Cross größer wird und es dann einen Fade auf den ListView gibt!
 
![Splash](https://user-images.githubusercontent.com/32302889/110126988-57343280-7dc5-11eb-823a-b1a4d909156e.png)

**Comment by ManAnRuck** [comment]
@visionmakery 
Ich hab angefangen zu probieren eine animations-splash-screen library zu implementieren, wirft jedoch Fehler, weshalb ich erstmal die nicht animierte Variante umsetzen würde. 

Dafür bräuchte ich das Logo in folgenden Formaten analog zu:

ios/splash_icon.png 150 × 150
![splash_icon](https://user-images.githubusercontent.com/2183135/120546100-c1259d80-c3ef-11eb-8649-ac19f7def129.png)
ios/splash_icon@2x.png 300 × 300
![splash_icon@2x](https://user-images.githubusercontent.com/2183135/120546102-c256ca80-c3ef-11eb-8fb3-0f9dc85a411f.png)
ios/splash_icon@3x.png 450 × 450
![splash_icon@3x](https://user-images.githubusercontent.com/2183135/120546103-c2ef6100-c3ef-11eb-92ef-bab7ef096de3.png)
mipmap-hdpi/splash_icon.png 300 × 300
![splash_icon](https://user-images.githubusercontent.com/2183135/120546717-81ab8100-c3f0-11eb-914a-f8f2e114ec0f.png)
mipmap-mdpi/splash_icon.png 150 × 150
![splash_icon](https://user-images.githubusercontent.com/2183135/120546736-87a16200-c3f0-11eb-8a6f-38077a56821c.png)
mipmap-xhdpi/splash_icon.png 450 × 450
![splash_icon](https://user-images.githubusercontent.com/2183135/120546757-8d974300-c3f0-11eb-8c26-4fc4a2bcd476.png)
mipmap-xxhdpi/splash_icon.png 450 × 450
![splash_icon](https://user-images.githubusercontent.com/2183135/120546777-91c36080-c3f0-11eb-9a13-0a1ccf7db6e9.png)
mipmap-xxxhdpi/splash_icon.png 450 × 450
![splash_icon](https://user-images.githubusercontent.com/2183135/120546795-95ef7e00-c3f0-11eb-8ecb-28489ee711f3.png)

**Comment by visionmakery** [comment]
Hey @ManAnRuck, wie versprochen der Link zum Ordner: https://drive.google.com/drive/folders/1pZcMZDnTGY45VZBBnjMZZIWGt05T8J3Y?usp=sharing

**Comment by visionmakery** [comment]
ich würd den SplashScreen eine halbe Sekunde länger stehen lassen

**Comment by ManAnRuck** [comment]
Du siehst den Screen so lange, wie dein Handy braucht die App zu laden. (Dies variiert je nach Model und Alter dieser)
Nach **kurzem** schauen, habe ich keine einfache Option gefunden, eine Mindest-Anzeige-Zeit einzustellen. 

Daher schiebe ich es in Review um die Frage zu klären:
1. [ ] Aktuelles verhalten 
2. [ ] Definierte Mindest-Anzeige-Zeit ist notwendig

**Comment by visionmakery** [comment]
aktuelle Anzeige i.O.
