### ISSUE TITLE
DEMOCRACY auch über alternativen appstore Fdroid zur Verfügung stellen

### ISSUE THREAD

**Issue by elisamenne** [demokratie-live/democracy-client#1388]
Request by eventuellem neuen User: 
"Was ich mich frage, wäre es möglich eure APP auch über den alternativen appstore Fdroid zur Verfügung zu stellen? Von Oligarchen und Monopolisten Google/Alphabet habe ich mich verabschiedert (Betriebssystem meines Handys ist Lineageos) und ich möchte auch auf den Playstore mit seinen Spionageapps verzichten. Vielen Dank und viele Grüße"

**Comment by visionmakery** [comment]
closed by #771
