### ISSUE TITLE
🚀 [Feature] Abgeordnetenergebnis

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1392]
🚀 Feature

Dieses Ticket beschäftigt sich mit der Änderung des DetailView.
Wir wollen den Unterpunkt "Abgeordnetenergebnis" einführen und diese aus "Bundestagsergebnis" herausziehen.

#### fraktionelle Abstimmungen
Bundestagsergebnis enthält: PieChart, PartyChart und BarChart und Beschlusstext.

#### namentliche Abstimmungen
Bundestagsergebnis enthält: PieChart, PartyChart und BarChart
Abgeordnetenergebnis enthält: Abgeordnetenergebnisse der Favoriten (+ Option, weitere zu favorisieren).

### Design & Layout

<img width="777" alt="Bildschirmfoto 2021-04-21 um 20 18 15" src="https://user-images.githubusercontent.com/32302889/115602004-bc44d880-a2de-11eb-8972-bb38d01d12b3.png">

**Comment by visionmakery** [comment]
Ja!

**Comment by visionmakery** [comment]
Hey @ManAnRuck 

Fürs Abstände-Anpassen:
- Oben mehr
- Zwischen Abstimmungsverhalten (Abgelehnt) und Punkten mehr
- unten weniger 
![image](https://user-images.githubusercontent.com/32302889/152312754-da487a3d-efc1-492a-b5ad-bdfe96f7180c.jpeg)

**Comment by ManAnRuck** [comment]
@visionmakery Anpassungen sind unterwegs auf die **Internal**

**Comment by visionmakery** [comment]
Hey @ManAnRuck, super!
Was ich mich noch frage: Können wir die Reihenfolge so machen, wir in den Favoriten?

![image](https://user-images.githubusercontent.com/32302889/153039596-d502e648-7423-4949-86d5-005232a219a5.png)
![image](https://user-images.githubusercontent.com/32302889/153039607-8975a4f7-023b-4b44-93d2-dc4c9696db52.png)
