### ISSUE TITLE
🕷 [Android] DetailScreen - Title not Centered

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#140]
🕷 [Android] DetailScreen - Title not Centered

**Bug**

The Title "Abstimmung" is not centered in the Top Menu-Bar.

This is also the case on the ListScreen, but there it does not look that faulty.

![screenshot_20180306-204324](https://user-images.githubusercontent.com/1238238/37054657-b7582838-217f-11e8-8ce4-cee771f853e4.png)

**Expected**

Center all Titles

**Comment by ReggaePanda** [comment]
@ulfgebhardt check Zeplin Android designs ;)
<img width="788" alt="bildschirmfoto 2018-03-07 um 00 40 50" src="https://user-images.githubusercontent.com/2183135/37065221-438b5486-21a0-11e8-89b1-f8954301b9f9.png">
<img width="504" alt="bildschirmfoto 2018-03-07 um 00 41 14" src="https://user-images.githubusercontent.com/2183135/37065223-476be6b0-21a0-11e8-80bc-57029aab52f1.png">

**Comment by ulfgebhardt** [comment]
Sieht trotzdem scheiße aus ;-)

**Comment by ReggaePanda** [comment]
@ulfgebhardt ist ja auch Android ;)
