### ISSUE TITLE
📱 [1.3.10] Abstände

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1403]
- [x] Der Abstand der Carousel-Punkte zu den anderen Objekten (oben: Legende, unten: „Diese Abstimmung.../Dieses Ergebnis“) ist zu gering. Bitte um 10-20px erhöhen. 
- [x] Den Abstand vom Dropdown "Communityergebnis" zu "Deutschland" und dem Deutschland-Piktogram um 10px vergrößern

![](https://cdn.discordapp.com/attachments/388453390801436682/836194068773994506/image0.png)
https://cdn.discordapp.com/attachments/388453390801436682/836194068773994506/image0.png

![](https://cdn.discordapp.com/attachments/388453390801436682/836193797091098624/image0.png)
https://cdn.discordapp.com/attachments/388453390801436682/836193797091098624/image0.png

**Comment by ManAnRuck** [comment]
in der nächste alpha (>=252) sind die abstände angepasst. soviel bei den Bundestags->Fraktionsergebnissen sowie WOM->Fraktionen BarCharts die maximale Höhe.
