### ISSUE TITLE
📱 [1.3.10] BarChart

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1404]
- [x] Die Bezeichnungen der Parteien vertikal in der Balkenmitte ausrichten (Bundestagsergebnis & Fraktions-WOM)
- [x] Die Balken nach links um 20-30px verlängern, damit der Abstand zu den Parteinamen nicht so groß ist, dass man einen Panzer dazwischen parken kann.
- [x] Beim WOM die anderen Parteien anklickbar machen
- [x] Schon-Gewusst-Screen Untertitel zentrieren

![](https://cdn.discordapp.com/attachments/388453390801436682/836193797091098624/image0.png)
https://cdn.discordapp.com/attachments/388453390801436682/836193797091098624/image0.png

![](https://cdn.discordapp.com/attachments/388453390801436682/836194259270762526/image0.png)
https://cdn.discordapp.com/attachments/388453390801436682/836194259270762526/image0.png

**Comment by visionmakery** [comment]
@ManAnRuck jetzt ist rechts unverhältnismäßig viel Platz, vgl. 
![image](https://user-images.githubusercontent.com/32302889/116778213-d4e88780-aa70-11eb-934a-005f1f6b6e9e.jpeg)
![image](https://user-images.githubusercontent.com/32302889/116778214-d87c0e80-aa70-11eb-911a-39be9a37857b.jpeg)

**Comment by ManAnRuck** [comment]
das trifft sich gut, war heute eh mein plan die bar chart zu optimieren. nächste alpha die kommt, hat die fixes mit drin :)

**Comment by visionmakery** [comment]
![image](https://user-images.githubusercontent.com/32302889/116892708-6520fb00-ac30-11eb-99a9-97f902481d4b.png)
ChangeRequest @ManAnRuck 

Den Untertitel noch Absatz-zentrieren; passt mit den neuen Bar-Charts nicht mehr
