### ISSUE TITLE
🗣 [Feature] thematische Gruppierung über Seperator

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1420]
Dieses Ticket ist die Idee, neben den Sitzungswochenseperatoren auch Sachgebietsseperatoren einzuführen.
Die Idee entstand im Rahmen eines Gesprächs mit Nutzern/Unterstützern der App.

**Comment by ManAnRuck** [comment]
Ist perfekt für eine Discussion ;) 
https://github.com/demokratie-live/democracy-client/discussions/1422
