### ISSUE TITLE
Chart Größen optimieren

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1436]
Gerade ist das handling von SVG Größen nicht sauber.

Diese sollten sich idealerweise über 100% bzw. eine maximale Größe definieren lassen.

Möglicher Lösungsansatz:
```js
const originalWidth = 519;
const originalHeight = 260;
const aspectRatio = originalWidth / originalHeight;
const windowWidth = Dimensions.get("window").width;
return (
    <View style={{ width: windowWidth, aspectRatio }}>
        <Svg 
            width="100%" 
            height="100%" 
            viewBox={`0 0 ${originalWidth} ${originalHeight}`}>
        ...
        </Svg>
    </View>
)
```
https://stackoverflow.com/questions/61657859/how-to-find-correct-values-for-width-height-and-viewbox-with-react-native-svg/61792447#61792447

**Comment by MuhammadAakash** [comment]
Hi @ManAnRuck. 
I would like to solve this issue also am a beginner to the Open source please guide me that how i can start working on this issue.

Thanks
