### ISSUE TITLE
🚀[Feature] '21 FAQ

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1457]
## Konzept
Das Ziel ist es, im FAQ für die Erstinstallierenden Häufige Fragen zu beantworten bzw. unserer Community die Veränderung der App zu erklären. 

## File
https://docs.google.com/document/d/18EYwfkGmZnTbT20ko2xjC5jPgjZHgvTNqUd-MLEnpNw/edit

**Comment by ManAnRuck** [comment]
@ManAnRuck Link zur FAQ file @visionmakery bereit stellen
