### ISSUE TITLE
Favoriten Bearbeiten Link ergänzen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1482]

**Comment by visionmakery** [comment]
Bitte direkt als + umsetzen, ansonsten müssen wir es hinterher nochmal anfassen

**Comment by ManAnRuck** [comment]
@visionmakery 
Ich muss gestehen ich bin von einem einfachen **+** icon noch nicht ganz überzeugt, da ja mehr als nur etwas hinzugefügt werden kann (hinzufügen, entfernen und später hoffentlich Reihenfolge ändern) und ich es z.B. aus der Notizen app auch anders kenne. 
Was sind den deine Vorzüge des +? :)

![IMG_13768204405B-1](https://user-images.githubusercontent.com/2183135/126901996-071de29f-3a28-49f9-83d3-bc362ffb5cb0.jpeg)

**Comment by visionmakery** [comment]
gibt für mich keine Vorteile außer, dass es (auf kleineren Handys) geiler aussieht!
