### ISSUE TITLE
🗣Abgestimmtes in der App besser finden

### ISSUE THREAD

**Issue by elisamenne** [demokratie-live/democracy-client#1486]
User Request:  "Ich benutze die App seit einiger Zeit und finde es wirklich super, dass ich mich auf diese Weise einfach und schnell über die Vorgänge im Bundestag informieren kann.
Toll finde ich auch die Möglichkeit mitstimmen zu können und hinterher zu sehen, mit welcher Partei ich die größten Übereinstimmungen habe.
Einen Verbesserungsvorschlag habe ich auch genau in diese Richtung. Mir ging es jetzt schon öfter so, dass ich eine Abstimmung/einen Gesetzesentwurf für oder gegen, den ich gestimmt habe nochmal gesucht habe, aber in der Vielzahl der Gesetzentwürfe nicht mehr fand. Selbst, wenn ich "die Glocke" aktiviert hatte.
Besteht die Möglichkeit noch irgendwo eine Schaltfläche einzubauen, sodass man auf genau jene Gesetzentwürfe schnell zugreifen kann?
Das wäre wirklich super!"

**Comment by visionmakery** [comment]
Hey XY,

Kurze Info von mir. Das ist in der aktuellen Version (1.3.11ff.) schon über den Filter Aktivität/Abgestimmt möglich, vgl. Screenshot
![IMG_7519](https://user-images.githubusercontent.com/32302889/128222655-4bfbe65c-df84-431f-9505-1e07cf284721.jpg)
