### ISSUE TITLE
🚀[Abgeordnetenprofil] Padding Legende & ListItem oben/unten

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1491]
- [x] like #1489 & #1477, links und rechts paddings einbauen sowie
- [ ] Padding (min. 20px) zwischen Legende und Drop-Down 'Abstimmungen'
![IMG_7503.jpg](https://images.zenhubusercontent.com/5d35a18454a8bc2dbc51e9f1/d80969d8-181c-48ea-8f9a-b5ac671fe9a5)

- [ ] Padding oben unten Listelement verkleinern, sodass passend zu Listitem Bundestag/Empfohlen, Bundestag/Top100, Bundestag/Alle, WOM/Bundestag & WOM/Fraktionen
![IMG_7506.jpg](https://images.zenhubusercontent.com/5d35a18454a8bc2dbc51e9f1/0ed8cdc1-965f-4765-9a0d-3aab25a7e49d)

**Comment by ManAnRuck** [comment]
in der nächsten version mit drinnen
