### ISSUE TITLE
Neuer Splash Screen fehlt in Production

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1506]

**Comment by ManAnRuck** [comment]
@visionmakery hast du die version bei dir neu installiert? (mach es auch lieber nicht, sonst könnten deine stimmen weg sein)

Wenn ja, scheint der splashscreen gecached zu sein. Bei Neuinstallationen sollte es direkt gehen und ggf. später auch bei bestehenden Installationen. Du könntest ggf. einen Neustart deines handy machen und schauen, ob's dann passt.
