### ISSUE TITLE
feature request: Übersicht aller Einzelbewerber und deren Motivation

### ISSUE THREAD

**Issue by elisamenne** [demokratie-live/democracy-client#1512]
User Feature Request:
"Zuerst einmal meinen Glückwunsch zur guten Arbeit. Wie wäre es mit einer Übersicht über alle Einzelbewerber und deren Motivation?"

**Comment by visionmakery** [comment]
Hey Elisa, 

das werden wir nicht anbieten. Wir sind und wollen auch kein Dienstleister für den Wahlkampf von Direktkandidaten sein. Bitte verweise den Betreffenden gerne an "Die Unabhängige" oder die "Bürgerkandidaten".
