### ISSUE TITLE
Push-Settings 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1536]
für LP20 alle Pushs freigeben:

- Sitzungswoche (Sonntag vor der Sitzungswoche) **bereits aktiv**
- Diese Woche im Bundestag (in der Sitzungswoche, 1x pro Tag) **aktivieren**
- Top 100 (keine Sitzungswoche, 1x pro Tag) **aktivieren**
- Ergebnispush **bereits aktiv**

**Comment by ManAnRuck** [comment]
**Diese Woche im Bundestag (in der Sitzungswoche, 1x pro Tag)** sollte nun wieder funktionieren.

@visionmakery  Wollen wir **Top 100** noch deaktiviert lassen oder jetzt auch mit aktivieren?

**Comment by visionmakery** [comment]
Top 100 würde ich auch anschalten. Können die Leute dann ja in der App deaktivieren ;)
