### ISSUE TITLE
Bug Report: Benachrichtigungsöffnung 

### ISSUE THREAD

**Issue by elisamenne** [demokratie-live/democracy-client#1540]
User Bug report: 
"Mir wird immer mal wieder eine Benachrichtigung angezeigt.
Z.B. Jetzt abstimmen #98.....
Wenn ich auf die Benachrichtigung klicke, öffnet sich ja die Democracy-App.
Soweit, so gut.
Leider komme ich jetzt nicht bei der #98 raus.
Und selbst, wenn ich dann die Top 100 auswähle, fehlen dort das Nummernzeichen und die Dazugehörige Nummer.
Bei "#98" ist es ja noch ziemlich easy, da ist es eben die dritt-letzte Abstimmung.
Bei "#37" muss ich ewig durchzählen.
Schreibt doch einfach die Nummern dazu."

**Comment by ManAnRuck** [comment]
Sollte mit der neuen Version behoben sein oder besteht der Fehler noch immer?
