### ISSUE TITLE
🗣 User Request: Weitere Filter-Einstellungen

### ISSUE THREAD

**Issue by elisamenne** [demokratie-live/democracy-client#1541]
User Feedback:
"Bei den Filter-Einstellungen kann man leider nur nach Themen auswählen, da fehlen mir weitere Auswahl-Möglichkeiten, wie zum Beispiel "aktuell im Bundestag", "demnächst im Bundestag", also einfach nach Zeit sortiert, und "von welcher Partei wurde es eingereicht", und "namentliche Abstimmung", und, und, und.
Vielleicht auch einen "Persönlichen Ordner", mit kurzer Info über gespeicherte Politiker, eigene Abstimmungen, usw."

**Comment by visionmakery** [comment]
geschlossen mit #1525 #1279 #1071
