### ISSUE TITLE
Feature Request: Suchfunktion hinzufügen

### ISSUE THREAD

**Issue by elisamenne** [demokratie-live/democracy-client#1542]
Mehrfach das User Feedback bekommen eine Suchfunktion/ Such-Tab hinzuzufügen.

**Comment by ManAnRuck** [comment]
@elisamenne es gibt bereits eine Suchfunktion.
![suche](https://user-images.githubusercontent.com/2183135/143492051-5415c8ff-9b89-47ad-ab78-4093518079be.jpg)
