### ISSUE TITLE
🗣 Stimmen übertragen via Datei

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1573]
### Verbesserungsvorschlag eines Nutzers

Die Methode, wie die Stimmen übertragen werden (QR Codes), finde ich nicht sonderlich gut. Erstens ist die Geschwindigkeit der Übertragung unterirdisch. Die Übertragung bei mir kam übrigens auch nach 5 Minuten zu keinem Ende. Zweitens muß hier das alte Gerät sowohl vorhanden als auch funktionsfähig sein.
Man kann aber nicht grundsätzlich davon ausgehen, dass das alte Gerät weder verloren noch defekt ist. Wesentlich günstiger wäre es, wenn die App eine Datei anlegen würde, die den Inhalt hat, der auch durch die vielen QR Codes übermittelt wird. Die Erzeugung dieser Datei sollte als ein Backup automatisch erfolgen, und zwar an einer Stelle, die von den hauptsächlichen Fehlerquellen nicht betroffen ist. Um den sensiblen Inhalt vor fremden Augen zu schützen, sollte die Datei verschlüsselt werden, und zwar mit einem Schlüssel, der konfigurierbar ist.

**Comment by herrxyz** [comment]
would love to have this, tried to update using QR codes and after some minutes display went dark on old phone, this broke "upload" process ... took several minutes just to get incomplete transfer

**Comment by ManAnRuck** [comment]
@herrxyz sorry for the late reply.
this feature is now available :)

**Comment by herrxyz** [comment]
feature ist da, allerdings passiert nichts wenn ich auf "stimmen kopieren" klicke - kein share-popup, nichts in der zwischenablage, ...
v1.5.10(103690)
