### ISSUE TITLE
Anträge in Abstimmung fehlen

### ISSUE THREAD

**Issue by hermann-san** [demokratie-live/democracy-client#1576]
vergangene, populäre, sowie Gesetze in Vorbereitung sind zu sehen, aber "in Abstimmung" ist leer.  Es wäre gut wenn diese auch zu sehen wären.
Brave Browser und Firefox

![grafik](https://user-images.githubusercontent.com/7679654/167888367-414f818f-bd94-4e05-8e0b-ced3bc857cc8.png)
![grafik](https://user-images.githubusercontent.com/7679654/167888450-928df5b6-def3-4b7f-8586-0697aa7e1fed.png)
![grafik](https://user-images.githubusercontent.com/7679654/167888487-97faddf7-f1e9-4ae1-84d8-ef22351c9fda.png)

**Comment by visionmakery** [comment]
behoben mit neuer Version, vgl. www.democracy-app.de
