### ISSUE TITLE
[Bug] [Android] Back Button closes App

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#158]
Using the back button on various screens results in closing(minimizing) the app.

- Support Screen (Should navigate back to List Screen)
- Security Screen (Should navigate back to List Screen)
- (?) List Screen Tabs (Should navigate one filter, on Filter "Abstimmungen" it should close)
- Tutorial Screen (Navigates back to list - should navigate back 1 image, on first image back to list)

**Comment by ReggaePanda** [comment]
1. & 2. sollten auf jeden fall gefixt werden 3. & 4. kann schon komplizierter werden und ist glaub ich auch kein normales verhalten. ( @ulfgebhardt  bitte mit anderen Apps vergleichen)
