### ISSUE TITLE
TutorialScreen: Willkommen in der Beta

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#159]
**Description:**
Die Elemente des 1. Tutorial-Screen sind zu eng beieinander

**Faulty Behaviour:**
Der Abstand zwischen der DEMOCRACY-Bubble zum Titel "Willkommen in der Beta" ist zu eng.
Der Abstand zwischen dem Untertitel "Alles über die..." zum Handy-Bild ist zu eng.

![tutorial-screen1](https://user-images.githubusercontent.com/32302889/37662126-a53d038a-2c56-11e8-8eed-ce5125e053a2.jpg)

**Expected Behaviour:**
Titel "Willkommen in der Beta" und Untertitel "Alles über die..." im Vergleich zur Bubble 10Pkt nach unten verschieben.

Das-Handy im Vergleich zum Titel "Willkommen in der Beta" und Untertitel "Alles über die..." 20Pkt nach unten schieben. Dafür möglicherweise das Handy so tief positionieren, wie bei den folgenden Screens, vgl. Anhang

![tutorial-screen2](https://user-images.githubusercontent.com/32302889/37662319-18e786d4-2c57-11e8-93ab-0eccdab38e6f.jpg)

**App-Version:** 0.2.0 (1078)
**Handy-Version** iPhone SE

**Comment by ReggaePanda** [comment]
@visionmakery Würde für alle screens gelten

**Comment by ReggaePanda** [comment]
<img width="511" alt="bildschirmfoto 2018-03-21 um 10 45 48" src="https://user-images.githubusercontent.com/2183135/37703171-121b8136-2cf5-11e8-928f-b95dd2652a45.png">
<img width="754" alt="bildschirmfoto 2018-03-21 um 10 45 47" src="https://user-images.githubusercontent.com/2183135/37703176-14ee576c-2cf5-11e8-9105-97e0775cfcf0.png">
