### ISSUE TITLE
TutorialScreen 2-6

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#160]
**Description:**
Die Text-Elemente des 2.-6. Tutorial-Screen skalieren nicht optimal.
Die Handys sind demgemäß in unterschiedlicher Höhe dargestellt.

**Faulty Behaviour:**
Beim 2. und 6. Tutorialscreen ist der Untertitel 3-zeilig. Beim 3.,4.,5. Screen ist er 2-zeilig und das Handy rückt dementsprechend hoch.
![2-6](https://user-images.githubusercontent.com/32302889/37662783-21bca6f8-2c58-11e8-9f26-7f55c86aa30e.png)

**Expected Behaviour:**

Eine einheitliche Handy-Höhe. Vorschlag: Handy-Höhe von Screen 2. bzw. 6. 
Einheitlich 2-zeilige Untertitel, z.B. durch Silbentrennung (2. Screen) oder Abkürzungen ("&" anstatt "und" beim 6.). 
Untertitel (in der Höhe) zentriert zwischen Titel und Handy anzeigen. 

**App-Version:** 0.2.0 (1078)
**Handy-Version** iPhone Se

**Comment by ReggaePanda** [comment]
Das so fix zu machen wird schwer, da wir ja verschiedenste device großen unterstützen möchten.

Möglichkeit wäre erstmal die fixen Umbrüche zu entfernen und eine maximale breite anzugeben.
Um es jedoch selbst dann möglichst genau gleich zu machen, müssten wohl die texte angepasst werden.

**Comment by ReggaePanda** [comment]
<img width="511" alt="bildschirmfoto 2018-03-21 um 10 45 48" src="https://user-images.githubusercontent.com/2183135/37703171-121b8136-2cf5-11e8-928f-b95dd2652a45.png">
<img width="754" alt="bildschirmfoto 2018-03-21 um 10 45 47" src="https://user-images.githubusercontent.com/2183135/37703176-14ee576c-2cf5-11e8-9105-97e0775cfcf0.png">
