### ISSUE TITLE
Gesetzesverlauf designen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#168]
Gesetzesverlauf designen

Visuelle Aufbereitung der Stadien eines Gesetzes

- Vergangene Zustände
- Aktuellen hervorgehoben

- Start- und End- Punkte analysieren (falls kein Star-/Endpunkt `…` anzeigen)

#### Times:
- Dev: 2d
- Design/Orga: 1d

**Comment by ReggaePanda** [comment]
duplicate #233
