### ISSUE TITLE
[Feature] Changelog for Android PlayStore

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#192]
**Description:**

[Feature]Changelog for Android PlayStore

**Faulty Behaviour:**

No Chagelog is currently provide for the PlayStore

**App-Version:** 0.3.5

**Comment by ulfgebhardt** [comment]
This is a bit more complicated
- Structure: https://docs.fastlane.tools/actions/upload_to_play_store/#changelogs-whats-new
- Possible Solution: https://github.com/pajapro/fastlane-plugin-changelog

**Comment by ReggaePanda** [comment]
@ulfgebhardt this package should be iOS only.
is included in https://github.com/demokratie-live/democracy-client/issues/360
