### ISSUE TITLE
Search does not match substrings

### ISSUE THREAD

**Issue by alexschwarz89** [demokratie-live/democracy-client#194]
**Description:**

Search could be improved, matching substrings of the search term.

**Faulty Behaviour:**

A search for "Cannab" yields no result

**Expected Behaviour:**

A search for "Cannab" should also match "Cannabis"

**Steps to reproduce:**
- 1. Press the search icon on the upper right
- 2. Enter "Cannab"

**App-Version:** 0.3.4 (TestFlight)
**Device:** iPhone 6S / iOS 11

**Comment by ReggaePanda** [comment]
will be fixed with https://github.com/demokratie-live/democracy-server/pull/38

**Comment by ulfgebhardt** [comment]
fixed on live
