### ISSUE TITLE
App crashes in flight mode

### ISSUE THREAD

**Issue by alexschwarz89** [demokratie-live/democracy-client#195]
**Description:**

In flight mode, the app crashes to home screen if selecting an item not voted yet

**Faulty Behaviour:**

Crash

**Expected Behaviour:**

Work as in usual mode

**Steps to reproduce:**
- 1. Turn your phone into flight mode and also disable wireless LAN
- 2. Start the app
- 3. Select an item you haven't voted already

**App-Version:** 0.3.4
**Device:** iPhone 6s iOS11

**Comment by ReggaePanda** [comment]
duplicate #175
