### ISSUE TITLE
Anträge in die App integrieren

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#208]
**Description:**

Aktuell bilden wir in der App datentechnisch nur Gesetzgebungsvorgänge (DIP: 100 - Gesetzgebung) ab; zeitnah sollten wir auch Anträge (DIP: 500 – Antrag) abbilden.
![bildschirmfoto 2018-04-06 um 12 07 55](https://user-images.githubusercontent.com/32302889/38415907-33d04d0c-3993-11e8-8e16-711b70c0bcea.png)

**Expected Behaviour:**

Back-End
Vorgangstyp "Antrag" datentechnisch anbinden

Front-End-Darstellung
Unter Details rechts zusätzlich "Typ: Antrag/Gesetz" anzeigen
Unter Dokumente "Antrag/Gesetz (BT 19/...)" anzeigen

**Comment by ReggaePanda** [comment]
![antrage](https://user-images.githubusercontent.com/2183135/38555784-c59dc610-3cc7-11e8-86aa-8aa2bc9396ed.png)
