### ISSUE TITLE
Aufklappicon zu hoch in "Schon Gewusst"

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#209]
Aufklappicon zu hoch in "Schon Gewusst"

![screenshot_20180406-145808](https://user-images.githubusercontent.com/1238238/38422533-65469374-39ab-11e8-8f8a-6e0764771baf.png)
![screenshot_20180406-145813](https://user-images.githubusercontent.com/1238238/38422534-65647ec0-39ab-11e8-9e4a-6bf3bb789868.png)
![screenshot_20180406-145834](https://user-images.githubusercontent.com/1238238/38422535-657f6712-39ab-11e8-96ed-2dfb63387ed3.png)

**Comment by ReggaePanda** [comment]
ist gemerged
