### ISSUE TITLE
[Schon Gewusst] Trenner zwischen Info und Stimme zu dunkel

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#211]
[Schon Gewusst] Trenner zwischen Info und Stimme zu dunkel

![](https://user-images.githubusercontent.com/1238238/38422533-65469374-39ab-11e8-8f8a-6e0764771baf.png)

**App-Version:** 0.5.0

**Comment by ReggaePanda** [comment]
ist gemerged
