### ISSUE TITLE
🐛 schlechte Lesbarkeit des grauen Text auf weißem Hintergrund

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#223]
Accessability - Kontrast - Grauer text auf Weißem Hintergrund

Tool: Aria

https://contrastchecker.com/

https://open-indy.github.io/Koa11y/

**Comment by visionmakery** [comment]
Du meinst, dass wir graue Schift bei z.B. den Untertiteln haben und das ist kontrasttechnisch nicht optimal?
