### ISSUE TITLE
Stimmbestätigung nicht intuitiv

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#232]
**Description:**
Im UX-Test wussten einige Teilnehmer nicht, ob sie bei Erreichen des "Schon gewusst?"-Screens schon abgestimmt hatten oder nicht. 

**Faulty Behaviour:**
Die minimale Bewegung des Buttons nach rechts war nicht aufschlussreich genug, dass man den Button von links nach rechts ziehen und über dem Haken "abwerfen" muss.

**Expected Behaviour:**
Dieses Verhalten könnte dem Nutzer durch einen 50%-Opacity-Button, der sich nach rechts bewegt und über dem Haken abgeworfen wird, eindeutiger aufgezeigt werden. Optional machen wir beim ersten Abstimmen dazu einen erklärenden Screen im Schon-gewusst-Design mitsamt der Erklärung, warum die Stimme nicht rücknehmbar ist und der How-to-Abstimm-Vorschau

**Comment by visionmakery** [comment]
<img width="721" alt="bildschirmfoto 2018-04-13 um 20 13 52" src="https://user-images.githubusercontent.com/32302889/38751082-47e53234-3f57-11e8-80ad-4e5bd3b45369.png">

Weiteres Feedback dazu...

**Comment by visionmakery** [comment]
Weiteres Feedback dazu:
![bildschirmfoto 2018-04-17 um 15 07 22](https://user-images.githubusercontent.com/32302889/38871400-1442fd06-4251-11e8-9763-c4e013a5d535.png)

**Comment by alexschwarz89** [comment]
Möchte hier ergänzen, dass ich es intuitiv nicht sofort verstanden habe, dass ich überhaupt von links nach rechts ziehen kann. Habe zuerst versucht auf eines der Icons zu drücken.

**Comment by visionmakery** [comment]
Weiteres Feedback dazu
<img width="730" alt="bildschirmfoto 2018-04-28 um 17 24 32" src="https://user-images.githubusercontent.com/32302889/39398111-3a0ce4be-4b09-11e8-90fe-0a94067d95d6.png">

**Comment by ulfgebhardt** [comment]
closing in favor or current measures taken to inform the user
