### ISSUE TITLE
🛠 Icons/Assets mit Fonts ersetzen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#238]
**Description:**
Die Asbests/Icons als png scheinen die performance relativ stark zu belasten, daher sollten wir diese mit font/vector-icons ersetzen 

https://github.com/oblador/react-native-vector-icons
bei Browse all können wir alle verwenden, es können jedoch auch eigene oder weitere hinzugefügt werden. Wenn da welche bei sind, würde es jedoch schneller gehen.

**App-Version:** 0.6.3

**Comment by ReggaePanda** [comment]
@visionmakery für die fehlenden sollten wir dann eigene Vektorgrafiken erstellen

https://medium.com/bam-tech/add-custom-icons-to-your-react-native-application-f039c244386c

**Comment by visionmakery** [comment]
@ReggaePanda Alles Klar, ich stelle dir das Bundestags-Icon als .svg (in Discord) zur Verfügung – hier kann ich es leider nicht anheften:/

**Comment by ReggaePanda** [comment]
[bundestag.svg.zip](https://github.com/demokratie-live/democracy-client/files/1918790/bundestag.svg.zip)

**Comment by ReggaePanda** [comment]
es fehlen noch sag's für folgende icons @visionmakery 
* shape-active: ![shape-active](https://user-images.githubusercontent.com/2183135/39134339-b5686dfa-4716-11e8-979f-9238b7a8d3dd.png)
* shape: ![shape](https://user-images.githubusercontent.com/2183135/39134340-b590d5c4-4716-11e8-8f25-d1caad29c699.png)
* thumbsUp: ![thumbsup](https://user-images.githubusercontent.com/2183135/39134341-b5ae9eec-4716-11e8-8e00-f4e5c9cc24a4.png)
* vote-line: (sollten wir eh mit etwas anderem ersetzen) ![vote-line](https://user-images.githubusercontent.com/2183135/39134342-b5d5fa14-4716-11e8-891d-9def7b2a3ebe.png)
* voteDropZone: ![votedropzone](https://user-images.githubusercontent.com/2183135/39134343-b5f36716-4716-11e8-9940-e4539b2dd1f4.png)
* worldClock: ![worldclock](https://user-images.githubusercontent.com/2183135/39134344-b60ff00c-4716-11e8-8086-0ef8a0c0d921.png)

**Comment by visionmakery** [comment]
Glocke: ios-notification-outline

**Comment by visionmakery** [comment]
erledigt!
