### ISSUE TITLE
Push Notification

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#241]
**Description:**
Dieses Issue bezieht sich auf das Ausbleiben von Push-Benachrichtigungen.
Es gilt zu überprüfen, woran das liegt.

**Faulty Behaviour:**
Bislang ist weder für Android noch für iOS eine Push-Benachrichtigung bei einem Tester angekommen.

**Expected Behaviour:**
Insofern sich der Beratungszustand von z.B. abonnierten Prozeduren ändert, sollte der Nutzer per Push darüber benachrichtigt werden.

**App-Version:** 0.6.4

**Comment by micgro42** [comment]
Ich hatte bisher ein einzelnes Mal eine Push-Notification, nach einem Update der App. Inhalt war etwas in der Richtung "Es steht ein neuer Antrag zur Abstimmung bereit" o.Ä.
Beim Klick auf die Notification öffnete sich nur die App, ohne dass erkennbar wäre um welchen Antrag es sich handelt. Nach dieser ersten Notification hab ich keine weiteren mehr erhalten.

Plattform: Android 7
Gerät: Galaxy S7


PS: Gibt es irgendwo eine Liste mit den konkreten Features die getestet werden sollen? Es bringt wenig wenn ich für Dinge die noch nicht implementiert/fertig sind BugReports bzw. Feature Requests schreibe.
Vielleicht bin ich auch nur irgendwie aus der Testing-Mailingliste rausgefallen?

**Comment by visionmakery** [comment]
![bildschirmfoto 2018-04-17 um 10 59 35](https://user-images.githubusercontent.com/32302889/38859521-7d33e686-422e-11e8-8a36-ea54424e634e.png)

Weiteres Feedback!
