### ISSUE TITLE
CreditScreen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#242]
**Description:**
Dieses Issue bezieht sich auf den Credit Screen. Die Darstellung der 3 Logos unter UNSER BESONDERE DANK GILT AUCH wirkt nicht stimmig.

**Faulty Behaviour:**
![unadjustednonraw_thumb_65](https://user-images.githubusercontent.com/32302889/38820308-d326e58e-419d-11e8-9178-41d7bfdfa2e3.jpg)

Das Hertie Logo ist zu weit rechts und wirkt "von den anderen an den Rand gedrängt". 

**Expected Behaviour:**
![bildschirmfoto 2018-04-16 um 17 45 57](https://user-images.githubusercontent.com/32302889/38820421-24fc3cec-419e-11e8-8034-c79dfdd47225.png)

**App-Version:** 0.6.4.

**Comment by ReggaePanda** [comment]
die sind alle mit gleichen abständen positioniert, das wirken liegt an den logos selbst.
eine Möglichkeit wäre, die auf irgendwelche weise zu Bordern.

**Comment by visionmakery** [comment]
Bordern finde ich gut!
Umsortieren habe ich schon probiert, das ist die schickste Reihenfolge.

**Comment by ReggaePanda** [comment]
erstmal Hertie und start next logo tauschen
