### ISSUE TITLE
PDF-Reader in die App einbinden

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#249]
**Description:**
Dieses Issue ist auf das Feedback eines Prototyp-Testers entstanden

**Faulty Behaviour:**
Der Prototyp-Tester ist Android-7-User.
![bildschirmfoto 2018-04-17 um 15 22 16](https://user-images.githubusercontent.com/32302889/38872304-32f09040-4253-11e8-8451-1dfecc548dd9.png)

**Expected Behaviour:**
1. Lösungsvorschlag von @ReggaePanda : App-internen PDF-Reader einbinden

**App-Version:** 0.6.4

**Comment by visionmakery** [comment]
Weiteres Feedback dazu:
![bildschirmfoto 2018-04-19 um 11 02 16](https://user-images.githubusercontent.com/32302889/38982127-55aefb5c-43c1-11e8-9510-9a315820eecf.png)

**Comment by visionmakery** [comment]
Weiteres Feedback dazu: 
"Springen zwischen den Anwendungen beim Lesen der offiziellen Dokumente ist nicht schön" – Lösung: Einbinden eines internen PDF-Readers

**Comment by visionmakery** [comment]
Weiteres Feedback eines Testers via Mail:
"Bug beim Anklicken des Dokumentes "Beschlussempfehlung..." kackt das Programm ab. "
![image2](https://user-images.githubusercontent.com/32302889/39514983-0365a5d4-4df9-11e8-9302-77c3b7ebc3d2.png)

**Comment by ulfgebhardt** [comment]
Muss Sprungmarken unterstützen

**Comment by ReggaePanda** [comment]
https://github.com/wonday/react-native-pdf/issues/171

**Comment by visionmakery** [comment]
Hey @ReggaePanda 

Wie gestern besprochen: Der pdf-Reader laggt bei iOS (nach Rücksprache mit @ulfgebhardt iOS only) beim Zoomen sehr stark. 

## Lösungen
Andere Libary?

**Comment by ReggaePanda** [comment]
in einer früheren dieser library scheint es besser zu funktionieren. daher habe ich mal auf den entsprechenden branch verlinkt

https://github.com/wonday/react-native-pdf/issues/167
