### ISSUE TITLE
🚀 Gliederung nach Themengebieten

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#251]
**Description:**
In Feedback auf den Prototyp-Test schlägt der Nutzer eine Gliederung nach Themengebieten vor.

**Faulty Behaviour:**
![bildschirmfoto 2018-04-17 um 15 30 51](https://user-images.githubusercontent.com/32302889/38872769-57439d42-4254-11e8-8e97-a2ba22110131.png)

**Expected Behaviour:**
Während des Hertie-Prototyp-Tests wurde nachgefragt, ob man nicht ein Ressort/Sachgebiet-Abo als Feature anbieten könne; dies sei insbesondere für die Abgeordneten bzw. deren fachpolitischen Berater ein Key-Feature. 

Zu klären ist insofern, wie wir den Sqchgebietsfilter umsetzen und/oder ob er entkoppelt von Sachgebietsbenachrichtigungen ist?

**App-Version:** 0.6.4

**Comment by stefanxyz** [comment]
Bilder machen die App mobil unbrauchbar. Lasst das doch bitte weg.

**Comment by ReggaePanda** [comment]
@stefanxyz Ich vermute du willst vermeiden, dass "Schönheitssachen" nicht auf's Datenvolumen gehen soll.

Da wir viel Wert auf offline Funktionalität setzen (was noch später besser umgesetzt wird) würden es nur "wenn" auch offline Bilder sein welche bei der Installation runtergelassen werden. Wir müssen jedoch auf alle Fälle analysieren, wie viele es werden würden um die Installationsgröße nicht unnötig aufzublasen.

Es gibt auch alternativen, die Bilder nur mit W-Lan Funktion herunterzuladen. Das wäre ggf. ein Zwischenweg.

**Comment by stefanxyz** [comment]
Eine thematische Gliederung wäre schon schön, z.B. habe ich im Screenshot hier vier Anträge zum gleichen Thema (Syrienangriff durch die Türkei).
![screenshot_20180524-101457](https://user-images.githubusercontent.com/7532528/40475316-9617095a-5f41-11e8-8e92-293aaf28d0c7.png)

Die Schwierigkeit wird daran liegen, wer diese Einteilung vornimmt.

Nach Ressorts sortieren zu können ist sicher einfacher, hilft aber wahrscheinlich nur den Abgeordneten.

**Comment by ManAnRuck** [comment]
Mit dem neuen Realease (15.03) werden sämtliche Vorgänge anhand der Tagesordungeen gegliederd :)
