### ISSUE TITLE
DetailScreen Abstimmung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#253]
**Description:**
Dieses Issue enthält 3 reportete Unterpunkte
1. die Anzahl der Abstimmenden
2. die Ergebnisse des BT
3. den Titel des Abstimmen-Dropdown

**Faulty Behaviour:**
![bildschirmfoto 2018-04-17 um 15 41 40](https://user-images.githubusercontent.com/32302889/38873349-d8af7dd2-4255-11e8-80d9-c189219a42ab.png)

**Expected Behaviour:**
1. Ändern in 11 Abstimm**ende**
2. Durch > anzeigen, dass BT-Ergebnisse per Swipe erreicht werden können
3. "Abstimmen" in "Abgestimmt" ändern, sobald man abgestimmt hat

**App-Version:** 0.6.4

**Comment by ReggaePanda** [comment]
2. entfällt durch #271
