### ISSUE TITLE
🚀 Einmaliges Pop-Up bei 1. Glockenklick

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#254]
**Description:**
Dieses Issue bezieht sich auf das Feedback eines Prä-Testers, der sagt:
![bildschirmfoto 2018-04-17 um 15 51 00](https://user-images.githubusercontent.com/32302889/38873904-2655039e-4257-11e8-8b39-d7c04ea2617d.png)

**Faulty Behaviour:**
Der Tester bemängelt, dass ihm kein ausreichendes Feedback gegeben wird, dass er dieses Papier damit abonniert hat.

**Expected Behaviour:**
1. Lösungsvorschlag: Beim ersten individuellen Abonnieren (Glockenklick) ein Pop-Up zeigen, dass man unten nur mit Ok bestätigen kann, auf dem es in etwa heißt: "Du hast die individuellen Benachrichtigungen für dieses Papier aktiviert. Unter Side Menu > Benachrichtigungen kannst du Deine individuellen Benachrichtigungen einsehen. Du kannst diese Benachrichtigungen durch das wiederholte Klicken auf die Glocke deabonnieren"

**App-Version:** 0.6.4

**Comment by ulfgebhardt** [comment]
in-App Tutorial releated

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/demokratie-live/democracy-client/issues/372
