### ISSUE TITLE
💬 Feedback: Information zum Antragsteller

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#256]
**Description:**
Dieses Issue bezieht sich auf einen Rückfragen-Dauerbrenner: Warum zeigt ihr den Antragsteller nicht unter Details? -> UX-Test-biased, weil ich dort nach dem Antragsteller frage. Ob sonst gefragt würde, ist fraglich...

**Faulty Behaviour:**
Ein Tester schreibt: 
![bildschirmfoto 2018-04-17 um 16 03 44](https://user-images.githubusercontent.com/32302889/38874693-fab5c47e-4258-11e8-8056-e50a055c9f2f.png)
Während des Hertie-Workshops ist diese Frage auch aufgeploppt. Ein Tester hat daraus ein Spiel gemacht, den Antragsteller in 9/10 Papieren richtig geraten zu haben.

**Expected Behaviour:**
Eigene Argumentation hat die Hertie-Tester überzeugt
-> Teil unseres Kernkonzept
-> Inhaltliche, sachliche Debatte fördern 

ggfs. erklären, warum -> Side-Menu-Punkt

**App-Version:** 0.6.3

**Comment by visionmakery** [comment]
Ein weiterer Tester merkt an, dass es ihn "wirklich stört, dass der Initiator nicht bekannt ist, weil es eine wichtige Information für ihn ist". Auf die Rückfragen, ob man damit nicht das Entscheiden nach politischen Farben maximiere antwortet er, "dass er durch den Initiator weiß, in welche Richtung ein 'gut klingendes Gesetz' geht – Beispiel: Liberalisierung im Baugewerbe von der FDP heißt dann priv. Investoren das Recht geben, eigene Stadtplanungskonzepte umzusetzen".

**Comment by ulfgebhardt** [comment]
Erklärscreen

**Comment by visionmakery** [comment]
Weiteres Feedback dazu:
<img width="723" alt="bildschirmfoto 2018-04-28 um 17 15 56" src="https://user-images.githubusercontent.com/32302889/39397993-e06b5676-4b07-11e8-969c-f012bd6c65dd.png">

**Comment by sebbuc** [comment]
Mein Feedback:
Argument, dass das Wissen über den Antragsteller Beeinflussung fördern könnte, ist valide. Andererseits sehe ich bei vielen Usern die usability und Verringerung der complexity als relevanter an.

Vorschlag (ohne zu wissen, ob implementierbar): Ihr plant doch sicherlich eine Art Menü "Standardeinstellungen", in denen der User Präferenzen festlegen kann. Warum dort nicht den User entscheiden lassen, ob er den Antragsteller bereits auf der "Details"-Seite der Abstimmung sehen möchte oder erst im pdf. (dftl = er sieht ihn erst im pdf). 

Versucht, die "quick&dirties" zu binden und auch die, die sich im Detail einlesen wollen.

V0.7.5
S3 Mini JB 4.2.2

**Comment by visionmakery** [comment]
<img width="574" alt="bildschirmfoto 2018-05-14 um 09 31 15" src="https://user-images.githubusercontent.com/32302889/39983893-99884d14-5759-11e8-8673-256534d844d5.png">

**Comment by visionmakery** [comment]
<img width="602" alt="bildschirmfoto 2018-05-14 um 09 32 25" src="https://user-images.githubusercontent.com/32302889/39983939-bd3dd300-5759-11e8-998c-42ac69eba27a.png">

**Comment by visionmakery** [comment]
LÖSUNG
In-App-FAQ-Eintrag:

**Warum fehlt der Antragsteller?**
Immer wieder kam und kommt die Frage auf, warum wir den Antragsteller eines Papiers nicht ebenfalls unter den Detailinformationen eines Vorgangs anzeigen.
Dies hat einen ganz einfachen Grund: 
Eines der Kernanliegen von DEMOCRACY ist es, den Wandel von einer von Sachfragen und tatsächlichen Entscheidungen losgelösten und mit Versprechen und Emotionen geführten hin zu einer an konkreten Entscheidungen erfahrbaren und lösungsorientierten Politik für Bürger mitzugestalten. Das Abstimmungsverhalten vorab mit politischen Farben zu beeinflussen, ist insofern nicht Teil dieses Kernkonzepts.

Nehmen Sie es als Chance, ihre (politische) Einstellungen anhand der konkret vertretenen Inhalte nochmal zu überprüfen.

**Comment by ulfgebhardt** [comment]
Einstellungs möglichkeit den Antragsteller anzuzeigen?

**Comment by ReggaePanda** [comment]
see FAQ

**Comment by visionmakery** [comment]
Hallo,
über die Frankfurter Rundschau sind wir (meine Frau & ich) auf die App
aufmerksam geworden, haben jetzt ein klein wenig Erfahrung gesammelt und
möchten uns für die Idee & Engagement erst mal ganz herzlich bedanken.


Die FAQ zum Thema "Antragsteller" habe ich gelesen. Meine Erfahrung ist nun
eine andere.


Ja - es ist sehr gut Transparenz zu bieten und uns User zum Lesen der
Anträge zu motivieren.


Nein - das funktioniert aufgrund der Informationsmenge, Zeit die ich als
User dafür aufwenden kann und der politisch oft irreführend formulierten
Überschriften nicht.
Ich nehme an, dass viele User abstimmen ohne die Details zu lesen und sich
von der Überschrift "verschaukeln" lassen. Anders kann ich mir z.B. die
hohen Zustimmungswerte bei AfD Anträgen nicht erklären.


Ich bitte euch deshalb, den Antragsteller anzuzeigen und uns Usern die
Urteilskraft zuzutrauen damit umgehen zu können. Für mich würde das den
Nutzen der App ganz erheblich verbessern.


Liebe Grüße

**Comment by visionmakery** [comment]
Hallo lieber ...,

Vielen Dank für Ihre sehr durchdachte Rückmeldung und entschuldigen Sie bitte zunächst unsere verspätete Rückmeldung. 

Um direkt in die Frage einzusteigen: Was spricht aus ihrer Perspektive dafür, den Antragsteller anzuzeigen?

+ Abstimmungseffizienz aufgrund der Informationsmenge -> Parteiheuristiken ermöglichen Zeitersparnis
+ „Verschaukeln" nach Überschriften und hohe AfD-Zustimmungen bleiben ggfs. aus

Habe ich das richtig verstanden? Aus meiner Perspektive sind beide Argumente berechtigt und doch teile ich eine andere Meinung. 
Insbesondere vor dem Hintergrund des letzte Wochenende veröffentlichen Wahl-O-Meters, halte ich es für essentiell wichtig, die Abstimmungen nicht a priori durch das Anzeigen des Antragstellers zu beeinflussen. Ziel einer vergangenheitsbasierten Wahlempfehlungsapplikation ist nicht, die höchsten Übereinstimmungswerte mit seiner Lieblingspartei herbeizuführen, sondern aufgrund von Sachfragen und konkret vertretenen Positionen eine qualifizierte Aussage zur eigenen politischen Vertretung in Berlin zu bekommen. Das ist in gewissen Sinne ja eine Wette, die Sie mit ihrer politischen Grundeinstellung abschließen, vgl. hierzu auch die Argumentation vom Erklärfilmmacher Jan Sundag https://www.facebook.com/kruegermarius/videos/2071935072875192/ (ab 19:00). Ihre Argumentation, dass diese Wahlempfehlung desto qualifizierter ist, je intensiver ich mich mit den Anträgen beschäftige, teile ich wiederum.

Für mich persönlich ist es allerdings nicht schlimm, dass Menschen nur nach den Überschriften abstimmen. Wenn Sie sich dafür entscheiden, dass das die Tiefe ihrer politischen Auseinandersetzung sein soll, kann ich das akzeptieren. Bei DEMOCRACY geht es darum, (Basis-) Demokratie spielerisch zu lernen: Die Ergebnisse haben keine juristische Wirkung, sind explizit nicht auf Repräsentativität geprüft. Obschon halte ich unsere Community für extrem divers. Insofern würde mich interessieren, welche Gesetze Sie meinen, wenn Sie von hohen AfD-Zustimmungsraten sprechen. 

Ganz liebe Grüße und auf den weiteren Austausch gespannt,

Ihr Marius Krüger

**Comment by visionmakery** [comment]
Hallo lieber Marius,
vielen Dank für die Antwort. Den neuen Wahl-O-Meter habe ich gesehen, grundsätzlich gefällt er mir gut.
 
Allerdings löst das das Problem nicht:  wenn viele Menschen oft nur nach den Überschriften abstimmen ist das schlimm
-          da die Überschriften des Öfteren den Inhalt nicht wiedergeben sondern von der Bandbreite von „beschönigend“ bis „verlogen“ formuliert sein können
(in der Schule und Wissenschaft ist dies verpönt – allerdings ist dies in der Werbung und der Politik wohl eher Tagesgeschäft)
-          wer nur nach Slogans und Überschriften abstimmt verfälscht damit implizit auch das Ergebnis seines Wahl-O-Meters und dies wird ihm nicht bewusst
 
Bleibt man also auf diesem Niveau stehen, taugt der gesamte Ansatz zur Erforschung und Förderung direkter Demokratie nicht.
 
Als Indikator verwende ich deshalb oft den Antragsteller obwohl das 2-3 Klicks mehr sind. Bei den Parteien, denen ich stark misstraue (insbesondere AfD) beschäftige ich mich deshalb näher mit dem Antragstext. Ich ziehe es vor lieber nicht abzustimmen, als mich manipulieren zu lassen und damit letztlich gegen meine persönliche Überzeugung abzustimmen.
 
Das Argument, die Abstimmungen nicht a priori durch das Anzeigen des Antragstellers zu beeinflussen, ist für mich andererseits nachvollziehbar und wäre unterstützenswert unter der Voraussetzung, dass es eine bessere Lösung gibt.
 
Dazu fallen mir 2 Ideen ein:
1.       einen Indikator einführen, der die Qualität der Überschrift bewertet. In der Praxis müsste dies durch User selbst gefüllt werden was wieder Fragen aufwirft, wie sich Democracy gegen Unterwanderung schützen könnte
2.       die Möglichkeit zur Debatte (BLOG) im Userkreis, wobei es einen Mechanismus geben muss, mehrere Vorlagen in einer Debatte zusammenzufassen
 
Mir waren mehrere AfD-Anträge mit – meiner Meinung nach – irreführenden Überschriften und hohen Zustimmungsraten aufgefallen. Allerdings gibt mir die App keine Analysefunktionen um das zu rekonstruieren. Als Beispiel nenne ich deshalb einfach mal „den Einsatz chemischer Pflanzenschutzmittel wirksam reduzieren“ (AfD / Zustimmung 86%). Von den Grünen gibt es den Antrag mit der Überschrift Pestizide jetzt wirksam reduzieren (95% Zustimmung). Für dieses Beispiel wäre also eine Debatte (BLOG) im Userkreis sehr sinnvoll, denn es handelt sich bei näherem Hinsehen um extrem unterschiedliche Positionen. Eine Debatte würde den Usern m.E. sehr viel bringen. Sie würden die impliziten Annahmen verstehen und dann entlang ihrer eigenen Überzeugung sich ein Urteil bilden können.
Die Qualität und damit die Fähigkeit und Kompetenz zur direkten Demokratie zu fördern wäre nach meiner Überzeugung damit um ein Vielfaches besser.
 
Liebe Grüße

**Comment by visionmakery** [comment]
Hey...,

Das ist einfach toll, so eine lange und ausführliche Mail von Dir zu bekommen.
Dass es ein Nutzer-Forum braucht, sehen wir absolut ähnlich. Ebenso, dass die Überschriften irreführend formuliert sind. 
Aktuell schreibt ein Nutzer der App, Christian Nufer, seine Masterarbeit genau zu dem Thema. Er möchte die Informationsarchitektur anpassen und auch Mechanismen einführen, wodurch die Community die Gesetze „taggen“ und damit besser einordnen kann. Zu Deiner Rückfrage, wie man dabei Unterwanderung verhindern könnte, fällt mir spontan das systematische Kondensieren ein, womit man Widerstandswerte aus der Community ‚gegen‘ die Tags ermitteln könnte. Dieses Verfahren funktioniert natürlich umso besser, je diverser die Gruppe ist, aber auch da könnte man ja mit einer Bewertung je Tag, wie man sie z.B. bei Amazon von Produkten kennt, eine Unterschiedlichkeit erkennen, selbst wenn der überwiegende Teil der Menschen den Tag für passend befindet. 

Dass man, je intensiver man sich mit den Themen beschäftigt, auch einen qualifizierteren Wahl-O-Meter bekommt, sehen wir ganz genauso. Und ich verstehe auch Deinen Punkt, dass einem bei Abstimmen nach Überschriften nicht klar ist, dass einem da ggfs. falsche Übereinstimmungen suggeriert werden.

Ob die Partei aus vorherig genannten Gründen ein hinreichend guter Indikator ist, ist für mich allerdings ziemlich fraglich – ein Zielkonflikt. 

Ich denke, wir belassen es derzeit erstmal dabei, den Antragsteller nicht in den Detailinformationen anzuzeigen. Ich würde aber unseren Schriftverkehr gerne anonymisiert auf GitHub im entsprechenden Ticket veröffentlichen, damit wir darauf verweisen können. Wäre das für Dich in Ordnung?

Ganz liebe Grüße

Dein Marius
