### ISSUE TITLE
Feedback: verbindliche Abstimmung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#257]
**Description:**
Dieses Issue bezieht sich auf eine Rückfrage der Hertie-Tester: Warum ist meine Stimme verbindlich und kann nicht zurückgenommen werden?

**Faulty Behaviour:**

**Expected Behaviour:**
eigene Argumentation hat überzeugt: Teil unseres KERNKONZEPTS
a) Anm.: "Verbindlichkeit führt ggfs. auch zu Rückzug"
-> Verbindlichkeit führt zu Sensibilität, zu Auseinandersetzung,..
-> Bundestagsabgeordneter kann seine Stimme auch nicht mehr ändern (gleiche Spielregeln)

b) technischer Hintergrund: Datenmodell ermöglicht keinen Stimmrückzug

**App-Version:** 0.6.4

**Comment by ulfgebhardt** [comment]
no triage
