### ISSUE TITLE
Feedback: Schon gewusst?

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#258]
**Description:**
DIeses Issue bezieht sich auf die Testrunde in der Hertie-Gruppe. Eine Testerin hat angemerkt, dass unter Schon gewusst nur die Argumente der Gegenseite angezeigt werden.

**Faulty Behaviour:**
Sie hat zur Disposition gestellt, ob man z.B. im Fall einer JA-Stimme nicht auch Pro-Argumente (das beste) zu sehen bekommen sollte.

**Expected Behaviour:**
Die Gruppendiskussion hat unsere Annahme bestätigt, in diesem Fall nur Contra Argumente zu zeigen, um die Gegenposition zu schärfen. Die Einbringende hat sich später korrigiert und dem Gruppenergebnis zugestimmt

**App-Version:** 0.6.3

**Comment by visionmakery** [comment]
Anderer Tester bemängelt, dass weitere Informationen erst nach dem Abstimmen verfügbar sind. Erklärung von meiner Seite, was wir diesbezüglich vor haben, hat ihn überzeugt – findet er gut!

**Comment by ulfgebhardt** [comment]
no triage

**Comment by visionmakery** [comment]
Nutzer-Feedback via Mail
"#3 Dieses Design (senkrechte und waagrechte grüne Striche) ist sicher noch nicht final..."
![image3](https://user-images.githubusercontent.com/32302889/39516845-7066474c-4dfe-11e8-9f4a-364a6b10eb42.jpeg)

"Getestet unter iOS11 auf iPhone6:"

**Comment by visionmakery** [comment]
Gleicher Tester
"#5 Ein Hinweistext „Ziehen zum Abstimmen“ wäre hier sicher noch hilfreich. Oder eine ausgeprägtere Animation."
![image5](https://user-images.githubusercontent.com/32302889/39516956-bbaf921c-4dfe-11e8-98ba-38e7b1bf7c35.jpeg)

**Comment by ulfgebhardt** [comment]
no fix #3, fixed #5 elsewhere - closing
