### ISSUE TITLE
🗣 In-App Bug Report

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#264]
**Description:**
Dieses Issue bezieht sich auf die Rückmeldung von @ogerly, dass es einen App-internen Bug Report geben sollte, weil "der gewöhnliche internetgänger mit github weit überfordert ist"

**Faulty Behaviour:**
Es gibt kein App-internes Eingabefeld zum Melden von Bugs/Verbesserungsvorschlägen

**Expected Behaviour:**
Eine möglichkeit für Tester eine/n Bericht / Hinweis  / Info zu hinterlassen.
Dafür würde gemäß @ogerly ein einfaches Eingabefeld reichen, dass wenn jemand irgendwo auf einer seite ist und z.B. einenFfehler o.ä. findet, eine Möglichkeit hat eine Nachricht zu schreiben, die  angehangen die Seiteninfos (wo der User gerade war /ggfs. was die seine letzte produzierte fehlermeldung war) beinhaltet.
"Quasi ein mini Bug report .. unabhängig von Github"

**App-Version:** [Bitte App version hier angeben]

**Comment by ulfgebhardt** [comment]
Issues von Github in App Liste - Leute stimmen ab was als nächstes kommt
