### ISSUE TITLE
🗣 App-Bewerten-Hinweis

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#265]
**Description:**
Dieses Issue bezieht sich auf eine Anmerkung von einem Tester: @ogerly merkt an, dass es gut wäre, dass wenn man ein, zwei oder drei Abstimmungen gemacht hat, der Hinweis auftaucht, in dem jeweiligen App Store die App zu bewerten und im günstigen Fall einen positiven kommentar zu hinterlassen

Ein an nicht nervender Stelle platzierter Hinweis fruchtet dann schon mal :smiley:

**Faulty Behaviour:**
bislang kein Bewertung-Hinweis

**Expected Behaviour:**
ein Bewertung-Hinweis,

zu klären: 
Wann? 
Wo?
Wie oft?

**App-Version:** [Bitte App version hier angeben]

**Comment by ulfgebhardt** [comment]
Im Menü, alles andere nervt!

**Comment by ManAnRuck** [comment]
nach der 10. abstimmung

**Comment by visionmakery** [comment]
Zieldesign: https://cdn.discordapp.com/attachments/385901951881052161/734708384753909800/Bildschirmfoto_2020-07-20_um_11.48.26.png

**Comment by ManAnRuck** [comment]
https://github.com/MinaSamir11/react-native-in-app-review?utm_campaign=React%2BNative%2BNow&utm_medium=email&utm_source=React_Native_Now_70
