### ISSUE TITLE
Switching screens no longer possible

### ISSUE THREAD

**Issue by alexschwarz89** [demokratie-live/democracy-client#267]
**Description:**

While in screen "Bundestag" it is no longer possible to navigate to some navigation points eg. "Benachrichtigungen" or "Credits".

**Faulty Behaviour:**

After touching the menu item, navigation closes but nothing more happens.

**Expected Behaviour:**

Open the selected screen

**Steps to reproduce:**
- 1. Navigate to Bundestag screen
- 2.Try to navigate to "Benachrichtigungen"

**App-Version:** 0.6.8
**Device:** iPhone 6S iOS 11.3

**Comment by ulfgebhardt** [comment]
duplicate #330
