### ISSUE TITLE
🚀 On-Boarding: In-App Tutorial

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#270]
**Description:**
Dieses Issue bezieht sich auf die Rückmeldung eines Prototyp-Testers. Dieser merkt an, dass er unser Tutorial viel zu abstrakt und nicht gut gelungen findet. Er schlägt stattdessen ein Step-by-Step In-App-Tutorial vor. 

**Faulty Behaviour:**
Das aktuelle On-boarding sei nicht funktional. Nach dem Tutorial wisse man nicht wirklich, was man in der App machen kann.

**Expected Behaviour:**
Eine Step-by-Step-Anleitung der einzelnen Funktionen In-App:

1. List-Screen ausgegraut bis auf..
- die 3 Tabs des Segmented Control
- die Suchfunktion 
- den Burger Menu-Button
+ ggfs. Erklärpfeile und man muss alles 1x Drücken.

2. Abstimmung testweise durchgehen
- Karte öffnen (alles andere ausgegraut)
- runterscrollen
- Abstimmen
- Schon gewusst: Button ziehen
- Ergebnis einsehen

Alternativ dazu könnte man die Funktionalitäten auch mit einem anderen Tutorial darstellen.
vgl. dazu die angehefteten Screenshot aus der Bahn App, neulich von mir entdeckt:
![unadjustednonraw_thumb_67](https://user-images.githubusercontent.com/32302889/38980834-2bb7726e-43be-11e8-856e-354c14f8709b.jpg)
![unadjustednonraw_thumb_68](https://user-images.githubusercontent.com/32302889/38980835-2bdea122-43be-11e8-951b-f86ef2a18414.jpg)

**App-Version:** 0.6.7

**Comment by ulfgebhardt** [comment]
Closed in favor of: https://github.com/demokratie-live/democracy-client/issues/372
