### ISSUE TITLE
🚀 DetailScreen: Abstimmungsergebnisse

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#271]
**Description:**
Dieses Issue entstand durch die Anmerkung eines Prototyp-Testers: Dieser merkte an, dass man als Nutzer keine Idee davon habe, wie der Bundestag abgestimmt hätte. Auf meine Erklärung, dass wir dieses Ergebnis per horizontalem Swipe daneben zeigen, bemängelte er, dass man so aus der vertikalen Scroll-Logik gerissen werde. Im Weiteren Verlauf des Tests kamen wir auf weitere als die aggregierten Bürger- und Bundestagsergebnisse zu sprechen, nämlich a) Bürgerergebnis vor bzw. nach der offiziellen Abstimmung sowie b) Fraktionsergebnisse, bzw. bei namentlichen Abstimmungen sogar die Namenslisten für Ja, Nein, Enthaltung nach Fraktion. Der Tester schlug insofern vor:

**Faulty Behaviour:**

**Expected Behaviour:**
I. Zwei Ergebnis-Bereiche (vertikal untereinander) "Klassen" – nicht zuklappbar (kein Drop-Down)
1. Communityergebnis (gesamt)
2. Bundestagsergebnis (gesamt)

II. Unter diesen Pie-Charts ist mit vollen und leeren Punkten angedeutet, wie vielen weitere Ergebnisansichten es in der jeweiligen "Klasse" noch gibt. Weiterhin kann mit ">" rechts neben dem Pie-Chart symbolisiert werden, dass man horizontal swipen kann:
1. Communityergebnis (gesamt) – Communityergebnis (vorher) – Communityergebnis (nach)
2. Bundestagsergebnis (gesamt) – Fraktionsergebnisse als Bar-Charts – ...
 
I. ist noch für den Prototyp umzusetzen.
II. ist MVP

**App-Version:** 0.6.7

**Comment by ReggaePanda** [comment]
1. ist umgesetzt daher jetzt in MVP geschoben
