### ISSUE TITLE
Fehlende Prozeduren checken (Vergangene) 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#275]
**Description:**
Dieses Issue bezieht sich auf einen festgestellten Fehler von uns; heute morgen um 8.00 Uhr waren die Vergangenen Gesetze in allen Apps (Dev/Beta/Alpha_old) weg. 

**Faulty Behaviour:**
Alle Apps zeigen unter vergangen nur noch 1 Gesetz. Alle anderen waren kurzzeitig weg – nach ungefähr 1h waren sie plötzlich wieder da. Eine erste Fehlersuche in den Diffs hat "keine fehlenden Beratungsstände" als logische Fehlerursache ergeben. Die Fehlerursache ist zu ermitteln. @ReggaePanda schlägt vor: 
Weiterhin gilt zu prüfen, ob und inwiefern davon die Ergebnisse der Nutzer i.S. eines Datenverlust betroffen sind.

**Expected Behaviour:**

**App-Version:** 0.6.8
[diffs.zip](https://github.com/demokratie-live/democracy-client/files/1931550/diffs.zip)

**Comment by ulfgebhardt** [comment]
Guess: Problem with Stati - should be fixed in https://github.com/demokratie-live/democracy-client/pull/314
