### ISSUE TITLE
Play Store: "Voice down like a member of the Bundestag" 🤦

### ISSUE THREAD

**Issue by micgro42** [demokratie-live/democracy-client#276]
**Description:**

The English description of the new beta version is obviously machine translated and thus quite embarrassing. Please adjust this, even if it is by just using a better machine translation, like that from https://deepl.com/translate . It translates `Stimme ab wie ein Miglied des Bundestages` to `Vote like a member of the Bundestag`

**Faulty Behavior:**

The english teaser of the new beta version of the app says: `Voice down like a member of the Bundestag`

**Expected Behavior:**

It should say: `Vote like a member of the Bundestag`
Alternatively: deactivate automatic translation, if that is possible. Original German is better then bad English

**Steps to reproduce:**
1. Use a phone which is set to use english as system language
1. become a tester
1. Go to https://play.google.com/store/apps/details?id=de.democracydeutschland.app.beta

**App-Version:** N/A

**Comment by ulfgebhardt** [comment]
Translated all Englsh Variants in the PlayStore
