### ISSUE TITLE
🐛 App does not start when no Server present initially

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#281]
**Description:**

App does not start when no Server present initially

**Faulty Behaviour:**

Stuck in Startscreen if App cannot load any Data

**Expected Behaviour:**

Start anyway

**App-Version:** [0.7.1]

**Comment by sebbuc** [comment]
hatte ich heute um 17:19/17:20 ebenso, beim dritten Startversuch dann erfolgreich - 1 min später.
Version 0.7.5
S3 Mini JB 4.2.2

**Comment by ulfgebhardt** [comment]
Seems 2 be fixed - starttime is a bit longer

**Comment by ulfgebhardt** [comment]
This Problem occurs if the Host is reachable but does not answer the request from the App. If the Host is not reachable (no internet connection), the app starts as expected

**Comment by sebbuc** [comment]
ich mach den nochmal auf nach gespräch mit ulf am Freitag:

Heute wieder probiert, die Beta zu öffnen. Die app hatte ich tags zuvor offen, jedoch nicht beendet (also im Hintergrund weiter aktiv). Der Startbildschirm öffnete sich immer wieder (über 15 mal), danach brach die app die Logon-Versuche ab. Keine 10 Sekunden später habe ich app nochmals öffnen wollen, diesmal sofort und ohne Probleme funktioniert.

PS: Folgenden Gegenversuch habe ich gemacht: Wenn ich die app nach der Nutzung nicht im Hintergrund weiterlaufen lasse, sondern komplett beende, dann laufen zig Neustart-Versuche ordnungsgemäß.

Samsung S3 Mini
4.2.2. JellyBean

**Comment by ManAnRuck** [comment]
mit der neuen version tritt dieser fehler nicht mehr auf 🏵
