### ISSUE TITLE
🐛 Prevent Double Navigation on iOS

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#289]
**Description:**

Remove the Android condition as soon as the Library (react-native-navigation) ist fixed

**Faulty Behaviour:**

https://github.com/demokratie-live/democracy-client/pull/221/files#diff-44768e43061f276b4bf6d9cca44cc680R15

TODO: link correctly after merge

**Expected Behaviour:**

Also prevent Double Navigation on iOS

**Steps to reproduce:**
- 1. Click List Item
- 2. Quickly click another
- 3. Both pages open
- 4. ...
- 5. Profit

**App-Version:** [0.7.1]

Rel:
- #183 
- #221
- https://github.com/wix/react-native-navigation/issues/271
- https://github.com/wix/react-native-navigation/issues/2655
- https://github.com/wix/react-native-navigation/issues/2676

**Comment by ManAnRuck** [comment]
mit neuer navi lib nicht mehr gültig
