### ISSUE TITLE
Hakenposition im Listview nicht optimal

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#300]
**Description:**
Dieses Issue bezieht sich auf die Umsetzung des Issue #246  . 

**Faulty Behaviour:**
Die Haken sehen bei meinem Handy minimal nach links verschoben und nicht zentriert unter der/dem Zahl/Dach aus. Insbesondere beim Doppelhaken fällt dies stark auf. 
![unadjustednonraw_thumb_6f](https://user-images.githubusercontent.com/32302889/39354946-1c7c7098-4a0c-11e8-935e-f7bc588ac16d.jpg)
![unadjustednonraw_thumb_70](https://user-images.githubusercontent.com/32302889/39354953-2064fe82-4a0c-11e8-8ad9-f7aa44a8dbe8.jpg)

**Expected Behaviour:**
Die Haken stehen zentriert unter der/dem Zahl/Dach.

**App-Version:** 0.7.4

**Comment by ReggaePanda** [comment]
@visionmakery das ist eine visuelle Täuschung ;) das icon ist zentriert
<img width="194" alt="bildschirmfoto 2018-04-27 um 12 00 41" src="https://user-images.githubusercontent.com/2183135/39358625-f908ae78-4a16-11e8-9fa1-1dbf68f7e862.png">

**Comment by ReggaePanda** [comment]
@visionmakery sehe, dass das SVG in sich schon verschoben ist (siehe Bild)
<img width="161" alt="bildschirmfoto 2018-04-27 um 12 37 43" src="https://user-images.githubusercontent.com/2183135/39358897-18fca9ea-4a18-11e8-89ac-b0e070f60dc9.png">
