### ISSUE TITLE
🛠 Erklärscreen: Abstimmungsrichtung klären

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#311]
**Description:**
Dieses Issue bezieht sich auf die Anmerkung eines Prototyptester per Mail.
Der Tester merkt an: "In vielen Abstimmungen wird von den beteiligten Ausschüssen empfohlen, gegen den vorgelegten Vorschlag zu stimmen. Beispiel anbei. "
![image](https://user-images.githubusercontent.com/32302889/39417720-7a280526-4c56-11e8-9c74-50334a8a92e9.png)
Der Tester fragt sich, auf was sich dann seine Stimme bezieht: "Ist mein grüner Daumen dann für den Antrag oder für den Abstimmungsvorschlag?"
Er merkt weiterhin an: "Wahrscheinlich ist das ganz eindeutig und es reicht eine einmalige Erklärung beim Einstieg in die App."

**Faulty Behaviour:**
Bislang steht In-App keine Erklärung, ob man über den ursprünglichen Antrag, den veränderten Antrag, Änderungsanträge, die Beschlussempfehlung oder den schlussendlichen Antrag (!) abstimmt.

**Expected Behaviour:**
Insofern wir einen Erklärscreen etablieren, sollten wir darauf vermerken, dass man immer über die letzte Variante des Antrags von der Vorgangs-initiierenden "Partei" (hier nicht nur i.S. einer politischen Partei gemeint) abstimmt. 

**App-Version:** 0.7.5

**Comment by dkohtes** [comment]
Ja, genau so hatte ich das gemeint. Ich bin da vor allem drüber gestolpert, weil die in meiner Liste auftauchenden Anträge, die ich mir angeschaut habe, zufällig alle von der Opposition waren und dementsprechend von den Ausschüssen immer empfohlen wurde, diese abzulehnen. Das entsprechende Dokument mit der Abstimmungsempfehlung der Ausschüsse ist dann auch immer das letzte (nach meiner Interpretation auch neueste) Dokument und hat bei mir zu dieser Unsicherheit geführt.

**Comment by ReggaePanda** [comment]
ToDo: Ergebnisdarstellen entsprechend analysieren und anzeigen
