### ISSUE TITLE
Darstellung Search-Resultate 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#312]
**Description:**
Dieses Issue bezieht sich auf ein Feedback eines Testers. 

**Faulty Behaviour:**
![image1](https://user-images.githubusercontent.com/32302889/39417896-8ef828d6-4c57-11e8-93d4-f635888d97d4.png)

**Expected Behaviour:**
"Wenn ich ein Vorhaben favorisiert habe, dann sollte das auch in der Liste sichtbar sein."
Es geht ihm also um die Darstellung der Such-Resultate. Anstatt Untertitel möchte der User eine Ansicht mit Glocke. Es gilt, darüber nachzudenken, ob man die Darstellung aus BurgerMenu/Benachrichtigungen adaptiert oder eine andere?

**App-Version:** 0.7.5

**Comment by magnusmunter** [comment]
Ja, es geht mir um die Darstellung der Suchresultate.
Allerdings eher um die Zahl und den Pfeil an der Seite, der hat sich nämlich nicht verändert, nachdem ich in der Detailansicht favorisiert habe.

Untertitel ist ok so, keine Glocke nötig.
