### ISSUE TITLE
🚀 Posting einzelner Abstimmung(en) in relevanten "Social Medias" zulassen! 

### ISSUE THREAD

**Issue by sebbuc** [demokratie-live/democracy-client#315]
Idee/Improvement: 

Unter den ABSTIMM-BUTTONS Posting der Abstimmung in "Social Medias" zulassen mit maximal 2 Klicks. Geht das nicht auch ohne dass alles von Twitter und Co getrackt wird ? 

Vorteil: Usern ermöglichen, Followerpower zu nutzen, Beteligung an der Democracy-App zu erhöhen. Könnte bei Versand von für den User und seinen Empfänger/Follower relevanter Abstimmungen die Erfolgschancen einer Anmeldung in der App erhöhen. 

**App-Version:** 0.7.5
S3 Mini, JellyB 4.2.2

**Comment by visionmakery** [comment]
Weiteres Feedback
<img width="593" alt="bildschirmfoto 2018-05-14 um 09 08 06" src="https://user-images.githubusercontent.com/32302889/39983041-93a5b6d2-5756-11e8-86f7-4b48ac7c609a.png">

**Comment by ReggaePanda** [comment]
@sebbuc Danke für deine Issues :)
Dieses Feature steht auch bereits auf unserer liste. Voraussichtlich wird Share-Button oben bei der Glocke hinzugefügt, welcher die nativen share Funktionen des Gerätes aufruft. Dadurch ist ein dauerhaftes Tracking der jeweiligen Dienste nicht möglich.

Anders wie bei den meisten Webseiten wird hier nicht ein widget des jeweiligen Dienstes eingebunden, sondern es wird erst beim klick auf den button der Titel und die Nachricht an die auf dem Handy installierten Dienste übermittelt mit welchem man sharen möchte. Alternativ gibt es dort auch glaub ich die Link-Kopieren option mit welcher man auch dann über den browser einen link sharen kann.

Developer-Info: https://facebook.github.io/react-native/docs/share.html

**Comment by ReggaePanda** [comment]
Was ich noch vergessen habe. wir haben noch ein paar Probleme für die Beta-Phase. Hierfür brauchen wir noch eine Weiche für Leute, die noch keinen zugriff auf die App haben und eine Desktop-Anzeige
