### ISSUE TITLE
Tutorial: Blauer Kreis

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#316]
**Description:**
Dieses Issue bezieht sich auf das Feedback eines Testers via Mail.

**Faulty Behaviour:**
"#1 Welche Bedeutung hat dieser Kreis? Das hat sich mir nicht erschlossen."
![image1](https://user-images.githubusercontent.com/32302889/39516413-33e25a96-4dfd-11e8-9061-629fd1f96290.jpeg)

**Expected Behaviour:**

**Steps to reproduce:**

**App-Version:** 0.7.5

**Comment by ulfgebhardt** [comment]
Klicken führt zum scrollen des tuts - closing
