### ISSUE TITLE
VoteData is lost (Android)

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#322]
**Description:**

The Vote Data on my Phone was lost for some reason

**Faulty Behaviour:**

- I only see grey buttons on Detailscreen
- I did not reinstall the App
- I updated the App
- I can click the grey buttons and Vote again (with no effect on the community result - just my local vote is set again(to the new value)

**Expected Behaviour:**

- Don't lose data
- Don't lose data on update
- Don't allow to click grey buttons

**Steps to reproduce:**
- 1. use
- 2. lose data
- 3. rage
- 4. ...
- 5. Profit

**App-Version:** 0.7.6

**Comment by visionmakery** [comment]
Nach dem Softwareupdate auf iOS 11.3

**Comment by ReggaePanda** [comment]
https://github.com/oblador/react-native-keychain

wir sollten zur Sicherheit auch lokal auf dem handy die Abstimmungsdaten mehr verschlüsselt hinterlegen. Dies sollte die Persistents ebenfalls verbessern.

ebenfalls sollte dann auch noch der cache vom graphql-client deaktiviert werden.
https://github.com/apollographql/apollo-client/issues/1419#issuecomment-287440150
