### ISSUE TITLE
Featurevorschlag: eigene Notiz zur Abstimmung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#327]
**Description:**
Ein Tester schlägt vor,
<img width="726" alt="bildschirmfoto 2018-05-14 um 09 02 58" src="https://user-images.githubusercontent.com/32302889/39983988-eb34c8ae-5759-11e8-8c4c-3f1b6dcdfa4a.png">

**Faulty Behaviour:**

**Expected Behaviour:**
Demnach möchte er für sich in einer kleinen Notiz dokumentieren können, warum er so abgestimmt hat...

**App-Version:**

**Comment by ulfgebhardt** [comment]
Forum löst dieses Problem
