### ISSUE TITLE
aktuellen stand ausblenden bei nicht abgestimmt

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#328]
Sehe gerade, dass wir den aktuellen stand abgelehnt/angenommen anzeigen, auch wenn man selbst noch nicht abgestimmt hat. Bei diesen Fällen sollten wir den Stand evtl ausblenden oder in abgestimmt ändern. Vielleicht mag einer von euch dazu ein Ticket erstellen

Was ist mit Zurückgezogen?

**Comment by ReggaePanda** [comment]
@ulfgebhardt ich denke zurückgezogen muss dabei nicht beachtet werden. Da könnten wir uns auch fragen, ob überhaupt über solche vorhaben abgestimmt werden können soll, da es der Bundestag ja auch nicht tut und so nie eine Vergleichsmöglichkeit kommen wird. Bei zurückgezogen wäre wohl interessant anzuzeigen, warum diese zurückgezogen wurden, aber ich glaube diese info steht uns nicht zur verfügung.
