### ISSUE TITLE
SideMenu-Fehler

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#330]
**Description:**
Dieses Issue bezieht sich ebenfalls auf die Rückmeldung von Magnus, er schreibt:
"Hallo Team,
Nach einer Weile herum spielen in der Applikation hatte ich einen Fehler bemerkt und wollte eine Support E-Mail schreiben."

**Faulty Behaviour:**
"Im Seitenmenü funktionierten dann die Punkte Support und Credits nicht mehr. Nach einem Klick dadrauf kann man nur zur Bundestagsliste zurück, die App hat keine andere Seite aufgerufen. Lediglich der Link Tutorial funktioniert nach wie vor."
![image1](https://user-images.githubusercontent.com/32302889/40271160-a9e78a82-5b99-11e8-9938-570a2d165afa.png)

Hatte den Fehler ebenfalls schon diverse Male in iOS.
Können wir das nochmal untersuchen?

**Expected Behaviour:**
"Everytime"-Funktionales Side-Menu

**App-Version:** 0.7.7

**Comment by ReggaePanda** [comment]
Dies liegt am verhindern, dass man eine Seite mehrmals aufrufen kann. Lösungsweg ist bereits bekannt, muss aber noch umgesetzt werden
