### ISSUE TITLE
💬 Datenbank-Feld "Fraktion der Antragsteller" anlegen und unter "Details" auflisten

### ISSUE THREAD

**Issue by stefanxyz** [demokratie-live/democracy-client#341]
**Description:**

Enhancement: Die "Fraktion der Antragsteller" als Datenbank-Feld anlegen und unter "Details" listen, damit diese Information auch mobil schnell verfügbar ist.
Eigentlich müsste es das Feld ja schon geben (da eine Wahl-O-Mat-Funktion der App ja beworben wird).

**Faulty Behaviour:**

Um die Antragsteller zu sehen, muss man das PDF-Dokument öffnen, was schon bei WLAN gute 10sec dauert und bei wiederholtem Aufruf irgendwie dann nur bei jedem 2ten Mal ausführen funktioniert und ein hineinzoomen erfordert (beim Smartphone).

**Expected Behaviour:**

Eine Rubrik "Fraktion der Antragsteller" unter Details listen, wo der Text aus dem Dokument "Antrag" übernommen wird.

**Steps to reproduce:**
- 1.
- 2.
- 3.
- 4. ...
- 5. Profit

**App-Version:** [Bitte App version hier angeben]

**Comment by ReggaePanda** [comment]
duplicate #256
