### ISSUE TITLE
🐛 "Schon gewusst ?" Pros/Cons teilweise von teiltransparentem Bereich geblockt

### ISSUE THREAD

**Issue by sebbuc** [demokratie-live/democracy-client#349]
![screenshot_2018-05-26-15-58-15](https://user-images.githubusercontent.com/38894101/40579048-ddd8fc6e-611f-11e8-8cd6-db7992913638.png)

**Description:**

Darstellungsproblem unter "Schon gewusst ?"

**Faulty Behaviour:**
 
Der Textbereich, in dem sich später die Pros/Cons/Links wiederfinden sollen, lässt sich nicht komplett aus dem teiltransparenten Bereich "Deine Stimme ist verbindlich ..." herausscrollen.

**Expected Behaviour:**

Durch Scrollen lässt sich der gesamte Rahmen/Textbereich hinter der Teiltransparenz hoch und runter bewegen. 

**Steps to reproduce:**
- 1.
- 2.
- 3.
- 4. ...
- 5. Profit

**App-Version:** 0.7.9 (aber auch zuvor schon)
S3 Mini JB 4.4.2

**Comment by ReggaePanda** [comment]
@sebbuc Eigentlich sollte der transparente Bereich beim scrollen langsam ausgeblendet werden, sodass kurz danach alles gut lesbar sein sollte.

Bleibt der Text mit dem Transparenten Hintergrund bei dir auch nach dem scrollen sichtbar?

**Comment by ulfgebhardt** [comment]
@ReggaePanda Ja das ist ein Problem - auf Android 4 verschwindet der Hinweis nicht - auch wenn man scrollt. Auf Android 6 funktioniert es (zumindest in Landscape Mode - auf Normal Mode kann ich es nicht testen - text zu kurz)

**Comment by ReggaePanda** [comment]
<img width="468" alt="bildschirmfoto 2018-06-01 um 08 52 46" src="https://user-images.githubusercontent.com/2183135/40825963-84e19aa4-6579-11e8-88b0-7017c2ef449a.png">
Leider kann ich das Problem im emulator mit Android 4.4 KitKat nicht Simulieren.

**Comment by ulfgebhardt** [comment]
Schon gewusst wird mit dem Wahl-O-Meter geupdatet und hat einen entsprechenden Abstand nach unten - fixed
