### ISSUE TITLE
🗣 Bedeutungskonfusion des Wortes "Abgestimmt", Vorschlag

### ISSUE THREAD

**Issue by sebbuc** [demokratie-live/democracy-client#350]
Gut finde ich, dass nun, bevor man selbst einen bereits im BT abgestimmten Antrag selbst bearbeitet hat, in der Detailansicht nur noch "abgestimmt" statt "zugestimmt" / "abgelehnt" erscheint. Top!

Die eigene Stimme am Ende der Detailseite wird mit "Abgestimmt" überschrieben, macht es nicht Sinn, hier eine andre Überschrift zu wählen, um eine Bedeutungskonfusion des Wortes "Abgestimmt" zu vermeiden? Vielleicht besser: "Deine Stimme" ? Oder ähnlich. Wäre auch persönlicher.

**Steps to reproduce:**
- 1.
- 2.
- 3.
- 4. ...
- 5. Profit

**App-Version:** 0.7.9
S3 Mini JB 4.4.2

**Comment by ulfgebhardt** [comment]
Support von @ReggaePanda & @ulfgebhardt

**Comment by visionmakery** [comment]
Hey @sebbuc, ich schließe das Ticket, weil sich bis jetzt niemand anderes darüber beschwert hat!
