### ISSUE TITLE
📥 🗣 Nicht-/Namentliche Abstimmung

### ISSUE THREAD

**Issue by ReggaePanda** [demokratie-live/democracy-client#351]
**Description:**
Es sollte eindeutiger dargestellt werden, ob es sich bei einem Bundestagsergebnis um eine Namentliche oder Nicht-Namentliche Abstimmung handelt.

**Faulty Behaviour:**
Derzeit ist nahezu nicht erkennbar, ob es sich um eine Namentliche oder Nicht-Namentliche Abstimmung handelt und wie man bei einer Nicht-Namentlichen Abstimmung auf das Ergebnis kommt.

**Expected Behaviour:**
Schnell und eindeutig erkennbar machen um welchen Abstimmungstyp es sich handelt.
Bei Nicht-Namentlichen Abstimmungen sollte der Abstimmungstext aus dem Plenarprotokoll in der App zur verfügung gestellt werden.

**Comment by ulfgebhardt** [comment]
@visionmakery Please Design!
