### ISSUE TITLE
🛠 Navigation with Swipe

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#356]
** Description **

Improve UserXP by allowing swipe on Detail-Screen
- left -> ListScreen
- right -> next DetailScreen for the Procedure below the one currently open (order like ListScreen)

**Faulty Behaviour:**

Left swipe will work on iOS as soon as #354 is fixed-

**App-Version:** [0.7.9]

**Comment by ulfgebhardt** [comment]
@visionmakery Meinung dazu?

**Comment by visionmakery** [comment]
left -> ListScreen
right -> next DetailScreen for the Procedure below the one currently open (order like ListScreen)

Find ich Geil!!!
