### ISSUE TITLE
🐛 Ergebnisrichtung (UI+bundestag.io) 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#369]
**Description:**
Dieses Issue bezieht sich auf den Bug Report eines Testers: Ihm ist ein Bug aufgefallen, nach dem die Ergebnisse mancher Abstimmungen falsch oder evtl. invertiert dargestellt werden. Das sei ihm aber bisher nur bei diesem Antrag aufgefallen. 

**Faulty Behaviour:**
Als Bsp. führt er die Abstimmung über den Antrag mit Procedere-Nr. 230141 "Umfassende Grenzkontrollen sofort einführen – Zurückweisung bei unberechtigtem Grenzübertritt" (Drucksache 19/41) der AFD an.
![screenshot_20180604-162910](https://user-images.githubusercontent.com/32302889/40965194-5fd594d6-68ad-11e8-8287-9c4ceb06d347.png)

In diesem Fall wurde namentlich über die Beschlussempfehlung abgestimmt mit dem Ergebnis (in Originaltext) "Annahme der Beschlussempfehlung auf Ablehnung". Die zustimmenden Parteien (CDU, SPD, FDP, B90, Linke) stimmen insofern auf Antragsebene gegen den Antrag (vgl. https://www.bundestag.de/parlament/plenum/abstimmung/abstimmung?id=504) 

**to Check/Analyse**
Warum ist es bei diesem Antrag unterschiedlich?
An welchem Marker unterscheidet sich das von den anderen namentlichen Abstimmungen?

**Expected Behaviour:**

**App-Version:** 0.7.9.

**Comment by visionmakery** [comment]
Passende Kritik an dieser Stelle auch:
<img width="783" alt="bildschirmfoto 2018-06-05 um 11 00 36" src="https://user-images.githubusercontent.com/32302889/40966053-bb9f45b2-68af-11e8-9e93-4a81d7d07189.png">

**Comment by ReggaePanda** [comment]
duplicate of #378
