### ISSUE TITLE
TypeError: Alert is undefined

### ISSUE THREAD

**Issue by roschaefer** [demokratie-live/democracy-client#37]
Description:

When I try to vote on a poll, i.e. click on :+1: :-1: or :large_blue_circle: , I see an error.

Faulty Behaviour:

![selection_166](https://user-images.githubusercontent.com/2110676/34032614-435e4770-e177-11e7-99bd-1c7579b3ff04.png)

Expected Behaviour:

I should see "Du hast abgestimmt".

Steps to reproduce:

- 1. `yarn start:web`
- 2. Open http://localhost:3000/
- 3. Click on "Gesetz zur effektiveren und praxistauglicheren Ausgestaltung des Strafverfahrens"
- 4. Click on a button below
- 5. Enjoy `TypeError: __WEBPACK_IMPORTED_MODULE_3_react_native__.Alert is undefined`

Commit: [A12B34E](URL)

**Comment by ulfgebhardt** [comment]
Fixed
