### ISSUE TITLE
🚀 SMS Verification

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#370]
**Description:**

[US02a](https://github.com/demokratie-live/democracy-client/wiki/US-02a-Erster-Start-der-App---Mobilger%C3%A4t)
---
**Konzept Frontend**
a) Angebot, sich zu verifizieren im Tutorial (SMS only)
....
b) Bei der ersten Abstimmung und jeder weiteren Abstimmung
...
- M. gelangt zum Verification-Screen – hier wird ihre Handynummer abgefragt – Unten steht “Warum mit der Handynummer registrieren?”

b1) M. geht den Weg
- Nach der Eingabe ihrer Handynummer fordert M. einen Aktivierungscode mittels Klick auf “Code anfordern” an
- SMS-Push übermittelt M. den für ihre Handynummer gültigen Registraturcode
- M. überträgt den Code in das Formular und klickt “Verifizieren”
- M. gelangt zu Schon gewusst?

b2) M. klickt auf Zurück und landet wieder auf dem Detail-Screen.

** Ergebnis-Bias**
Bundestagsergebnis (in App + Browser) ab Vergangen (Verfügbarkeit) für alle anzeigen – IMMER

Community-Ergebnis
a) in-app – ab Voting
b) im Browser, wenn Bundestagsergebnis vorliegt

**Konzept Backend**

Technisch

---
**Layout**

![](https://github.com/demokratie-live/democracy-assets/raw/master/userstories/US02/02a_1.jpg)
![](https://github.com/demokratie-live/democracy-assets/raw/master/userstories/US02/02a_2.jpg)

---
**Design**
![bildschirmfoto 2018-06-11 um 15 05 42](https://user-images.githubusercontent.com/32302889/41233196-f7730532-6d88-11e8-81f3-d44e9023d850.png)

---
**Umsetzung**
---

**Comment by visionmakery** [comment]
Ui ist umgesetzt – Wir sollten das, wenn wir die SMS-Verification ausarbeiten nochmal gemeinsam auf UX überprüfen;)
