### ISSUE TITLE
🚀 Filter/Order ListView-Einträge

### ISSUE THREAD

**Issue by ReggaePanda** [demokratie-live/democracy-client#375]
### Sort:
im Standard-ListView nicht sichtbar – erreichbar übers Nach-Unten-Ziehen-der-Liste (Vorstufe von Reload)
pro "Liste" auswählbar – ist bedarfsgerechter 

__in Abstimmung__
1. nach Restzeit sortieren
3. nach Aktivitätsindex sortieren

__in Vorbereitung__
1. nach Aktualisierungsdatum (Procedure Change) sortieren (Neuste zuerst)
2. nach Vorgangserstellungsdatum sortieren (Neuste zuerst)
3. nach Aktivitätsindex sortieren

__Whats Hot__
1. nach Aktivitätsindex sortieren

### Filters
global über alle "Listen"
 
__Sachgebiet(e)__ (multiple)
1. Arbeit und Beschäftigung
2. Ausländerpolitik, Zuwanderung
3. Außenpolitik und internationale Beziehungen
4. Außenwirtschaft
5. Bildung und Erziehung
6. Bundestag
7. Energie
8. Entwicklungspolitik
9. Europapolitik und Europäische Union
10. Gesellschaftspolitik, soziale Gruppen
11. Gesundheit
12. Innere Sicherheit
13. Kultur
14. Landwirtschaft und Ernährung
15. Medien, Kommunikation und Informationstechnik
16. Neue Bundesländer
17. Öffentliche Finanzen, Steuern und Abgaben
18. Politisches Leben, Parteien
19. Raumordnung, Bau- und Wohnungswesen
20. Recht
21. Soziale Sicherung
22. Sport, Freizeit und Tourismus
23. Staat und Verwaltung
24. Umwelt
25. Verkehr
26. Verteidigung
27. Wirtschaft
28. Wissenschaft, Forschung und Technologie

__Vorgangstyp__ (radio)
1. Gesetz
2. Antrag

__Aktivität__ (radio)
1. Aktualisierungen
2. Nicht Abgestimmt

__Beratungszustand__
1. 
2. 
3. 

<img width="803" alt="bildschirmfoto 2018-06-13 um 14 06 55" src="https://user-images.githubusercontent.com/32302889/41350620-109aef02-6f14-11e8-84ce-9e2f97db42bd.png">

#### Times:
- Dev: 1w
- Design/Orga: 2d

**Comment by visionmakery** [comment]
Ui ist in Zeplin;)

**Comment by visionmakery** [comment]
Aktualisierung liegt bei Zeplin
