### ISSUE TITLE
🚀 Ergebnisdarstellung

### ISSUE THREAD

**Issue by ReggaePanda** [demokratie-live/democracy-client#377]
- Fraktionsergebnisse
- Nicht-/-namentliche-Abstimmungen different (Zahlendiskrepanz)
- PDF-Text bei nicht namentlichen Abstimmungen
- Scroll Indikatoren anzeigen

**Konzept**
![11061802](https://user-images.githubusercontent.com/32302889/41241149-8c979b10-6d9c-11e8-9b70-41fc6123eec9.JPG)
<img width="818" alt="bildschirmfoto 2018-06-14 um 21 13 17" src="https://user-images.githubusercontent.com/32302889/41455918-273e3a2c-707f-11e8-9a8b-f77f12428756.png">

bei namentlichen Abstimmungen
1. PieChart mit absoluten Zahlen
2. BarChart mit absoluten Zahlen je Fraktion
3. Fraktionsverteilungen auf Ja/Nein/Enthaltung (ohne nicht abg.) 
4. hier keinen Text oder ggfs. vertikal scrollbare Liste aller Abgeordneten mit Vorname, Name (Fraktion): Ja/Nein/Enthaltung/nicht abg., später mit Wahlkreis-Abo den eigenen Abgeordneten

bei nicht-namentlichen Abstimmungen
1. PieChart mit %-Zahlen
2. BarChart mit Farbe je Fraktion
3. Fraktionsverteilungen auf Ja/Nein/Enthaltung (ohne nicht abg.)
4. genauen Ergebnistext gemäß Plenarprotokoll

#### Times:
- Dev: 3d

resolves #271 
resolves #351

**Comment by visionmakery** [comment]
UI ist in Zeplin
