### ISSUE TITLE
🗣 Communityergebnis Anonymität gewährleisten

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#411]
Das Communityergebnis sollte Anonymität gewährleisten.

Beispielkonzept wäre eine Anzeige erst bei:
min. 10 Abstimmenden wobei mindestens eine stimme different sein muss

**Comment by visionmakery** [comment]
Anonymität besteht sobald 2 Personen abgestimmt haben, die nicht die gleiche Abstimmungsrichtung haben. Ich schließe das Ticket!
