### ISSUE TITLE
🗣 Install/test without Google Account

### ISSUE THREAD

**Issue by hansWURSCHT10000** [demokratie-live/democracy-client#414]
Can we download the beta APK from somewhere else like Github releases or F-Droid? 
I could not find anything like that.
That would be great for people who don't want to use a Google account or don't have Play Services installed.
I also tried to compile the app like descriped in the Readme but I was not successful.
Master builded successful but it only showed a white screen when opening and alpha didn't even build.

**Comment by ulfgebhardt** [comment]
Hey @hansWURSCHT10000 ,
we plan to do this at some point - but currently in the closed Beta this will not be the case!

Regarding building the App:

You need to set alot of environment varibales in the .env.debug file and need a Server running to get the coresponding laws displayed.
If you need help setting this thing up we will gladly assist you: Contact us @ https://discord.gg/Pdu3ZEV

**Comment by davidak** [comment]
@ReggaePanda Why was this closed?

**Comment by ReggaePanda** [comment]
Hey @davidak , we clean up our issues and with the topic we have multiple times.
https://github.com/demokratie-live/democracy-client/issues/469

we still in progress to add an apk to fdroid :)
