### ISSUE TITLE
💬 Wenn Abstimmung "Vergangen", Ergebnisse 

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#420]
Wenn eine Abstimmung bereits den Status "Vergangen" hat, sollte man nicht mehr abstimmen können, sondern das tatsächliche Ergebnis mitgeteilt bekommen.

**Comment by muessjoeh** [comment]
Wenn man es so betrachtet, dass die Stimmung der Community und die eigenen Präferenzen unabhängig vom parlamentarischen Ergebnis aufgezeichnet werden sollen, ist das im Prinzip nachvollziehbar. Dennoch sollten meiner Meinung nach bereits gelaufene Abstimmungen irgendwie gekennzeichnet werden und deren Abstimmungsergebnis im Parlament angezeigt werden.

**Comment by muessjoeh** [comment]
Ich glaube, dass wir verschiedene Sichtweisen auf diese App haben: Einerseits die Dokumentation der eigenen Meinungen, andererseits die Darstellung der parlamentarischen Fakten.

**Comment by muessjoeh** [comment]
Ich finde, wenn die Parlamentarier bereits abgestimmt haben, sollte dieses Abstimmungsergebnis irgendwie zugänglich sein. Eventuell durch ein kleineres Schaubild als das der Community oder als Link.

**Comment by ReggaePanda** [comment]
Todo: Bundestagsergebnisse anzeigen sobald die Abstimmung Vergangen ist

**Comment by ulfgebhardt** [comment]
Als neues Issue definiert: https://github.com/demokratie-live/democracy-client/issues/594
