### ISSUE TITLE
Abstimmung vorbei, aber nicht "Vergangen"

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#421]
Manchmal ist es so, dass eine Abstimmung zwar schon gelaufen ist und das Enddatum korrekterweise in Rot dargestellt wird, sie wird aber nicht in der Teilliste der Abstimmungen mit dem Status "Vergangen" aufgelistet. Bei mir war das heute bei der "Operation Olivenzweig" der Fall.

**Comment by ReggaePanda** [comment]
@muessjoeh danke dir für deinen Hinweis.
In der Alpha haben wir es bereits gefixt. Wir testen diese nächste Woche noch ausführlich und wenn alles in gut geht, dann kommt übernächste Woche die Beta, bei welcher dieser Fehler behoben sein sollte.

**Comment by ulfgebhardt** [comment]
@muessjoeh 
Wir suchen noch Alpha-Tester!
Wenn du Interesse hast die neueste Version der App bereits im Vorhinein auf Fehler zu untersuchen, bewerbe dich doch als Alpha-Tester unter contact@democracy-deutschland.de
Du bekommst dann die neuste Version der App ~1 Woche vorher und kannst dort nach belieben ausprobieren, da die Daten der Alpha getrennt von der Beta gehalten werden.
