### ISSUE TITLE
Whats-Hot und Abstimmung nicht in sync

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#435]
**Description:**

Es erscheint so als wären nicht alle Prozeduren in Abstimmung, die in Whats-Hot mit "Beschlussempfehlung liegt vor" markiert sind - überprüfen!

**App-Version:** [7.10,7.11,8.0]

**Comment by ReggaePanda** [comment]
@ulfgebhardt könntest du bitte entsprechende id's und Titel mit im issue aufführen

**Comment by ulfgebhardt** [comment]
Speziell: Keine Rekrutierung Minderjähriger in die Bundeswehr 232647

Erscheint nicht in Abstimmung

**Comment by ReggaePanda** [comment]
ist ein Fehler beim verarbeiten der vergangen Daten aus dem Agenda-scraper.
Da müssen wir wohl die Logik nochmal überarbeiten.

derzeit ist es folgende:
Stand: Überwiesen
und dokumentennummer in den Tagesordnungspunkten
