### ISSUE TITLE
[Feature] Tagesordnungspunkte Scrapen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#437]
Die Tagesordnungspunkte des Bundestages scrapen.

![image](https://user-images.githubusercontent.com/1238238/37977181-9008090a-31e3-11e8-89e1-5af665e92831.png)

Gewünscht:
- nodejs
- Ressourcenschonend - das aufbauen ganzer Browserinstanzen ist nicht gewünscht.

Optimaler Startpunkt
- [hier](http://www.bundestag.de/tagesordnung)
- Die Daten können direkt ohne JS-Nachlade-Firlefanz über eine solche URL abgerufen werden [Beispiel](https://www.bundestag.de/apps/plenar/plenar/conferenceweekDetail.form?year=2018&week=8&limit=10)

Das Scraping darf gerne Teil von [Dip21-Scraper](https://github.com/demokratie-live/dip21-scraper) werden.

Scrape-Technologie Vorschlag:
- [NodeJS Request](https://github.com/demokratie-live/dip21-scraper/blob/master/src/DipBrowser.js)
- [Beispiel-Scraper](https://github.com/demokratie-live/dip21-scraper/blob/master/src/scraper.js) für das Dip21
- [Datenausgabe](https://github.com/demokratie-live/dip21-scraper/blob/master/src/scraper.js#L27) unabhängig von Art der Speicherung [[1]](https://github.com/demokratie-live/dip21-scraper/blob/master/src/cli.js#L119) [[2]](https://github.com/demokratie-live/bundestag.io/blob/master/src/importJob.js#L42)

Wir stehen für Rücksprache bereit:
- [Discord](https://discord.gg/Pdu3ZEV)
- [EMail](mailto:contact@democracy-deutschland.de)

Rev: https://github.com/demokratie-live/bundestag.io/issues/17

**Comment by ReggaePanda** [comment]
https://github.com/demokratie-live/bt-agenda
