### ISSUE TITLE
🗣 Angabe des Zeitraums bis zur parlamentarischen Abstimmung 

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#452]
Wenn man sich eine Liste der anstehenden Beschlüsse ansieht, stößt man auf Formulierungen wie "4 Tage", die beim ersten Mal völlig unverständlich sind. Meiner Meinung nach wären Formulierungen wie "in 4 Tagen" oder "Abstimmung in 4 Tagen" besser.

**Comment by ReggaePanda** [comment]
@muessjoeh da hast du vollkommen recht, leider gibt es an dieser position Platzprobleme. Ein Umbruch würde nicht gut aussehen. Daher müssen wir das wohl mit einem In-App Tutorial Hinweis beschreiben.

**Comment by visionmakery** [comment]
Weiteres Feedback eines Testers: 
"Hallo,

ich fände es toll, wenn ein Klick auf die grüne Zahl (die roter Kasten im Screenshot) eine kurze Erläuterung in einem Fenster aufgehen würde."
![image1](https://user-images.githubusercontent.com/32302889/42178688-aa08a1b2-7e31-11e8-825d-1d78fbe581d4.jpg)

**Comment by ReggaePanda** [comment]
auf detail "in 4 Tage"

**Comment by ulfgebhardt** [comment]
Closed in Favor of https://github.com/demokratie-live/democracy-client/issues/582
