### ISSUE TITLE
🐛 Grafische Anzeige falsche Größe 

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#453]
Wenn man in einen einzelnen Punkt das Handy quer hält und eine Abstimmung vornimmt und dann das Handy in das Hochformat dreht, wird die Grafik des Community-Ergebnisses zu groß ausgeben.

**Comment by ulfgebhardt** [comment]
Hey @muessjoeh 
Beschriebt dieses Issue dein Problem?
https://github.com/demokratie-live/democracy-client/issues/355

**Comment by muessjoeh** [comment]
Ja.
