### ISSUE TITLE
💬 Abstimmung streckenweise nicht möglich 

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#455]
Bei manchen Punkten kann man nicht abstimmen, zum Beispiel bei "Export von Rüstungsgütern verbieten". Dennoch trägt dieser Punkt den Wert 56. Ich dachte, dass es sich dabei um die Anzahl der abgegeben Stimmen handelt, aber das kann nicht sein.

**Comment by sign2k** [comment]
Soweit ich das verstehe, ist der Antrag noch in Vorbereitung. Hier kann daher noch nicht abgestimmt werden. Mann kann über den Pfeil,der über der Zahl 56 ist, die Zahl einmalig erhöhen. Dies entscheidet wie "Hot" der Antrag ist 😄

**Comment by muessjoeh** [comment]
Ich dachte, die persönliche Abstimmung sei auch dazu gut, die eigenen Ansichten für einen Wahlomat zu dokumentieren. Das sollte dann aber unabhängig vom Status sein.

**Comment by visionmakery** [comment]
Hallo lieber @muessjoeh, so wie es @sign2k beschrieben hat, sieht es unser Konzept vor. 
Natürlich ist die persönliche Abstimmung dazu gut, die eigenen Ansichten für das Wahl-O-Meter zu dokumentieren, aber wir haben ja auch noch einen parlamentarischen Prozess und wir wollen, dass dem Abstimmenden möglichst viele Informationen zur Verfügung stehen (z.B. die Beschlussempfehlung) bevor er abstimmt. Das später hinzukommende Forum, indem Weiterführendes (Links, Argumente, Videos) gesammelt wird, spricht auch dafür, die Abstimmung erst ab einem bestimmten Zeitpunkt zu öffnen – aus gleichen Gründen wie oben.

LG

**Comment by muessjoeh** [comment]
Vielleicht muss ich mich dann erst mal wegen der genauen Intention und den Features dieser App informieren. Wo kann ich das am besten machen?

**Comment by visionmakery** [comment]
Hallo lieber @muessjoeh,
Unter https://www.democracy-deutschland.de/#!citizen kannst du einsehen, was Du mit DEMOCRACY alles machen kannst. LG

**Comment by muessjoeh** [comment]
Auf dieser Seite sind verschiedene Dinge erwähnt, die bei meiner Installation der App nicht möglich sind bzw deren Bedienung ich nicht gefunden habe. Zum Beispiel das Feedback (außer Abstimmungen) oder zusätzliche Informationen. Für ein paar Sekunden Bedenkzeit (ich bin ja kein professioneller Bundestagsabgeordneter) sind etliche Anträge vermutlich zu komplex.
Außerdem konnte ich nicht einzelnen Anträgen durch den Pfeil größeres Gewicht geben, vermutlich geht es hier um Bruchteile von Millimetern.

**Comment by ReggaePanda** [comment]
werden dort diese Interaktionen anbieten
https://github.com/demokratie-live/democracy-client/issues/575
