### ISSUE TITLE
🛠 [Server] Bundestag io aufsplitten

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#460]
BundestagIo sollte etwas aufgesplittert werden.

Derzeit ist die API, Scraper und Admin interface in einem Packet, diese sollten jeweils in ein eigenes paket.

**Comment by ulfgebhardt** [comment]
Immer noch aktuell?

**Comment by ReggaePanda** [comment]
ja

**Comment by ulfgebhardt** [comment]
Bundestag.io sollte zu einem Repo werden, aber von DEMOCRACY getrennt werden
