### ISSUE TITLE
🛠 [Docu] Maintainer Images in Readme

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#466]
**Description:**

Display Maintainer-Images like its done here
https://github.com/oblador/react-native-keychain/blob/master/README.md

**Comment by Guzzler** [comment]
Hey i would like to pick this up. Will Raise a PR soon. Would it be possible to get the pictures?

**Comment by Guzzler** [comment]
Ich habe das Notwendige getan und eine lokale Niederlassung erstellt, aber selbst einer lokalen Niederlassung fehlt die Push-Berechtigung. Bitte lassen Sie mich wissen, wie ich vorgehen darf.
