### ISSUE TITLE
🐛 [Burger Menu] Navigating to a Sub-Page from the Burgermenu will prevent navigating to it again

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#467]
**Description:**

If you use the Burgermenu to navigate to e.g. Support and you navigate back with the Android Back Button, you can not open the Support page anymore unless you do another navigation

**Steps to reproduce:**
- 1. Navigate to Support
- 2. Press Back
- 3. Navigate to Support again, do not do any other navigation
- 4. ...
- 5. Profit

**App-Version:** [0.8.0]

**Comment by ManAnRuck** [comment]
neue nav lib macht dies obsolet 🎬
