### ISSUE TITLE
📥 🗣 Provide the app via Fdroid?

### ISSUE THREAD

**Issue by fapsi** [demokratie-live/democracy-client#469]
Hey,
are there any plans to provide your App via Fdroid after the beta? (Since I have no G-Playstore I'd have to build it on my own, which is a bit annyoing; Is it currently possible to participate without an googleid in the beta phase?)
Here are their (Fdroid) guidelines (https://f-droid.org/de/docs/Inclusion_Policy/).
Thanks in advance

**Comment by fapsi** [comment]
Refer also #414 . Let me know if I can help with this.

**Comment by ulfgebhardt** [comment]
Yes you can help @fapsi, we are about to launch the app - one of the next Steps is to provide it for those without Google account t.

We use Travis and fastlane to deploy the app.

Is there an API and a script to upload binaries, pictures and alike to fdroid?

<3 Ulf

**Comment by fapsi** [comment]
Ich schreibe mal auf Deutsch, fällt mir leichter. Soweit ich es verstanden habe, bräuchten wir ein build-recipe sowie einige app-metadaten, welche in das fdroid-repo aufgenommen werden müssten. Die Android-App (IOS wird von FDroid nicht unterstützt) wird dann aus den Github-Sources gebaut und je nach gewählter Aktualisierungsmethode aktualisiert. Da die Entwickler von FDroid aktuell wohl viel um die Ohren haben wäre es sinnvoll, selbst einen Merge-Request zu schreiben. 

Relevant sind glaube ich folgende Artikel:
- Erfahrungsbericht/Kurzanleitung: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/
- App-Metadaten: https://f-droid.org/en/docs/Build_Metadata_Reference/ 
  - Mögliche Aktualisierungsmethoden: https://f-droid.org/en/docs/Build_Metadata_Reference/#Update-Check-Mode
- Antragseinreichung und Anforderungen: https://f-droid.org/en/docs/Inclusion_How-To/

Um voran zu kommen, könnten wahrscheinlich an verschiedenen Fronten gearbeitet werden:

1. Bestimmung einer der o.g. Aktualisierungsmethode (mir scheint das Arbeiten mit Tags intuitiv sinnvoll, aber das hängt von euren Präferenzen ab; Eventuell müsste dabei trotzdem in build.gradle die Version explizit auftauchen, aber da bin ich noch nicht sicher -> wäre natürlich unschön bezüglich eurer aktuellen Lösung mit den Umgebungsvariablen) 
2. Erstellung des build-recipe. (Leider habe ich eure App noch nicht selber bauen können, ist aber auch eine Weile her, dass ich es probiert habe; vllt. könntest du bezüglich des Bauens der Android-Apk ein paar Tips geben. Werde mich die Tage aber auch nochmal dran versuchen.)
3. Überprüfung der Anforderungen für den Review-Prozess, um möglichen Problemen vorzubeugen

Bezüglich des build-recipe könnte es schneller gehen, wenn wir uns an einer vorhandenen App, welche ähnliche Build-Mechanismen verwendet orientieren. Beispiele anderer Apps: (Riot: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.vector.alpha.txt (siehe insb. das kompliziertere Rezept in neuster Version); Conversations: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/eu.siacs.conversations.txt ) 

(Nur zur Info: Einen temporären Workaround könnte die Bereitstellung der .apk auf eurer Website darstellen. Nichtsdestotroz wäre bezüglich der Verbreitung der App das Publikum bei FDroid für euch interessant.)

**Comment by fapsi** [comment]
Ich sehe gerade, dass fastlane auf dem debian buildserver von fdroid leider nicht trivial wird, zudem existiert noch keine Vorlage im FDroid-Repo.
https://github.com/fastlane/fastlane/issues/11579
https://github.com/fastlane/fastlane/issues/11687

**Comment by fapsi** [comment]
Ich sehe gerade, dass fastlane auf dem debian buildserver von fdroid leider nicht trivial wird, zudem existiert noch keine Vorlage im FDroid-Repo.
[Versuch](https://github.com/fastlane/fastlane/issues/11579)
[Linux Support](https://github.com/fastlane/fastlane/issues/11687)
Wahrscheinlich wäre es sinnvoller direkt über gradle zu bauen..

**Comment by ulfgebhardt** [comment]
PR: https://gitlab.com/fdroid/fdroiddata/merge_requests/3799
Issue: https://gitlab.com/fdroid/rfp/issues/743

**Comment by ulfgebhardt** [comment]
@Grammost @davidak @ialokim @fapsi 
Mögt ihr ein wenig Druck auf die FDroid-Store verantwortlichen ausüben - jemand hat uns einen PR gemacht, aber er ist nach wie vor nicht durchgemerged <3

**Comment by davidak** [comment]
Nicht sicher ob das angebracht ist. Sie tun sicher was sie können. Aber einmal nach dem Status fragen wird OK sein.

**Comment by ulfgebhardt** [comment]
Closed as of:
- https://f-droid.org/de/packages/de.democracydeutschland.app/
- https://gitlab.com/fdroid/fdroiddata/merge_requests/3799
