### ISSUE TITLE
🐛 Winston Discord Logger - Remove Duplicated Content

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#506]
## 🐛 Bugreport

![image](https://user-images.githubusercontent.com/1238238/44140273-dd41fde8-a079-11e8-8c08-67183082d335.png)

Remove duplicated Field, add server which throws the log.

**Comment by ManAnRuck** [comment]
und winston nochmal aufräumen
local log einstellen, log monitoring etc.
