### ISSUE TITLE
Zahlen und Grafik passen nicht zueinander 

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#530]
Bei einem Ergebnis einer Abstimmung passen die absoluten Zahlen nicht zur Grafik. Ich habe zwar einen Screenshot, aber wie bindet man diesen ein?

**Comment by ulfgebhardt** [comment]
Screenshots kannst du einfach in das Textfeld schieben hier auf GIthub - das Bild wird dann automatisch hochgeladen @muessjoeh

**Comment by ReggaePanda** [comment]
@muessjoeh alternativ würde uns auch die Vorgangs id (bei details) helfen.

Wir haben händisch viele werte angepasst, dabei kann es zu Fehlern gekommen sein.

**Comment by muessjoeh** [comment]
Wie macht man das Einbinden von Screenshots denn in Android?
Bei welcher Abstimmung das genau war, weiß ich leider nicht mehr.

**Comment by ulfgebhardt** [comment]
@muessjoeh Auf dem Handy kann man Screenshots nicht hochladen (glaube ich) bei Github
Schick einfach eine EMail mit dem Screenshot > contact@democracy-deutschland.de

**Comment by ReggaePanda** [comment]
@muessjoeh anhand des Bildes, kann ich leider nicht bestätigen, dass dort etwas mit den Zahlen falsch ist. 

Da es eine "nicht namentliche Abstimmung" ist, beziehen sich die Zahlen auf die Fraktionen. 
Im pieChart werden die werte je nach Fraktionsstärke ausgegeben. Es ist in der Tat etwas verwirrend, wenn jedoch alleine die Union und SPD für ein Gesetz stimmen und alle anderen dagegen, gibt es 2 Zustimmungen und 4 Ablehnungen, jedoch ist dann dennoch die Zustimmung größer trotz kleinerer zahl an zustimmenden Fraktionen.

**Comment by muessjoeh** [comment]
Da es verwirrend ist, dass sich die absoluten Zahlen auf Fraktionen und die Prozentzahlen auf Personen beziehen, sollte man es anders beschriften.

**Comment by ulfgebhardt** [comment]
Vorschlag:
"6 Fraktionen nach Stärke"

**Comment by muessjoeh** [comment]
Wie wäre es denn mit "3 Fraktionen Zustimmung" bzw Ablehnung in der Beschriftung und "69%/31% der Abgeordneten" in der Grafik?

**Comment by ReggaePanda** [comment]
Wenn man zum BarChart swiped, sollte das Verhältnis der Fraktionen zum Ergebnis klar werden.

<img width="549" alt="bildschirmfoto 2018-10-16 um 11 15 25" src="https://user-images.githubusercontent.com/2183135/47005786-ce08fc00-d134-11e8-833b-391fb0ffdb12.png">
