### ISSUE TITLE
Sortieren nach Erstellungsdatum 

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#531]
Die einzelnen Einträge können nach Restzeit und Aktivität sortiert werden. Es würde die Suche nach neuen Einträgen stark vereinfachen, wenn man auch nach dem Erstellungsdatum sortieren könnte.

**Comment by muessjoeh** [comment]
Wenn beim Filtern nach "Abstimmungen" die eigenen gemeint sind, existiert zumindest ein Workaround.

**Comment by ReggaePanda** [comment]
Wenn das Ziel ist, nicht abgestimmte Abstimmungen zu finden, ist in der Tat der Filter die beste Lösung. :)

**Comment by muessjoeh** [comment]
Okay, dann kann man das glaube ich als Duplikat markieren.

**Comment by ulfgebhardt** [comment]
Todo:
- Filterbezeichnungen verbessern
- Über neue Filter nachdenken für die nächste Iteration
