### ISSUE TITLE
Übernahme der Daten aus Beta

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#551]
Ich habe gerade im Play Store die App heruntergeladen und dabei die Telefonnummer angegeben, so dass eine eindeutige Zuordnung der Accounts besteht. Dennoch wurden Anträge, über die ich bereits abgestimmt habe, jungfräulich dargestellt.

**Comment by ReggaePanda** [comment]
Hi @muessjoeh wir wollten für die production version einen sauberen start, da es evtl. auch Leute gibt, die in der Beta nur getestet haben und nicht so abgestimmt haben, wie sie es wirklich wollten.
Des weiteren haben wir in der Beta keine Telefonverifizierung, wodurch zur production diese Verbindung nicht besteht.

**Comment by muessjoeh** [comment]
Die Verbindung besteht zwar nicht auf dem Server, aber auf den Clients (also den Telefonen). Insofern wäre es im Prinzip möglich, wenn dies vorgesehen ist, die Daten zu übertragen.
Wenn dieser Vorgang manuell angeworfen wird, kann man dann auch davon ausgehen, dass es gewünscht ist.

**Comment by ReggaePanda** [comment]
Wir werden in einer zukünftigen Version die Möglichkeit einbinden, dass wenn man die Handynummer wechselt die Stimmen übertragen kann. Die Übertragung aus der Beta werden wir jetzt nicht mehr nachträglich einbinden.
