### ISSUE TITLE
 🐛 App does not exit Loadingscreen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#564]
## 🐛 Bugreport

![image](https://user-images.githubusercontent.com/1238238/46263435-700ece80-c50f-11e8-841d-7ee1720d979e.png)

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by ReggaePanda** [comment]
<img width="466" alt="bildschirmfoto 2018-10-26 um 16 07 19" src="https://user-images.githubusercontent.com/2183135/47571929-06c98200-d93a-11e8-9233-e8416031a035.png">
on iOS

**Comment by ulfgebhardt** [comment]
Auf Android gibt es den "neverending loading indicator" beim updaten der Liste/Detailseite, wenn der Server nicht erreichbar ist

![image](https://user-images.githubusercontent.com/1238238/48075120-be844c80-e1e2-11e8-86a3-bdc17d733a03.png)

How to reproduce
-> stop-production.sh auf internal
-> neverending loading indicator

Bei Neuinstallation der App:
-> Die App verlässt den Loading Screen und zeigt das Tutorial
-> danach kommt man auf den Listscreen, welche dann leer bleibt und neverending loading indicator aufweist

**Comment by ManAnRuck** [comment]
mit neuer version obsolet 👌
