### ISSUE TITLE
🐛 Code order & Crash

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#565]
## 🐛 Bugreport

![image](https://user-images.githubusercontent.com/1238238/46278355-2f8e6f80-c566-11e8-8f2c-be87efaf81f5.png)

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by ReggaePanda** [comment]
No triage
