### ISSUE TITLE
📥 🐛 Legende hellgrau auf weiß

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#566]
## 🐛 Bugreport
An prototyping@ ist folgendes gerichtet worden:

Mich stört dass sie ganz kleine Schrift in hellgrau auf weissem Grund anbieten. Das fällt besonders bei den Tortendiagrammen auf in der Beschreibung der Farben. 
Da würde ich um Nachbesserung bitten. 

Mit freundlichen Grüßen
XXX

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by ReggaePanda** [comment]
farbe von Repräsentation übernehmen

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/47436888-b3272f00-d7a7-11e8-9395-1a9e568515ec.png)
![image](https://user-images.githubusercontent.com/1238238/47436895-b5898900-d7a7-11e8-9d3d-aea09e0b6c74.png)
