### ISSUE TITLE
📥 🗣 Bundestagsergebnisse immer in-App anzeigen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#594]
## 🗣 Suggestion

Bundestagsergebnisse sollten auch ohne Abstimmung in-App angezeigt werden, sofern die Abstimmung vorbei und Daten vorhanden sind.

**Comment by muessjoeh** [comment]
Wie kann eigentlich ein Ergebnis vorhanden sein, ohne dass vorher eine Abstimmung stattgefunden hat?

**Comment by ReggaePanda** [comment]
@muessjoeh Es geht bei dem Ticket darum, dass man als Person nicht selbst abgestimmt haben muss und dennoch die Abstimmungsergebnisse des Bundestages angezeigt werden.
Also der Bundestag muss schon vorher abgestimmt haben, damit wir da was anzeigen ;)

**Comment by muessjoeh** [comment]
Also wieder mal das verkehrte Auffassen des Wortes "Abstimmung". Nachdem das nicht zum ersten Mal passiert ist, sollte man sich denke ich über die Verwendung dieses Wortes Gedanken machen, zumal ja nicht nur eine einzige Entität Abstimmungsergebnisse generiert.

**Comment by ReggaePanda** [comment]
Wir versuchen zukünftig ein wenig mehr auf's wording zu achten 🙂
