### ISSUE TITLE
🌟 [EPIC] Vereinheitlichen alles Bundestags-Textblöcke

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#605]
## 🚀 Feature

Alle Texte des Bundestages sollten gebündelt werden. Hier ist darüber nachzudenken das ganze ggf in eine externe Library zu gießen, um die Wiederverwendbarkeit zu erhöhen insb. im Zusammenhang mit Bundestag.io .

Das betrifft im besonderen die Beratungszustände, unsere Definition der verschiedenen Listen, Typen der procedures, Sachgebiete, ...

Es ist ebenfalls notwendig den Inhalten eine Dokumentation über deren Bedeutung hinzuzufügen. Dies ist zweitrangig, kann aber als Dokumentation für Bundestag.io dienen.

https://github.com/demokratie-live/bundestag.io-definitions

**Comment by ManAnRuck** [comment]
Description:

Alot of checks use string definitions of currentStatus.

e.g. ... === "Abgestimmt"

All those defintions should be unified in the config, no string definitions what so ever should be used in the code - all must go into the config/constants section

https://github.com/demokratie-live/democracy-client/issues/398
