### ISSUE TITLE
🐛 Spenden aktualisieren sich nicht beim start der App sondern nur auf der Spendendetailseite

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#617]
## 🐛 Bugreport

Spenden aktualisieren sich nicht beim start der App sondern nur auf der Spendendetailseite.
Daher zeigt das Menü immer einen veralteten Spendenstand an.

Solution: Beim Start der App sollte der aktuelle Spendenstand einmalig abgerufen werden.

### App-Version & Environment

APP: [1.0.5]

OS:  [both]

### Report

> Sehr geehrtes Team,
> 
> seit ich die App benutze, steht dort der gleiche notwendige fehlende Betrag
> zur Finanzierung von 9949 Euro/Monat.
> Hat sich da wirklich noch nix getan oder ist das ein Bug?
> 
> Mit freundlichen Grüßen
> XXX

**Comment by visionmakery** [comment]
gilt das noch in der neuen Version, @ManAnRuck?

**Comment by ManAnRuck** [comment]
nein, daher schließe ich dieses ticket :)
