### ISSUE TITLE
🐛 Verifikationstutorial - Verifikation-Button nicht sichtbar

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#620]
## 🐛 Bugreport

Im Verifikationstutorial ist Verifikation-Button nicht sichtbar auf kleinen Geräten.
Siehe Screenshot

### App-Version & Environment

APP: [1.0.5]

OS:  [iPhone 5s iOS 12.0.1]

### Steps to reproduce

![image-1](https://user-images.githubusercontent.com/1238238/47915227-7bed0800-dea2-11e8-8465-eb8b1ee2ea80.jpg)

**Comment by visionmakery** [comment]
gelöst mit 1.3 durch Löschen dieses Screens!
