### ISSUE TITLE
🚀 FontSize/Schrift Größe/Farbe vereinheitlichen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#636]
### FontSize/Schrift Größe vereinheitlichen

Alle Schriftgrößen in der App sollten fest definiert und einheitlich sein.

**Comment by visionmakery** [comment]
"Ich möchte anregen, die Schriftart in der Democracy App entweder für die Nutzer selbst anpassbar zu machen, oder wenigstens die Schriftfarbe nicht grau zu gestalten.
Ich möchte das als älterer Mensch auch gerne lesen können, ohne mich dabei zu sehr abzumühen. 
Sie wissen doch sicherlich von den Grundsätzen eines inklusiven Design von Webanwendungen und Software. Da geht hellgrau gar nicht, weil dadurch Menschen mit altersbedingter Sehschwäche und auch andere Personen, die unter eingeschränkter Sehkraft leiden, von vornherein benachteiligt sind.
Ich finde die Initiative der Democracy App sehr gut und würde mich freuen, wenn der Text auch für mich etwas lesbarer gestaltet wäre."
