### ISSUE TITLE
🚀 Neue Listensymbole

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#637]
### 🚀 Neue Listensymbole
- [ ] Push
- [ ] Update
- [ ] Neu
- [ ] Aktivity-Symbol

**Comment by visionmakery** [comment]
als kleine Anmerkung allerdings: die Pfeile nach oben in jedem Listeneintrag der Gesetzte in Kombination mit der Teilnehmerzahl suggerieren mir Upvotes (Zustimmungen) und nehmen Einfluss auf die Abstimmung.

Bei Kommentaren in Google, Amazon oder stackoverflow bedeutet ein Pfeil nach oben mit der Zahl 7, dass die Upvotes um 7 überwiegen. Die Zahl -4 oder auch 4 mit einem Pfeil nach unten bedeutet, dass die Downvotes um 4 in der Mehrzahl sind.

Ich würde den Pfeil einfach rausnehmen oder zumindest bei einer UX Testessen Session schauen, ob es weiteren Usern auch so ergeht wie mir.

Liebe Grüße,
Fabian Schimke
