### ISSUE TITLE
🚀 [Feature]📱WOM: Bestenliste 

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#644]
### Bestenliste 

Politiker-Bestenliste berechnen für den Nutzer
- [ ] favorisierbare Politiker
- [ ] WK-Politiker

**Comment by visionmakery** [comment]
Weitere Ideen zum WOM:

Auch das neue Wahl-O-Meter Feature ist super. Das macht das Abstimmen nochmal nützlicher und gibt ein gutes Gefühl, wie die Parteien abstimmen. Das Ergebnis ist wie ich es erwartet habe, von daher würde ich sagen, es funktioniert.

Vielleicht könnte es ein Ziel sein, mit möglichst wenig Abstimmungen ein möglichst detailiertes Wahl-O-Meter zu bekommen. Ich könnte mir vorstellen, dass eine Liste mit "kontroverser Abstimmungen" da hilfreich ist. Also solche, bei der sich die BENUTZER uneinig sind. Das sollte dann deutlich machen, auf welcher Seite ich stehe.

Beim Screen nach einer Abstimmung mit dem Wahl-O-Meter wäre es nett zu sehen, wie es sich durch die letzte Abstimmung verändert hat. Also in grün +1 oder rot -1 bei den Fraktionen.

Ich hab auch gemerkt, dass es nicht immer leicht ist eine gute Wahl zu treffen, ohne sich intensiv mit jedem Thema zu befassen. Zum Beispiel bei dem Thema "Angriffe mit Messer sollen in Polizeistatistik kommen". Hab ich gedacht "Ja, warum nicht." Dann hab ich gesehen, der Antrag ist von der AfD und alle anderen Parteien sind dagegen. Also hab ich dagegen gestimmt. Dann hab ich aber gesehen, dass 80% der Benutzer dafür sind. Das sind sicher nicht alle AfD Wähler. Also spricht vielleicht doch nichts dagegen das zu machen, außer dass man nicht zugeben möchte, dass die AfD auch mal gute Ideen hat? Man könnte natürlich bewerten, dass es nicht notwendig ist und der AfD nur für rassistische Schlussfolgerungen nützt.

Ich hab gesehen, dass es in meinem Wahlkreis einen anderen Nutzer gibt. Vielleicht wäre es nett mit ihm in Kontakt treten zu können? Das könnte erstmal anonym über die App laufen und man könnte wenn gewünscht per nachricht Kontaktdaten austauschen. Wenn kein Name angezeigt wird müsste eventuell ein generiertes Benutzerbild angezeigt werden, damit man Nutzer außeinander halten kann.
Liebe Grüße
David

**Comment by visionmakery** [comment]
duplicate #953
