### ISSUE TITLE
🚀 [Push Nachricht] Ergebnis vorhanden, Bulk Push Ergebnis

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#662]
### [Push Nachricht] Ergebnis vorhanden, Bulk Push Ergebnis
- [ ] PushUpdate (Glocke): 'Ergebnis:' vorhanden 
- [ ] Bulk Push Ergebnis
- [ ] Benachrichtigungseinstellungen Benachrichtigungen über neue Ergebnisse
- [ ] (Nutzer wählt Zeitpunkt)

### Design & Layout

@visionmakery Genauer Text

**Comment by visionmakery** [comment]
'Bundestagsergebnis: Gesetz zur XYZ...' @ulfgebhardt @ReggaePanda

**Comment by visionmakery** [comment]
<img width="340" alt="Bildschirmfoto 2019-03-19 um 11 56 06" src="https://user-images.githubusercontent.com/32302889/54600889-0d1ddf00-4a3e-11e9-829f-df476989c64d.png">
