### ISSUE TITLE
🗣 [Piechart] [Namentliche Abstimmung] "Nicht Abg." nicht verständlich

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#663]
### [Piechart] [Namentliche Abstimmung] "Nicht Abg." nicht verständlich

"Nicht Abg." ist nicht verständlich
-> Ausschreiben
-> oder "Nicht Abgge."

![image](https://user-images.githubusercontent.com/1238238/48138817-67937b80-e2a5-11e8-82c3-85a1c11c7e2f.png)

**Comment by visionmakery** [comment]
In 1.3 via "Abwesend" gelöst
