### ISSUE TITLE
🗣 [Website] App ist kostenlos Hinweis

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#664]
### [Website] App ist kostenlos Hinweis
DEMOCRACY+ suggeriert Kostenpflichtigkeit

Erste Lösung in der Roadmap den Hinweis "Alle Produkte sind kostenlos" hinzufügen
@visionmakery genaues wording

**Comment by visionmakery** [comment]
‘Unsere Entwicklung ist Open Source, der Quellcode frei und offen
DEMOCRACY ist und bleibt kostenlos'

@ulfgebhardt
