### ISSUE TITLE
🐛 [Bundestag.io] Gesta Ordnungsnummer sehr oft leer

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#665]
### [Bundestag.io] Gesta Ordnungsnummer sehr oft leer

Die Gesta Ordnungsnummer ist oft null -> untersuchen ob ein Fehler vorliegt

**Comment by ManAnRuck** [comment]
@ulfgebhardt welche Gesta-Ordnungsnummer?
