### ISSUE TITLE
🗣 Teilen nach Abstimmung prominent machen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#670]
## 🗣 Suggestion

Der Nutzer sollte nach seiner Abstimmung darauf hingewiesen werden, dass er das Gesetz teilen kann.
Er hat sich nun mit dem Vorgang beschäftigt und eine Meinung dazu. Er ist nun bereit seinem Nachbarn/Kollegen etc davon zu erzählen, insbesondere, wenn er eine Erkenntnis in dem Prozess der Auseinandersetzung mit dem Vorgang hatte.

@visionmakery Wie kann das passieren, nachdem der Nutzer abgestimmt hat?

**Comment by visionmakery** [comment]
gelöst mit Interaktionsbuttons nach der Abstimmung ab Version 1.2.2
