### ISSUE TITLE
🐛 [Push Nachrichten] Öffnen Gesetz nicht, Kategorie in Push

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#676]
### [Push Nachrichten] Öffnen Gesetz nicht, Kategorie in Push
1.) Push-Nachrichten A

Wenn bei den Push-Nachrichten als Erstes die Katagorie stehen könnte, also Abstimmung/Vorbereitung/What's hot. Dann kann man sofort entscheiden, die App zu öffnen oder nicht. Bislang ärgert mich das immer, weilch ich beispielsweise denke, es handele sich um ein Gesetz, öffne dann die App und sehe, daß es "nur" um eine Vorbereitung geht.

2.) Push-Nachrichten B

Was mich noch viel mehr ärgert als das obige Verhalten, ist das Verhalten der App beim Öffnen, wenn ich denn eine Push-Nachricht antippe. Anstatt nun direkt an den Ort des Geschehens zu springen (wie ich es eigentlich erwarten würde), zeigt die App immer nur die Standard-Übersicht und ich muß mich mühsam durch die Kategorien hangeln, bis ich - vielleicht - den Vorgang gefunden habe, den die Push-Nachricht angezeigt hat. Oft gebe ich dann das Suchen einfach auch auf, weil es mir einfach zu lange dauert und zu mühsam ist. Wenn sich dieses Verhalten der App ändern ließe = 1 mit Sternchen!!!  :-))

---

Zur Zeit ist es so, daß unabhängig von der Anzahl der angezeigten Pushnachrichten jedes Mal dann, wenn man eine der Pushnachrichten antippt und daraufhin die App startet, anschließend alle anderen zuvor mitangezeigten Pushnachrichten nicht mehr als Pushnachricht angezeigt werden.

Könnte man das möglicherweise dahingehend ändern, daß nach dem Antippen EINER Pushnachricht die anderen Pushnachrichten anschließend auch weiterhin als Pushnachrichten bestehen bleiben?

Dann könnte man alle Pushnachrichten nach und nach abarbeiten, je nach Gusto.

Derzeit weiß man man nach dem Öffnen einer ausgewählten Pushnachricht ja leider gar nicht mehr, woraufhin in den anderen Pushnachrichten hingewiesen wird, da sie nicht mehr angezeigt werden.

### App-Version & Environment

APP: []

OS:  [Galaxy Tab A mit Android 7.1.1]

**Comment by ManAnRuck** [comment]
durch neues pushkonzept obsolet 🧹
