### ISSUE TITLE
🗣 Einzelpunkte von Anträgen abstimmbar machen, nicht nur gesamten Antrag

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#677]
## 🗣 Suggestion

Bei manchen Anträgen kann Einzelpunkten der Beschlussvorschläge zugestimmt werden.

Also:
- a und b JA 
- Rest NEIN
 
Das ist ziemlich wichtig für die Abstimmung. Kann eine differenzierte Abstimmungsart perspektivisch kommen?

**Comment by visionmakery** [comment]
Hier ist es zu einem Missverständnis gekommen. Eine Beschlussempfehlung kann mehrere Vorgänge, z.B. Anträge enthalten. Im Bundestagsplenum wird dann meist über die Beschlussempfehlung abgestimmt und es heißt "unter Punkt b) empfiehlt der". Ein einzelner Vorgang kann aber nicht in Einzelpunkten abgestimmt werden!
