### ISSUE TITLE
📥 🐛 Datenschutzrichtlinie enthält Google Analytics

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#687]
### Datenschutzrichtlinie enthält Google Analytics

Die Datenschutzrichtlinie enthält einen Referenz auf Google Analytics. Dieses wird allerdings nicht mehr in Verwendet. Weder auf der Website noch in der App.

Betrifft auch F-Droid.

### App-Version & Environment

APP: [latest]

OS:  [both]

### Steps to reproduce
![screenshot_20181211-232117](https://user-images.githubusercontent.com/1238238/50226771-5eb5bf80-03a4-11e9-8ca9-6c6f0db702fd.png)

**Comment by Echolon** [comment]
Ja, war gerade kurz davor zu fragen warum Google Analytics jetzt genutzt werden muss
