### ISSUE TITLE
🐛 Fehler bei der Nummerbestätigung

### ISSUE THREAD

**Issue by PerhapsSomeone** [demokratie-live/democracy-client#690]
Zum Bestätigen eines Accounts wird eine deutsche Nummer gefordert, allerdings wird eine Nummer mit dem Format
173XXXXXX nicht angenommen, der Knopf bleibt ausgegraut.
0173XXXXXX hingegen lässt den Knopf farbig werden, endet aber mit einem weiteren Fehler, welcher besagt das 0049 hinzugefügt werden soll.
Das würde aber nicht funktionieren.

**Comment by ulfgebhardt** [comment]
@PerhapsSomeone Gehe ich richtig in der Annahme, dass deine Nummer 9 Stellen + Vorwahl (0 oder +49) hat? Also respektiv 10/12 Stellen insgesammt?

Wir prüfen in unserer Validitätsprüfung ob die Nummer 10 Stellen hat (respektive 11/13)
> https://github.com/demokratie-live/democracy-server/blob/master/src/graphql/resolvers/Device.js#L57

Magst du uns dafür kurz Rückmeldung geben? Gerne auch per EMail. Details zu dem Mobilfunkprovider und dem alter der Nummer wären großartig um zu prüfen in wieweit es sinnvoll ist die oben verlinkte Regel zu ändern.

<3 Ulf

**Comment by PerhapsSomeone** [comment]
Meine Nummer sieht so aus:
+49 173 XXXXXXX
Insgesamt sind es also 10 Stellen.
Ich bin bei 1&1, die Nummer ist ungefähr vier Jahre alt.
