### ISSUE TITLE
🗣 Weitere Zahlungsmethoden: Playstore-Pay/Apfel-Pay, Paydirect, Bankeinzug

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#691]
### Weitere Zahlungsmethoden: Playstore-Pay/Apfel-Pay, Paydirect, Bankeinzug

```
Könntet ihr nicht eine Funktion einfügen durch Ingame-Käufe zu spenden?
So wie das Spiel "Conspiracy", bei welchem man durch diese keine zusätzlichen
Funktionen bekommt, sondern durch Ingame-Käufe mit verschiedenen Preisen
(1€, 2€, 5€, usw.) Geld spenden kann, ohne dabei all seine Bankdaten
angeben zu müssen. Da viele Leute Guthaben für den Play Store übrig
haben, würde man dadurch vielleicht eher auf die Idee kommen zu spenden.
```

Ein anderer Nutzer schlägt Pay-Direct vor.

Apfel-Pay ist mittlerweile in Deutschland angekommen für Gemeinnützige Anwendungen

Nutzer per EMail:

```
Ein GiroCode QR wäre auch super, ist in 2 Sekunden erstellt!
Ein Spendenkonto für Bitcoin oder sogar Stellar Lumen ist auch in wenigen
Minuten eingerichtet und die Wallet Adresse bei euch hinterlegt. Die PayPal
Gebühren müssen ja nicht sein!
  GiroCode QR (enhancement)
  Bitcoin Wallet (feature)
  Andere Cryptowährungen, zb. Stellar Lumen (advanced feature)
```

**Comment by Echolon** [comment]
LiberaPay

**Comment by visionmakery** [comment]
"Aber es wäre noch leichter gewesen, wenn ich den Empfänger und die IBAN direkt aus dem angezeigt Text hätte kopieren können."

**Comment by Merlin2001** [comment]
@visionmakery : Ich würde vorschlagen, meine Anregung zum Kopieren der Bankverbindungsdaten als gesondertes Issue zu tracken, da es letztendlich nur Folgendes bedeutet:
Der Text auf der Spendenseite sollte selektier- und kopierbar sein - damit wäre das Problem schon gelöst :)

Wenn du einverstanden bist, lege ich gern ein entsprechendes Issue an.
(Ich muss mir auch mal anschauen, ob ich das nicht selbst implementieren und euch einen Pull-Request schicken kann.)

**Comment by ManAnRuck** [comment]
Kopieren von App texten: https://github.com/demokratie-live/democracy-client/issues/1258

Android Spenden: https://github.com/demokratie-live/democracy-client/issues/1281
