### ISSUE TITLE
🐛 Zurück-Button funktioniert nicht

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#709]
## 🐛 Bugreport
2 Nutzer merken an, dass in der App der Zurück-Button der DetailPage nicht mehr geht, vgl.

"hallo ich finde die app total gut. leider funktioniert die zurück knopf nicht wenn ich in einer abstimmung war, so dass immer die tastatur auf geht anstelle der vorherige bildschirm erscheint."
(galaxy s9)

"die aktuelle Version der Democracy App lässt keine Nutzung des zur Button des Smartphones zu.
Meine Android Version habe ich angehängt."

![screenshot_20190111-155955_settings](https://user-images.githubusercontent.com/32302889/51128282-c3d7c600-1827-11e9-8c66-0114daa5215b.jpg)

Kannst Du das bestätigen @ulfgebhardt ?
### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by visionmakery** [comment]
![bildschirmfoto 2019-02-02 um 20 52 56](https://user-images.githubusercontent.com/32302889/52168640-939b8d00-272c-11e9-849b-dde78b9fbb36.png)
<img width="744" alt="bildschirmfoto 2019-02-02 um 20 53 01" src="https://user-images.githubusercontent.com/32302889/52168641-939b8d00-272c-11e9-9e0c-b1860b130cc2.png">

**Comment by visionmakery** [comment]
Ein weiterer Nutzer merkt an:

"Die Zurücktaste in der App öffnet bei mir den Nummernblock 
Ich muss die App dann schließen um wieder auf die Hauptseite zu kommen"

**Comment by michas79de** [comment]
Ich habe das gleiche Problem: Ich kann nirgends zurück gehen, bekomme dafür immer die Tastatur geöffnet und muss stattdessen die App "abschießen" und neu öffnen. Mehr als umständlich.
Version 1.0.5 von F-Droid auf Samsung Galaxy S8 mit Android 9.

**Comment by ManAnRuck** [comment]
mit der neuen navigationslibrary sollte dieses problem behoben sein (release der neuen app 15. März 🎉)
