### ISSUE TITLE
Namentliche Abstimmungen können fehlerhafte Daten liefern

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#714]
## 🐛 Bugreport
https://internal.democracy-app.de/gesetzgebung/238561/gesetz-zur-einstufung-georgiens-der-demokratischen-volksrepublik-algerien-des-koenigreichs-marokko-und-der-tunesischen-republik-als-sichere-herkunftsstaaten

#### Titel
Gesetz zur Einstufung Georgiens, der Demokratischen Volksrepublik Algerien, des Königreichs Marokko und der Tunesischen Republik als sichere Herkunftsstaaten

#### procedureId: 
238561

Live Server funktioniert
alpha und Internal funktionieren nicht
- keine Änderungen am server 🧐

**Comment by ulfgebhardt** [comment]
no triage - new scrapers available now
