### ISSUE TITLE
🛠[Code Refactoring] Monorepo

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#715]
## 🗣 Suggestion
Use Monorepo with Yarn Workspaces

https://github.com/ReggaePanda/React-Native-Web-TypeScript-Prettier-Boilerplate
https://medium.com/grand-parade/monorepo-setup-with-lerna-typescript-babel-7-and-other-part-1-ac60eeccba5f

**Comment by visionmakery** [comment]
haben wir umgesetzt, oder?
