### ISSUE TITLE
🐛[PDF Viewer] Zoom is limited in Landscape Mode

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#718]
### [PDF Viewer] Zoom is limited in Landscape Mode

Maximum Zoom:
![image](https://user-images.githubusercontent.com/1238238/51677281-67b83300-1fd9-11e9-88ed-5c5cf6451500.png)

![image](https://user-images.githubusercontent.com/1238238/51677484-165c7380-1fda-11e9-9bcb-eca33dd046f8.png)

### App-Version & Environment

APP: [Alpha 1.10 (new PDF Viewer)]

OS:  [Android, iOS]

### Steps to reproduce
1. Open PDF 
2. Switch to Landscape Mode
3. Zoom
4. ...
5. Profit

**Comment by WolfgangLeiendecker** [comment]
This bug is open since 10 month.
It's very difficult to read the documents.
How can I use my own PDF reader instead of the app-iternal reader?

**Comment by ulfgebhardt** [comment]
We are working on an update @WolfgangLeiendecker . With it we will update the Library and might even add the possibility to download the PDF so you can use your own PDF reader.

**Comment by WolfgangLeiendecker** [comment]
Cool. THX. 

 

Von: Ulf Gebhardt <notifications@github.com> 
Gesendet: Freitag, 6. Dezember 2019 08:26
An: demokratie-live/democracy-client <democracy-client@noreply.github.com>
Cc: WolfgangLeiendecker <wolfgang.leiendecker@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [demokratie-live/democracy-client] 🐛[PDF Viewer] Zoom is limited in Landscape Mode (#718)

 

We are working on an update @WolfgangLeiendecker <https://github.com/WolfgangLeiendecker>  . With it we will update the Library and might even add the possibility to download the PDF so you can use your own PDF reader.

**Comment by ManAnRuck** [comment]
Größerer Zoom und pdf Download mit der kommenden Version endlich möglich
![503C4B4B-F4C2-452D-9B40-8043E134A26E.jpeg](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/5e21bac8-7f68-429a-b2a6-d536484e3586)![9CE56626-9E87-4298-A020-B3238B07D40D.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/023ac3de-2450-453c-a89c-0a87d71ae0b5)

**Comment by ManAnRuck** [comment]
Da es in der kommenden Version (im März) gelöst sein wird 😊 schließen wir das ticket. 

Falls es in der neuen Version doch noch zu Problemen kommt, öffnen wir es gerne wieder
