### ISSUE TITLE
🗣 App in allen Ländern zur Verfügung stellen?

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#725]
## 🗣 Suggestion

Wir haben oft Anfragen aus Österreich und der Schweiz.
Die App dort zugänglich machen?

Alpha ist bereits weltweit für Browserstack

![image](https://user-images.githubusercontent.com/1238238/51996140-75c3f300-24b4-11e9-9700-4d0fb672a60b.png)

Diejenigen, die keine deutsche Handynummer besitzen können dann nicht abstimmen.

**Comment by visionmakery** [comment]
für alle Länder freigegeben!
