### ISSUE TITLE
🐛 [Android] Changelog is missing on Production

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#733]
### [Android] Changelog is missing on Production

Lately no Changelog is available with Android Production releases

### App-Version & Environment

APP: [1.1.1]

OS:  [Android]

### Steps to reproduce

![image](https://user-images.githubusercontent.com/1238238/52337444-f11f2a80-2a07-11e9-8c83-8fbaa3a7fe88.png)

![image](https://user-images.githubusercontent.com/1238238/52337464-fd0aec80-2a07-11e9-848d-54979eaa659e.png)

![image](https://user-images.githubusercontent.com/1238238/52337480-05fbbe00-2a08-11e9-9ff2-307758278d27.png)

**Comment by ManAnRuck** [comment]
Production machen wir händisch
