### ISSUE TITLE
🐛 [iOS] Production builds fail on Travis due to missing groups options

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#734]
### [iOS] Production builds fail on Travis due to missing groups options

https://travis-ci.org/demokratie-live/democracy-development/jobs/489128089

```[16:58:08]: You must specify at least one group using the `:groups` option to distribute externally ```

![image](https://user-images.githubusercontent.com/1238238/52337633-74408080-2a08-11e9-9c61-b45dd39f775c.png)

### App-Version & Environment

APP: [1.1.1]

OS:  [iOS]

**Comment by ManAnRuck** [comment]
mit neuer version obsolet
