### ISSUE TITLE
🐛 [Search] Suchscreen wird nicht aktualisiert nach Abstimmen/Upvoten

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#750]
### App-Version & Environment

APP: [1.1.1]

OS:  [Both]

### Steps to reproduce
1. Search
2. Navigate to Details
3. Upvote/Vote
4. Navigate Back
5. Searchresult is not updated
6. ...
7. Profit

**Comment by ManAnRuck** [comment]
duplicate https://github.com/demokratie-live/democracy-client/issues/501
