### ISSUE TITLE
🐛 [Optimization] Speed of Detailpage/Wahl-O-Meter rendering when cache is available

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#752]
### [Optimization] Speed of Detailpage/Wahl-O-Meter rendering when cache is available

When data is cached the Spinners for Detailpage/Wahl-O-Meter are not displayed. This causes the App to freeze for a few Moments (up to 5sec) till everything is rendered properly.

There is a massive slowdown when the Community Result is present. This might be due to the way its rendered or because the cache is always present when the Community  Results are shown.

Solution:
Evene when cache is present show spinner till rendering is complete

### App-Version & Environment

APP: [1.1.1]

OS:  [Android mostly]

**Comment by ManAnRuck** [comment]
mit neuer version behoben
