### ISSUE TITLE
🗣 [Filter/Sort] Nach Aktualisierung sortieren aus Vergangen rausnehmen oder in Abstimmen reinnehmen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#754]
### [Filter/Sort] Nach Aktualisierung sortieren aus Vergangen rausnehmen oder in Abstimmen reinnehmen

Vergangen Liste hat "nach Aktualisierung sortieren"
Abstimmen Liste hat das nicht

-> vereinheitlichen

**Comment by visionmakery** [comment]
in vergangen kein Unterschied zwischen 'nach Vorgangsdatum' und 'nach Aktualisierung' sortieren -> eins rausschmeißen!

**Comment by visionmakery** [comment]
keine Sortierung mehr in 1.3
