### ISSUE TITLE
🐛 Falscher Farbcode bei den Abgeordnetenprofilen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#760]
## 🐛 Bugreport
Anstatt die BT-Farben zu verwenden, wird hier der Farbcode der Community-Ergebnisse in der Legende verwendet
https://cdn.discordapp.com/attachments/385901951881052161/547808727517102100/image0.png

### App-Version & Environment
1.2.1

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by olierxleben** [comment]
Moin zusammen, es sieht mir so aus als ob das hier noch zu haben sei. für Hacktoberfest würde ich mir das gerne mal anschauen.

**Comment by visionmakery** [comment]
Hammer, Danke für Deine Contribution!

**Comment by ManAnRuck** [comment]
Ist nun in der neuen Version umgesetzt
Testing:
Abgeordnetenprofilseite checken

<img width="584" alt="Bildschirmfoto 2020-02-05 um 08 13 35" src="https://user-images.githubusercontent.com/2183135/73819250-6b3ae880-47ef-11ea-81a3-e5aa98d0695a.png">

**Comment by ulfgebhardt** [comment]
Test: ok
