### ISSUE TITLE
Navigation to Wahl-O-Meter to Bundestag an back to Wahl-O-Meter fails

### ISSUE THREAD

**Issue by WolfgangLeiendecker** [demokratie-live/democracy-client#762]
### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by WolfgangLeiendecker** [comment]
###App-Version & Environment

APP: [Alpha 1.2.1]

OS: [Androide 6.0]

Smartphone: [Acer T11]

### Steps to reproduce

1. Go to Wahl-O-Meter
![screenshot_20190220-194230](https://user-images.githubusercontent.com/47830193/53118040-819f5400-354c-11e9-94ef-7f804fcd5735.png)
![screenshot_20190220-194237](https://user-images.githubusercontent.com/47830193/53118042-819f5400-354c-11e9-9377-4bfc6a2abb50.png)
![screenshot_20190220-194245](https://user-images.githubusercontent.com/47830193/53118045-819f5400-354c-11e9-8b83-7582d80ec7a0.png)

2. Return to Bundestag via Back-Button
![screenshot_20190220-194253](https://user-images.githubusercontent.com/47830193/53118046-8237ea80-354c-11e9-8be1-93ffbe137bf3.png)

3. Try to open Wahl-O-Meter again using Menue
![screenshot_20190220-194310](https://user-images.githubusercontent.com/47830193/53118151-c88d4980-354c-11e9-8f95-470365252ae2.png)
![screenshot_20190220-194329](https://user-images.githubusercontent.com/47830193/53118152-c88d4980-354c-11e9-978c-47ee61395f8e.png)

4. The app stays on Site Bundestag, instead of jump to Wahl-O-Meter
![screenshot_20190220-194337](https://user-images.githubusercontent.com/47830193/53118193-db078300-354c-11e9-9553-539adc143054.png)

Workaround:
- Use the menue to go to e.g. Statistik
- Then use the menue again to go to Wahl-O-Meter

**Comment by visionmakery** [comment]
mit 1.3 gelöst!
