### ISSUE TITLE
[Scraper] party in deputy name

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#765]
## 🐛 Bugreport
In some Deputies is the party name included

<img width="684" alt="Bildschirmfoto 2019-03-08 um 20 56 30" src="https://user-images.githubusercontent.com/2183135/54087505-bb959600-4353-11e9-8c73-c6390c6c44a9.png">

<img width="705" alt="Bildschirmfoto 2019-03-08 um 20 57 08" src="https://user-images.githubusercontent.com/2183135/54087511-c2240d80-4353-11e9-8721-af1faac4df28.png">

`db.getCollection('deputies').find({"name" : { $regex: /(SPD|CDU|Linke|Grünen|Fraktionslos|FDP|AFD)/, $options: "si" }}).count();`

**Comment by ulfgebhardt** [comment]
Not yet live but fixed
