### ISSUE TITLE
🐛 [Details] Vote & Interaction minor Problems (Highlight on Upvote, Wrong Vote Default)

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#766]
#### Upvote button hat trotz Schloss noch eine interaktion auf click (highlight)
![image](https://user-images.githubusercontent.com/1238238/54197314-e272da00-44c3-11e9-8ee9-0afa8cbb785b.png)

#### Bis der voted status geladen ist wird eine velorene Stimme angezeigt
![image](https://user-images.githubusercontent.com/1238238/54197373-0c2c0100-44c4-11e9-9ee9-eea94a9663e9.png)
![image](https://user-images.githubusercontent.com/1238238/54197379-0f26f180-44c4-11e9-9b56-753485716b7f.png)

### App-Version & Environment

APP: [1.2.1]

OS:  [Android]

### Steps to reproduce
1. Navigate to Detail Page
2. See lost Vote
3. Wait - see vote option
4. ...
5. Profit

1. Navigate to Detail Page
2. Upvote - see lock
3. Keep clicking upvote
4. ...
5. Profit

**Comment by visionmakery** [comment]
gelöst mit 1.3
