### ISSUE TITLE
Tippfehler (Direktkandidat anstatt Direktkadidat)

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#778]
## 🐛 Bugreport
Ein Nutzer merkt an:

"Sehr geehrte Damen und Herren,

gespannt habe ich auf das release der APP gewartet und wurde sehr positiv überrascht. Allerdings komme ich leider nicht umhin euch auf einen Tippfehler hinzuweisen. 
Das ist natürlich grundsätzlich nur menschlich und meine eigenen Leistungen im Fach Deutsch legen nahe, dass ich niemals etwas dazu sagen sollte, aber es ist dennoch sehr ärgerlich. 
Davon unabhängig- weiter so!"
![Screenshot_20190324-160442](https://user-images.githubusercontent.com/32302889/55146835-95d70200-5145-11e9-8223-8efe9822953a.png)

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by Lednerb** [comment]
Related to #799, done in #802

**Comment by lkreimann** [comment]
Could you please close this issue or label it accordingly, if it's already fixed?! :) That would be great!
