### ISSUE TITLE
Verifizierung-Button im Tutorial anpassen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#779]
## 🗣 Suggestion
Ein Nutzer schreibt:
"Zunächst habe ich aus Versehen die Verifizierung übersprungen, weil es so aussah als wäre der Button ein Teil des Screenshots unter dem Text (siehe Anhang).
Vielleicht könntet ihr den Button neben das "Überspringen" verschieben, dann ist es eindeutig, dass man entweder verifizieren oder überspringen kann. (Oder ihn anders hervorheben, damit er nicht so aussieht als wäre er nur ein statischer Teil des Screenshots.)"

**Comment by Merlin2001** [comment]
Ich war der Nutzer 😊 - bei Rückfragen jederzeit gerne hier!
