### ISSUE TITLE
PLZ als Ganzzahl modelliert

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#780]
## 🐛 Bugreport
Ein Nutzer merkt an:

"ihr habt die PLZ im Wahlkreis als Ganzzahl modelliert. Das ist für den ganzen Osten ungünstig. Ich finde Dresden nur via 1097 und nicht 01097. Wenn es noch geht, würde ich euch empfehlen euer Model anzupassen. Ansonsten muss der fix ins UI."

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by visionmakery** [comment]
"Das alte Postleitzahlenproblem mit der ersten "Zahl" Null tritt bei der
Wahlkreissuche auf.
Beispiel: Ich suche 04329 und es passiert nichts. Ich muss 4329
eingeben, wenn ich das "Problem" kenne."

**Comment by ulfgebhardt** [comment]
@Manu How to Test?

**Comment by ManAnRuck** [comment]
testing:
plz mit beginnender 0 suchen
z.B. `01445`  = Meißen

**Comment by visionmakery** [comment]
klappt!

**Comment by ulfgebhardt** [comment]
Die Suche funktioniert, die Listendarstellung zeigt das ganze allerdings ohne 0 an:
"Meißen Wahlreis 155: 1936, 1445, ..."

**Comment by mheinzerling** [comment]
Ich möchte nochmal darauf hinweisen, dass das keine Frontend sondern ein Model-Problem ist. PLZ sind Strings, keine Integers.

**Comment by ManAnRuck** [comment]
Diese werden bereits als Ganzzahlen behandelt jedoch fehlen in der rohdatei bereits die führenden Nullen. Innerhalb der App der neuen Alpha sollte nun alles korrekt dargestellt werden

**Comment by ulfgebhardt** [comment]
Test: ok
