### ISSUE TITLE
Deutlichere Kommunikation von Alternativen Anträgen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#783]
## 🗣 Suggestion

Feature-Request: Deutlichere Kommunikation von Alternativen Anträgen 

 Hallo Jungs, ich nutze eure App regelmäßig und bin begeistert vom Konzept. Bei den Abstimmungen ist mir aufgefallen dass systembedingt gelegentlich mehrere Lösungsvorschläge zu einer Problematik vorliegen (aktuell z.b. zum Thema Wolf) Da die Vorgänge vollständig unabhängig hinterlegt sind, tendiert man als Nutzer dazu, nur zu einem Antrag ab zu stimmen. Dieser bekommt dadurch mehr Interaktionen und verdrängt im Ranking die Alternativen. Außerdem fällt mir auf, dass teilweise zwei völig konträre Vorschläge ähnliche Mehrheiten bekommen. Das ist im Sine einer Parlamentssimulation nicht hilfreich. Ich möchte vorschlagen, wenn es zu einem Beschluss verschiedene Vorlagen gibt, diese als Alternativen untereinander zu verlinken um den Nutzer deutlicher, intuitiver und auffälliger zu informieren. Ich stelle mir zwischen "Details" und "Dokumente" noch eine optionale Rubrik "Alternativen" vor. Eine andere Möglichkeit wäre, in der Rubrik Abstimmung verschidene Abstimmungen zu den jeweiligen Alternativen unterineander an zu beiten. Das könnte aber unter Umständen zu mehr Verwirrung führen.  Ich glaube, dass sich durch eine deutlichere Kommunikation von Alternativen auch ein deutlicheres Meinungsbild aus der Nutzerschaft ergibt, wenn Nutzer zwar formal über einzelne Anträge, doch de facto zwischen alternativen wählen.  Macht weiter so! Martin.

**Comment by visionmakery** [comment]
Daten:
Eine Möglichkeit wäre die Beschlussempfehlungen auslesen, Verlinkte Drucksachen zu referenzierten und in ein Abstimmungspaket zu Clustern

**Comment by visionmakery** [comment]
Nutzerfeedback

"Ich nutze jetzt seit ein paar Wochen eure App. Die Handhabung ist einfach, die nötigen Informationen vorhanden und es wäre interessant, die Abstimmungsergebnisse mit der Community zu vergleichen.
 
Ja, wäre, mir ist nämlich heute - nicht zum ersten Mal – ein Logikproblem aufgefallen.
 
Es geht im Beispiel um Anträge verschiedener Fraktionen zur Finanzierung der Hochschulen. Unter den Überschriften
"Finanzierung der Wissenschaft auf eine arbeitsfähige Basis stellen"
"Hochschulpakt 4.0 - Qualitätsoffensive für die Lehre"
"Neue Dynamik für die Hochschulfinanzierung"
und "Neuer Hochschulpakt 2021"
wurden 4 unterschiedliche Anträge eingereicht. Die kritisierten Punkte sind gleich oder ähnlich, die Ansätze zur Behebung sehr unterschiedlich. Es ist also so, dass man gar nicht ohne Widerspruch jedem der 4 Anträge zustimmen kann. Jedoch sehe ich folgendes an Zustimmungen:
82 %
80 %
83 %
60 %
 
Mir fallen dazu nur 2 Möglichkeiten ein.
1. Überschrift zählt
Vielleicht ist es ja so, dass viele nur die Überschriften lesen, die für sich genommen alle gut klingen, und danach entscheiden. Wie die Anträge im Detail aussehen, ist vielen dann egal, weil man dafür die Anträge sorgfältig lesen und verstehen muss.
2. Antragsteller zählt
Man nimmt sich den Antrag der bevorzugten Partei und stimmt dann dafür. Konsequenter Weise müsste man dann die anderen Anträge ablehnen, außer man ist zu bequem dazu oder hat schlicht kein Interesse."
 
Für mich stellt beides ein Problem dar. Die 2. Variante wäre eine Erklärung, dass alle Anträge hohe Zustimmung erfahren, jedoch keine, dass es keine Gegenstimmen gibt. Die 1. Variante ist ebenfalls schlecht, da dies das Bild völlig verzerrt, da sich die Abstimmenden dabei offensichtlich nicht genug Gedanken um die Inhalte machen. Ich weiß nicht, was schlimmer ist.

**Comment by Lednerb** [comment]
Sehe ich ähnlich wie der zitierte Nutzer, allerdings entfällt 1) Auf den Antragssteller da passendes zu Wählen. Die Beteiligung bei Vorschlägen mit verständlichem Titel sind auch wesentlich höher als bei "Gesetz zur Änderung von Gesetz zum Thema X vom Datum Y". Dies ist aber eher ein *politisches* Problem als ein technisches.

Zitierte Möglichkeit Nr. 2 wird mit einer Diskussions- bzw. einzelnen Abstimmungsmöglichkeit pro Antragspunkt möglich, dass man wirklich zu einzelnen Punkten eine Zustimmung oder Ablehnung äußern kann.

Mir persönlich geht es teilweise so, dass Antrag X 10 Punkte zur Realisierung vorschlägt, wovon ich 8 zustimmen würde, bei einer nicht ganz sicher bin, ob dies der richtige Ansatz wäre und 1 Punkt eine absolute Ablehnung in mir auslöst.
Das Abstimmungsverhalten in einem solchen Fall ist natürlich sehr individuell und birgt einen gewissen Konflikt (muss nicht unbedingt negativ sein, immerhin denkt man als Nutzer auch über die alternativen nach).

------------------------------------------------------------

### TL;DR
- Eine Auflistung von "Ähnlichen Anträgen" oder "Alternativen Anträgen" mit entsprechender Verlinkung wäre sinnvoll.
- In einer späteren Version wäre es schön (ist soweit ich weiß ohnehin geplant) über die einzelnen Inhaltlichen Lösungsaspekte abstimmen zu können und in eine Diskussion zu treten. Gerne auch direkt mit einem Zugang für die Abgeordneten (verifiziert), sodass diese zu *ihrem* Antrag direkt Stellung nehmen könnten.

**Comment by visionmakery** [comment]
Ein Nutzer schreibt: 
Ich habe eine Frage: Wenn es zur Abstimmung über ein Gesetz zu einer Problemstellung kommt, formuliert ja oft jede Fraktion ihre eigene Version davon und dann werden alle Versionen außer die der Regierungsparteien abgelehnt. 
Wäre es möglich in der App immer alle Versionen unter einem Punkt zu gruppieren, sowie das in den "Beschlussempfehlung und Bericht" Dokumenten der Fall ist?
Dann könnte ich mir einen Überblick verschaffen, was die verschiedenen Vorschläge sind ein Problem zu lösen und mich entscheiden, welchen Lösungsvorschlag ich am Besten finde. 
Im Moment tippe ich auf einen Entwurf, finde ihn gut und Stimme dafür und später finde ich einen Entwurf zum gleichen Problem mit einer besseren Lösung und Stimme auch dafür. Wenn ich das aber vorher gewusst hätte, hätte ich bei Entwurf eins mich enthalten, weil ich weiß, es gibt noch eine bessere Lösung. Im Moment ist es etwas schwierig in der App den Überblick über verschiedene Gesetzentwürfe zur gleichen Problemstellung zu behalten.
