### ISSUE TITLE
Chinesisches Schriftzeichen in der Liste nach dem Abstimmen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#791]
## 🐛 Bugreport
"Hallo 
mir ist aufgefallen, dass nach dem Abstimmen in der Übersichtsliste ein 
archaisches chinesisches Schriftzeichen (𠗟) auftaucht. Ich denke mal, da 
sollte was anderes angezeigt werden, aber es stimmt vielleicht mit der 
Codierung etwas nicht oder vielleicht fehlt eine Font. Ich hab einen 
Screenshot angehängt." 
![20190402_193811](https://user-images.githubusercontent.com/32302889/55540463-58cdbb00-56c3-11e9-90c5-b3209b15b414.jpg)

### App-Version & Environment

APP: []

OS:  Samsung Galaxy S9 mit Android 9. Die Systemsprache ist Englisch.

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by michas79de** [comment]
Das Zeichen erscheint bei mir auch.
Version 1.0.5 von F-Droid auf Samsung Galaxy S8 mit Android 9 in Deutsch.

**Comment by muessjoeh** [comment]
Bei mir erscheint es ebenfalls, und zwar bei Einträgen, die bereits von mir abgestimmt wurden. Außerdem habe ich beim Filtersymbol angewählt, dass er keine bereits abgestimmte Einträge darstellt. Es wird also nicht nur ein chinesisches Schriftzeichen dargestellt, sondern bereits abgestimmte Einträge werden nicht als solche erkannt.

**Comment by ulfgebhardt** [comment]
@michas79de @muessjoeh Is this still the case after the latest F-Droid Update (Version 1.22) ?

**Comment by muessjoeh** [comment]
Ich benutze kein F-Droid, sondern lediglich die aktuelle Version (1.2.2) über den Appstore. Und diese weist diesen Bug auf.

**Comment by michas79de** [comment]
I'm sorry to say, but yes, the problem still exists with the F-Droid version 1.2.2 (103578).

**Comment by ManAnRuck** [comment]
mit der neuen kommenden version ist dieses problem behoben 🎉
