### ISSUE TITLE
🐛 Crash beim Öffnen des Wahl-O-Meters

### ISSUE THREAD

**Issue by fynngodau** [demokratie-live/democracy-client#792]
## 🐛 Bugreport

Crash beim Öffnen des Wahl-O-Meters.

### App-Version & Environment

APP: [versionCode 103578, versionName 1.2.2]

OS:  [Android 8.1.0]

### Steps to reproduce
Ich vermute, dieser Fehler tritt auf, weil alle meine Stimmen lokal verloren gegangen sind und der Wahl-O-Meter, wenn ich das richtig verstanden habe, seine Schlüsse daraus zieht.

**Comment by ManAnRuck** [comment]
Das deine Stimmen lokal weg sind ist schonmal alles andere als gewollt 😢
Den daraus folgenden Absturz hast du wohl richtig analysiert. Da müssen wir auf jeden fall nochmal ran. Danke dir!

Nach einer Umstellung auf TypeScript (geplant) sollten Folgefehler dieser Art nicht mehr auftreten können.

**Comment by IFoundAnotherUsername** [comment]
Ich habe eine ältere Version (102715, Android 8.0.0) und bei mir tritt dieser Fehler auch bei direkt davor getätigten Abstimmungen auf. Vielleicht verstehe ich nicht, was lokal verloren meint, aber ich könnte mir auch vorstellen, dass es mit Anderem zu tun hat.
Wenn ich auf Einstellungen>Statistik klicke, crasht die App ebenso.

Sollte dieser Fehler schon bei neueren Versionen verschwunden sein, wäre es nett, wenn das Fdroid-Repo dann dahingehend geupdatet würde. :)

**Comment by ManAnRuck** [comment]
sollte in der neuen (kommenden) version behoben sein. gerne nochmal testen
Android: https://www.democracy-deutschland.de/invite/28EAD8EE
iOS: https://testflight.apple.com/join/qZ6BmERW

**Comment by ManAnRuck** [comment]
in der neuen version kam es zu keinem krash daher schließen
(release am 15.03)
