### ISSUE TITLE
🐛 Suche fehlerhaft

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#793]
## 🐛 Bugreport
Der erste gelistete Eintrag fängt mit dem Wort "Kinderchancengeld" an. Dieses Wort kommt also definitiv vor. Wenn man über das Lupensymbol nach diesem Wort sucht, wird es jedoch nicht gefunden. 

### App-Version & Environment

APP: [1.2.2 (103578]

OS:  [8.0]

**Comment by ManAnRuck** [comment]
Die suche wurde mit dem letzten update endlich etwas verbessert. Nun sollte es zu finden sein :)
