### ISSUE TITLE
Rechtschreibfehler: Direktkadidat

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#799]
## 🐛 Bugreport
kleiner Typo "Direktkadidat" anstatt Direktkandidat
![Screenshot_2019-05-05-18-58-26-353_de democracydeutschland app](https://user-images.githubusercontent.com/32302889/57366433-3f6ad380-7187-11e9-90fe-a62bf7552287.png)

**Comment by ulfgebhardt** [comment]
duplicate of #778
