### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by Kuhjuice** [demokratie-live/democracy-client#805]
Would be so good to be able to download the PDF

**Comment by ManAnRuck** [comment]
diese funktionalität wird es in der neuen version geben 😊
technisch bereits umgesetzt, eine erste testversion wird es die nächsten tage geben

<img width="412" alt="Bildschirmfoto 2020-02-03 um 10 14 58" src="https://user-images.githubusercontent.com/2183135/73640137-0d32c780-466e-11ea-9872-079419a2f2dd.png">
