### ISSUE TITLE
🚀[Feature]📱Kopieren von Text

### ISSUE THREAD

**Issue by muessjoeh** [demokratie-live/democracy-client#807]
Es kann kein Text markiert und danach kopiert werden. Wenn man in einem Antrag oder in der Langform als PDF lang berührt, passiert gar nichts. Ich würde erwarten, dass der entsprechende Text markiert wird, so dass man ihn kopieren und danach googeln kann.

**Comment by visionmakery** [comment]
Ist mittlerweile möglich. Getestet auf iOS >13, iPhone Xs
