### ISSUE TITLE
Spelling in Datenschutzerklärung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#808]
## 🐛 Bugreport
im vorletzten Satz der Präambel ist ein Schreibfehler (wegen Du/Sie-Umstellung).
Unter 4. Personenbezogene Daten/Eingegebene Daten ist dementsprechend noch von "Deine Wünsche" die Rede.
Diese Hinweise beanspruchen nicht gesicherte Vollständigkeit.

**Comment by Lednerb** [comment]
Ebenfalls kann der Google-Analytics Abschnitt entfernt werden, da GA ohnehin nicht verwendet wird.

https://github.com/demokratie-live/democracy-client/blob/3e636f732d283778b21a4b96fd89f19cba254a4f/src/screens/Imprint/content.js#L126-L133
