### ISSUE TITLE
🐛Suche funktioniert nicht richtig 

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#809]
## 🐛 Bugreport
Hi,

die Suchfunktion funktioniert nicht richtig. Wenn ich z.B. BDS suche, kommt nur ein Ergebnis, dabei müssten mindestens 3 Ergebnisse kommen. Auch bei manchen anderen Suchen kamen weniger Ergebnisse als es Anträge gab.
Wenn ich z.B. nach "collect" Suche, kommt kein Ergebniss, obwohl es mindestens 2 geben müsste.

![Screenshot_2019-05-26-13-24-23~2](https://user-images.githubusercontent.com/32302889/58820003-b9309880-8631-11e9-9778-82b42f382b43.png)
![Screenshot_2019-05-26-13-24-33~2](https://user-images.githubusercontent.com/32302889/58820008-bafa5c00-8631-11e9-8fd5-a65a95727b97.png)

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by ManAnRuck** [comment]
ist auf internal jetzt über eine direkte mongo suche drinnen
