### ISSUE TITLE
Ausländern Einsicht gewähren

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#811]
## 🚀 Feature
Nutzer-Request:
Man könnte nach Installation der App zu Beginn eine Abfrage des Herkunftslandes durchführen bzw. EU/Dritt- oder Deutschland welche nicht mehr änderbar ist. - Somit könnten Interessierte die Ergebnisse verfolgen und jene Personen welche Abstimmungsberechtigt sind würde nicht beeinflusst.

**Comment by Simon-Laux** [comment]
Vielleicht kommen in der Zukunft die anderen Länder ja auch noch dazu und diese Einstellung kann genutzt werden um diese dann zu benachrichtigen wenn ihr Land kommt / oder auch für Abstimmungen die im EU Parlament stattfinden. (evtl. auch für Bundesländer)
Wäre dann auch die frage wie man das UX technisch übersichtlich macht wenn mehrere Scopes(Nationen oder Nationen-Bündnisse wie die EU) für den Nutzer verfügbar sind.

**Comment by ManAnRuck** [comment]
nicht mehr änderbar ist auch schwierig, da man ja ggf. nach Deutschland ziehen könnte.
ich denke da müssten wir einen anderen weg finden.

mein Vorschlag mit der Annahme, dass die Benutzer wenn möglich abstimmen möchten.
nicht verifizierte sehen die Ergebnisse sofort, sobald man verifiziert ist nur noch nach dem Abstimmen.
mit dem Wahl-O-Mat gibt es nun einen weiteren Grund sich zu verifizieren.

**Comment by ulfgebhardt** [comment]
I will close this issue since we now allow to download the App worldwide.

To vote you still have to posses a German mobile phone number (+49).

If you are able to obtain such a number you will also be able to vote worldwide.

**Comment by ManAnRuck** [comment]
@ulfgebhardt der Wunsch Einsicht in die Ergebnisse zu gewähren ist noch nicht erfüllt. (derzeit ist die Registrierung Voraussetzung, was ja nicht möglich ist ohne deutsche Nummer)

**Comment by ulfgebhardt** [comment]
Lösen wir das mit dem neuen Design? Ja oder? @ManAnRuck

**Comment by ManAnRuck** [comment]
Ich würde sagen, das ist noch nicht zu 100% sicher. Sollten da Ggf. Noch das Detail screen refinement machen

**Comment by Simon-Laux** [comment]
_Wow ihr arbeitet ja auch nachts...._
> Lösen wir das mit dem neuen Design?

neues api design? wo kann ich mich darueber informieren? (rein interesse halber)

**Comment by ManAnRuck** [comment]
@Simon-Laux rund um die Uhr (aber auch rund um den Globus 😉)

Wir bringen die App technisch mal auf den aktuellen stand und versuchen damit auch die meisten Kinderkrankheiten auszumerzen und die Weiterentwicklung zukünftig etwas zügiger hinzubekommen.

Sprich: 
- TypeScript
- unitTests
- e2e Tests

hier zwei issues mit ein wenig Ausblick was zusätzlich kommt
https://github.com/demokratie-live/democracy-client/issues/928
https://github.com/demokratie-live/democracy-client/issues/923

**Comment by ManAnRuck** [comment]
Ist in der neuen version möglich.
Logik:
- in vergangenen Prozeduren sind alle charts zu sehen
- nicht vergangende zeigen communitychart nur nach eigener abstimmung

Testing:
- stimmt die beschriebene logik

**Comment by ulfgebhardt** [comment]
test: ok
