### ISSUE TITLE
🚀 Deeplinking

### ISSUE THREAD

**Issue by Simon-Laux** [demokratie-live/democracy-client#816]
## 🚀 Feature
The app registers as handler for the website address so that **shared content can get opened with the app** and not in the browser when the app is installed.
Deeplinking an web url might not work in very old OS versions, the website could provide an "open in app" link that uses a custom URI scheme like `demokratie:` as fallback for older devices.

probably related: https://github.com/demokratie-live/democracy-client/issues/203

### Design & Layout
does not apply

**Comment by Simon-Laux** [comment]
Just noticed this might be a duplicate of #784

**Comment by ManAnRuck** [comment]
thank you for your report, yes we can handle it as a duplicate.
btw, we have to do some big changes du support new android versions and therefor we also refactor the push notifications :)
