### ISSUE TITLE
🐛ListView "already voted for this one" checkmark, Icon is missing 

### ISSUE THREAD

**Issue by Simon-Laux** [demokratie-live/democracy-client#817]
## 🐛 Bugreport
![image-1564036592](https://user-images.githubusercontent.com/18725968/61851586-ae6ae500-aeb7-11e9-84e7-e2043f9cde8c.jpg)
An icon is missing here.

### App-Version & Environment

APP: 1.2.2 (103578) from fdroid

OS:  Android 9

### Steps to reproduce
1. vote for something
2. go back to the list

**Comment by ManAnRuck** [comment]
da wir die liste umgestaltet haben und nun pie charts angezeigt werden, sollte dieses problem in der neuen kommenden version so nicht mehr auftreten können :)
