### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by MIntrovrt** [demokratie-live/democracy-client#819]
## 🚀 Feature

When scrubing the list and take of the finger of the screen, the list should keep scrolling.
Nearly every app has this now, and I don't see why this UI improvement should be missing here.

**Comment by ManAnRuck** [comment]
hi @MIntrovrt you are right, this is not the best behaviour.
on my test devices it works like expected.

do you have some more details for me?
Android or iOS
OS version
and device model

**Comment by MIntrovrt** [comment]
I'm on android 9.0
to be more specific : rr_oneplus3-userdebug 9 
It's a OnePlus 3T

the app version is v1.2.2 (103578) // is that mainline?

Smooth scrolling works in the about and details page but not in any of the vote lists.

**Comment by ManAnRuck** [comment]
thank you 🙂
i tried it on OnePlus 6T (3T is not available on Browserstack) there it works fine.

we currently working on the react-native update, this could solve the issue on your device.

**Comment by visionmakery** [comment]
solved with 1.3
