### ISSUE TITLE
🚀 [Feature] Dependency Update (WIX) (switch to react-navigation)

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#826]
### Dependency Update (WIX)

Update WIX Navigation

Aufwand: Low
Impact: Middle

**Comment by ManAnRuck** [comment]
Da [react-navigation](https://reactnavigation.org) inzwischen besser zu sein scheint, besser gepflegt wird und eine größere community hat, sollte die Library ausgetauscht werden.

**Comment by ManAnRuck** [comment]
wirklich zu RN wechseln oder RNN v3 verwenden?

https://medium.com/hackernoon/how-to-choose-the-right-react-native-navigation-library-48679d63c9e9
