### ISSUE TITLE
🚀 [Feature] Serviceinfrastructure Docker & Kubernetes

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#828]
### Serviceinfrastructure Docker & Kubernetes

Learning: 5D
Umsetzung: 1D

Aufwand: Middle
Impact: Middle

### Design & Layout
![Prozess.png](https://images.zenhubusercontent.com/5d35a18454a8bc2dbc51e9f1/d06e0c22-079d-4fb4-bfb1-5b5f8c0eab86)

**Comment by ManAnRuck** [comment]
eventuell ein sehr interessanter Artikel für dieses ticket 🎫 

https://medium.com/better-programming/containerizing-a-node-js-api-using-docker-with-kubernetes-and-minikube-30255fd33ef9

ebenso könnte caprover sehr hilfreich sein
https://caprover.com

**Comment by ManAnRuck** [comment]
Aufbauend auf learnings von diesem Kurs umsetzbar.
https://www.udemy.com/course/microservices-with-node-js-and-react

Detailiertere ausarbeitung noch ausstehend…
