### ISSUE TITLE
🚀 [Feature] Tests schreiben

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#834]
🌋 Dieses ticket sollte aufgesplittert werden für die einzelnen Repositories

### Tests schreiben

- Unit Tests

corevage Abhängigkeit

Aufwand: Middle
Impact: High

### Additional context
[Detox](https://github.com/wix/Detox)
[DetoxInstruments](https://github.com/wix/DetoxInstruments)

**Comment by ManAnRuck** [comment]
@ulfgebhardt duplicate of #749 ?

**Comment by ulfgebhardt** [comment]
We close this in favor of the Test Epic #909
