### ISSUE TITLE
Replace outdated way to use multiple environments (Alpha, Beta, Production)

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#840]
https://medium.com/@ywongcode/building-multiple-versions-of-a-react-native-app-4361252ddde5

**Comment by ManAnRuck** [comment]
Testing: try to build different stages

`cd packages/mobile-app`
iOS: `react-native run-ios --scheme Alpha --configuration Alpha.Debug`
Android: `react-native run-android --variant=alphaDebug --appIdSuffix=alpha`

**Comment by ulfgebhardt** [comment]
I am unable to compile with the given command

![image](https://user-images.githubusercontent.com/1238238/72721722-02ac0480-3b7d-11ea-8dad-72aa00ec795d.png)

Apparently smth is wrong with the client settings. Did i miss a new configuration?

**Comment by ManAnRuck** [comment]
run `yarn` in root directory of the monorepo

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/72729844-74417e00-3b90-11ea-8d39-24ed00327457.png)

```
* What went wrong:
Task 'installAlphaDebug' not found in project ':app'.
```

running `yarn` in the root directory fixed the Error. But it cant find `installAlphaDebug` nor can it find `installAlpha`.

The following Warning is raised for every Thirdparty library:
```
WARNING: The following project options are deprecated and have been removed: 
android.useDeprecatedNdk
NdkCompile is no longer supported
```

**Comment by ulfgebhardt** [comment]
![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/4b4e2920-0eee-4c87-82e4-e6669d4424cc)

`yarn react-native run-android` works perfectly

**Comment by ManAnRuck** [comment]
@ulfgebhardt funktioniert bei dir evtl. folgender command
`yarn react-native run-android --variant=alphaDebug --appIdSuffix=alpha` oder hast du es schon mit dem `yarn` am Anfang probiert?
