### ISSUE TITLE
🐛 Eigene Abstimmung wird nicht gespeichert

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#856]
## 🐛 Bugreport
Es scheint Fälle zu geben, bei denen das eigene Abstimmungsverhalten nicht gespeichert wird.

### App-Version & Environment

APP: 1.2.2

OS:  Android & iOS

### Steps to reproduce
derzeit unbekannt
- scheint unter anderem bei Neuinstallationen aufzutreten

- tritt mit der selben Handynummer auf mehreren devices auf. Daher schließe ich darauf, dass ein parameter fehlerhaft übertragen/ausgewertet wird und die Schaltfläche zum abstimmen aktiviert sind. Diese sollten jedoch bereits disabled sein. (da wahrscheinlich mit dieser Handynummer eine Abstimmung auf der Prozedere getätigt wurde)

**Comment by visionmakery** [comment]
immer noch ein Problem?

**Comment by ManAnRuck** [comment]
denke dieses problem sollte mit der nächsten version ebenfalls gelöst sein
