### ISSUE TITLE
🚦[E2E-Test] Erster Start der App

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#887]
## Ablauf der Teststory
1. User startet die App
2. User sieht für 2s den Slash-Screen 
3. User navigiert durch das Tutorial, abwechselnd durch Klicken auf ‚Weiter‘ bzw. Den Punkt im Handy (4x)
4. User landet auf dem ListScreen/Abstimmung

**Comment by ManAnRuck** [comment]
How to test:

- yarn e2e:ios-debug
- yarn e2e:android-debug

**Comment by ulfgebhardt** [comment]
Funktioniert auf Android 9 nicht - swipe schlägt fehl

**Comment by ManAnRuck** [comment]
![Bildschirmfoto 2019-12-11 um 15.55.35.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/6ee9e6dd-38a9-4951-a5d4-eae900cceb9c)

![Bildschirmfoto 2019-12-11 um 15.56.28.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/dd7125c5-9f29-42b5-8bed-95d14b20dff7)

leider nicht im emulator mit Android 9 reproduzierbar.

**Comment by ManAnRuck** [comment]
könntest du mal in Android Studio im log schauen ob da was auffälliges ausgegeben wird @ulfgebhardt ?

**Comment by ulfgebhardt** [comment]
Hab ich auf meine Liste geschrieben

**Comment by ulfgebhardt** [comment]
Ich habe schwierigkeiten die App auf Linux auf meinem Device zu debuggen - er kann sich nicht an den externen Prozess anhängen -.-
