### ISSUE TITLE
🚦[E2E-Test] 🏃‍♂️Verifizieren

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#888]
### Szenario 1: Verifizieren via BurgerMenu/Profil

1. User startet die App
2. User landet auf dem ListScreen/Sitzungswoche
3. User klickt auf das BurgerMenu
4. User klickt oben auf 'unverifizierter Nutzer'
5. User sieht den VerifikationsErklärungsScreen
6. User klickt auf Verifizieren
7. User sieht den VerifikationsTelEingabeScreen
8. User gibt seine Handynummer (Testnummer festlegen, z.B. 0000) ein
9. User drückt auf ‚Code anfordern‘
10. User sieht BestätigungderTelefonnummerPopUp und bestätigt mit ‚ja‘
11. User landet auf dem VerifikationsCodeEingabeScreen
12. User bekommt SMS-Code
13. User gibt 6 stelligen SMS-Code mit Fehler ein
14. User korrigiert den fehlerhaften Code und schließt die Verifikation erfolgreich ab
15. User sieht SpendenScreen
16. User klickt auf `Später`
17. User landet auf dem ListScreen/Sitzungswoche

### Szenario 2: Verifizieren via BurgerMenu/Settings

1. User startet die App
2. User landet auf dem ListScreen/Abstimmung 
3. User klickt auf das BurgerMenu
4. User klickt auf 'Settings'
5. User wählt Verifizieren 
6. User sieht den VerifikationsErklärungsScreen
7. User klickt auf Verifizieren
8. User sieht den VerifikationsTelEingabeScreen
9. User gibt seine Handynummer (Testnummer festlegen, z.B. 0000) ein
10. User drückt auf ‚Code anfordern‘
11. User sieht BestätigungderTelefonnummerPopUp und bestätigt mit ‚ja‘
12. User landet auf dem VerifikationsCodeEingabeScreen
13. User bekommt SMS-Code
14. User gibt 6 stelligen SMS-Code mit Fehler ein
15. User korrigiert den fehlerhaften Code und schließt die Verifikation erfolgreich ab
16. User sieht SpendenScreen
17. User klickt auf `Später`
18. User landet auf dem SettingsScreen

### Szenario 3: Verifizieren via Abstimmen

1. User startet die App
2. User landet auf dem ListScreen/Sitzungswoche
3. User klickt auf die oberste Abstimmung
4. User landet auf der DetailPage/$Abstimmung#1
5. User scrollt nach unten
6. User stimmt mit JA ab
7. User sieht den VerifikationsErklärungsScreen
8. User klickt auf Verifizieren
9. User sieht den VerifikationsTelEingabeScreen
10. User gibt seine Handynummer (Testnummer festlegen, z.B. 0000) ein
11. User drückt auf ‚Code anfordern‘
12. User sieht BestätigungderTelefonnummerPopUp und bestätigt mit ‚ja‘
13. User landet auf dem VerifikationsCodeEingabeScreen
14. User bekommt SMS-Code
15. User gibt 6 stelligen SMS-Code mit Fehler ein
16. User korrigiert den fehlerhaften Code und schließt die Verifikation erfolgreich ab
17. User sieht SpendenScreen
18. User klickt auf `Später`
18. User landet auf der DetailPage/$Abstimmung#1

### Szenario 4: Verifizieren via BurgerMenu/Profil **mit App schließen**
1. User startet die App
2. User landet auf dem ListScreen/Sitzungswoche
3. User klickt auf das BurgerMenu
4. User klickt oben auf 'unverifizierter Nutzer'
5. User sieht den VerifikationsErklärungsScreen
6. User klickt auf Verifizieren
7. User sieht den VerifikationsTelEingabeScreen
8. User gibt seine Handynummer (Testnummer festlegen, z.B. #49176...) ein
9. User drückt auf ‚Code anfordern‘
10. User sieht BestätigungderTelefonnummerPopUp und bestätigt mit ‚ja‘
11. User landet auf dem VerifikationsCodeEingabeScreen
12. User bekommt SMS-Code
13. User verlässt die App und schließt beendet Sie im Taskmanager
14. User geht wieder in die App
15. User sieht einen Screen mit 2 Buttons 'Code eingeben' und 'Neuen Code Senden (Timer)'
16. User drückt 'Code eingeben'
17. User gibt 6 stelligen SMS-Code mit Fehler ein
18. User korrigiert den fehlerhaften Code und schließt die Verifikation erfolgreich ab
19. User sieht SpendenScreen
20. User klickt auf `Später`
21. User landet auf dem ListScreen/Sitzungswoche

**Comment by ManAnRuck** [comment]
https://github.com/demokratie-live/democracy-client/actions/runs/92082539

**Comment by visionmakery** [comment]
❓ **Android Szenario 1** (💬 erste 1:20 passiert nicht viel; nach 3:00 ist das Video zu Ende, der Test unvollendet bei 12.)
✅ **Android Szenario 2** (💬 erste 1:20 passiert nicht viel)
✅ **Android Szenario 3** (💬 erste 0:45 passiert nicht viel)

✅ **iOS Szenario 1** 
❓ **iOS Szenario 2** (💬 nach 0:52 ist das Video zu Ende, der Test unvollendet bei 15.)
✅ **iOS Szenario 3**

**Comment by ManAnRuck** [comment]
https://github.com/demokratie-live/democracy-client/actions/runs/96542935
jetzt sollte man das ende sehen, lasse die tests jewels 3 Sekunden länger laufen
