### ISSUE TITLE
🗣[Browser] Suche: Prozeduren durch Click in neuem Tab öffnen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#902]
## 🐛 Bugreport
Wenn man etwas sucht und mit STRG/Command+click eine Prozedur in einem neuen Tab öffnet, setzt sich die suche zurück. In dem Fall sollte die suche bestehen bleiben.

Using the search, open a procedure with STRG/Command+click in a new tab, it sets back.
In that case, the search should persist.

**Comment by visionmakery** [comment]
closed with Gregs Release
