### ISSUE TITLE
🛠Fehlende Xcode 11 Kompatibilität

### ISSUE THREAD

**Issue by olierxleben** [demokratie-live/democracy-client#904]
## 🐛 Bugreport
Fehlermeldung aus Simulator beim Laden der App.  
<img width="428" alt="image" src="https://user-images.githubusercontent.com/1403225/66218432-78bd5600-e6c9-11e9-9841-ac41564e240d.png">

### App-Version & Environment
APP: [Democracy Client]

OS:  macOS 10.14.6, target: iOS 13  (iPhone Simulator)

### Steps to reproduce
1. yarn start:ios --simulator "iPhone 11" 
2. wait to compile

### Solution
Bug wohl bekannt, Anheben der React Native Version zu react-native > 60.x

**Comment by olierxleben** [comment]
ich würde es mir auch gern direkt schnappen...

**Comment by ManAnRuck** [comment]
Bin derzeit dran die react version auf den neuesten Stand zu bringen🙂
https://github.com/demokratie-live/democracy-client/issues/818

**Comment by olierxleben** [comment]
👌 ok

**Comment by ManAnRuck** [comment]
@olierxleben repo ist jetzt aktualisiert und nun sollte es wieder funktionieren :)
