### ISSUE TITLE
[APP] 📱 Sitemap / Userflow / Systemmap

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#907]
![Systemmap DEMOCRACY](https://user-images.githubusercontent.com/32302889/66915179-b058c600-f018-11e9-9e5c-a698dcb74ed8.png)

Hier als .pdf zum Download:
[Systemmap DEMOCRACY-komprimiert.pdf](https://github.com/demokratie-live/democracy-client/files/3734043/Systemmap.DEMOCRACY-komprimiert.pdf)

**Comment by ogerly** [comment]
nice :)

**Comment by ManAnRuck** [comment]
wenn's in https://github.com/demokratie-live/democracy-docu persistent gesso here ist können wir es schießen :)
