### ISSUE TITLE
[BIO] Prozedur aus Tagesordnungspunkten vom Bundestag entfernt - Abstimmungsdatum bleibt

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#910]
# Fehler
Wenn der Bundestag eine Abstimmung von der Tagesordnungsliste entfernt, bleibt das bisher gescrapte Abstimmungsdatum weiterhin in der Datenbank.

# Lösung
Das Abstimmungsdatum sollte wieder entfernt werden.
(Frage: soll es dann ebenfalls aus den Abstimmungen fliegen? könnte verwirrend sein für Leute die bereits abgestimmt oder auch zum abstimmen in social media geshared haben)

# Möglichkeiten
1. Automatisiert: es wird ein check eingebaut, welcher Prozeduren in einer bestimmten Zeitspanne checkt und im falle einer Entfernung der TOP auch das Abstimmungsdatum wieder entfernt
  - Generieren einer Id der Tagesordnungspunkte (Woche, Tagesordnungspunkt, Unterpunkt). Diese mit der Prozedur verknüpfen -> und nur diese Prüfen. Falls Änderungen bestehen, einen erweiterten check starten…
2. Eine Redaktionelle Entfernungsmöglichkeit über das BioBackend

# Todos
- simulieren
- beobachten

**Comment by visionmakery** [comment]
Hier einige Beispiele, anhand von https://democracy-app.de/vergangen ermittelt

**Vergangene Prozeduren ohne Ergebnisse (bis 06.06.2019)**


__im aktuellen Bundestag.io-BackEnd gefunden__

236259 – Mietenexplosion stoppen - Bestandsmieten deckeln

236651 – Wälder schützen - Rodungen für die Windkraft stoppen

236320 – Ein umfassendes Tabakwerbeverbot schaffen

247834 – Die Freisetzungsrichtlinie 2001/18/EG in ihrer Regelungsschärfe auch für neue Gentechnik beibehalten - Regulierung im Einklang mit dem Vorsorgeprinzip auch in Zukunft sichern

248212 – Fairen Wettbewerb und gute Arbeitsbedingungen auf Post- und Paketmärkten durchsetzen

__im aktuellen Bundestag.io-BackEnd nicht gefunden__

https://democracy-app.de/gesetzgebung/247689/gesetz-zur-aenderung-des-waffengesetzes

https://democracy-app.de/antrag/242538/das-recht-von-maedchen-auf-bildung-und-gesundheit-in-krisen-und-konfliktgebieten-staerken-und-die-g7-deklaration-zuegig-und-konsequent-umsetzen

https://democracy-app.de/antrag/243183/freihandelsabkommen-mit-vietnam-fair-nachverhandeln-investitionsschutzabkommen-ablehnen

https://democracy-app.de/antrag/242505/mehr-fachkraefte-fuer-gute-kitas-und-eine-starke-kinder-und-jugendhilfe

https://democracy-app.de/antrag/249079/ausstattung-von-angehoerigen-der-bundessicherheitsbehoerden-mit-naloxon

**Comment by ulfgebhardt** [comment]
Related: https://github.com/demokratie-live/democracy-client/issues/915

**Comment by ulfgebhardt** [comment]
Scrapers are forward self correcting -> consider this done.
Remaining issues #915 
Not addressed: Manuel edit in backend
