### ISSUE TITLE
[bundestag.io] Delete Agenda Collection, Remove Database Model

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#913]
### [bundestag.io] Delete Agenda Collection, Remove Database Model

Remove the table & model for `agendas` - they seem to hold pretty useless data which is now available via ConferenceWeekDetails.

@ManAnRuck Cool?

![image](https://user-images.githubusercontent.com/1238238/66478933-bb9d7600-ea9b-11e9-8ce2-e1558fe31bca.png)

**Comment by ManAnRuck** [comment]
Da Daten im neuen format vorhanden sind, kann's gelöscht werden :)
