### ISSUE TITLE
Nutzerspezifische Push's

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#922]
- Wann ist der Optimale Zeitpunkt für den Nutzer pushs zu bekommen - wir können das nicht abfragen?
- Wie ist die optimale Darstellung für den Nutzer?
- Was ist der optimale Inhalt einer push pro Nutzer?
- Wie oft pushen wir den Nutzer optimaler Weise?
- Wie schaffen wir es diese Optimalwerte pro Nutzer zu ermitteln?
- Was sind minimal Werte (max/min pushs pro Monat/Tag)
- Welche verschiedenen Arten von Pushs können wir erzeugen? (Newsletter, Gesetz, Ergebnis, Bulk,...)

@visionmakery

**Comment by ulfgebhardt** [comment]
Closing this in favor of new Push Concept: https://github.com/demokratie-live/democracy-client/issues/923
