### ISSUE TITLE
🌟 [EPIC] Push Refactoring

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#923]
## Neues Konzept
<img width="537" alt="Bildschirmfoto 2019-10-30 um 19 16 55" src="https://user-images.githubusercontent.com/32302889/67886529-dff3ec00-fb49-11e9-9478-f6aadb9d5fe6.png">

<img width="242" alt="Bildschirmfoto 2019-11-07 um 10 55 34" src="https://user-images.githubusercontent.com/32302889/68378878-27cbd200-014d-11ea-9e18-1abbac3f681f.png">

<img width="449" alt="Bildschirmfoto 2019-11-12 um 14 24 52" src="https://user-images.githubusercontent.com/32302889/68675478-3a347a00-0558-11ea-8c18-eb1c312d5ae1.png">

a) Individualpushs
- ✅(Sitzungswochen-)Abstimmung mit den meisten Aktivitäten pushen; täglich neu - random Zeit vormittag / 'Jetzt Abstimmen!' 
- ❌(Sitzungswochen-)Abstimmung mit den meisten Aktivitäten pushen; täglich neu - gegen Abend / 'Heute noch nicht abgestimmt?' 
- ✅'Das-könnte-Sie-auch-interessieren' via Populär pushen; in sitzungswochenfreier Zeit (Top 100) / 1x die Woche
- ❌Neues Papier in Vorbereitung bekommt besondere Beachtung 
- ✅ RückkopplungsPush, bei denen ich abgestimmt habe
Problem: Wenn wir die Rückkopplungspush über die Glocke lösen, bekommt der Nutzer auch jedes Update, was nicht das Ergebnis ist, z.B. 'Verabschiedet' oder 'Bundesrat hat Vermittlungsausschuss nicht angerufen'

b) Bulk-Pushs 
- Push (Sieh Dir jetzt die Inhalte der neuen Sitzungswoche an)
- ✅Sonntag: Diese Sitzungswoche stehen 13 Abstimmungen für Dich bereit
- ✅filternd: nur in Themenbereichen, die mich interessieren (Präferenz) / 'Neue Abstimmungen für Dich'

PushStrategy researchen
Pushlänge

#### Bulk-Push-Notifications für

- Jetzt Abstimmen!
- Neu in Vorbereitung!

#### Single-Push-Notifications für

- Update (Glocke)

#### Regeln zum Pushen
2x/Tag 8.00 Uhr und 19.45 Uhr

#### Aktuelles Layout
Titel: Wording für Klassen in bold
Untertitel: Gesetzestitel / Es gibt 13 neue Abstimmungen. / 53 Elemente neu in Vorbereitung

![IMG_5114](https://user-images.githubusercontent.com/32302889/67090636-eaf26800-f1aa-11e9-9a21-5d15b6145de2.png)

#### Aktuelle Umsetzung

![40976500-a52de134-68ce-11e8-94ea-a36ee4487b3f](https://user-images.githubusercontent.com/32302889/67091037-db275380-f1ab-11e9-86de-406e7b6b009b.png)

**Comment by ManAnRuck** [comment]
idee: local push mit meisten Aktivitäten welche noch nicht gelesen wurden (möglich?)

**Comment by ulfgebhardt** [comment]
Filter resettet beim Push Click & Restart der App

**Comment by visionmakery** [comment]
2 Step - zunächst ohne Sachgebiete

**Comment by visionmakery** [comment]
PushIcon (in blau) nur bei SinglePush auf Liste darstellen.
SinglePush -> Detailseite und demarkiert das ListenPushIcon

BulkPushs ohne ListenPushIcon
