### ISSUE TITLE
Listenansicht b.io-admin anpassen

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#929]
## 🚀 Feature
![Group 2](https://user-images.githubusercontent.com/32302889/67704154-e3a23a00-f9b4-11e9-8985-986b9d5b50da.png)

hier in der Listenansicht den Beratungszustand (z.B. "Beschlussempfehlung liegt vor" oder "Abgelehnt") + das Datum der letzten Änderung anzeigen

geil wäre dann noch eine Sortierung nach den Beratungszuständen, wobei "Angenommen/Abgelehnt/Verabschiedet" oben sein sollte vor "Überwiesen/Beschlussemfehlung liegt vor"

**Comment by ulfgebhardt** [comment]
Anstatt dem Letzten Änderungsdatum muss das erwartete Vote Datum angezeigt werden `customData.expectedVotingDate`

**Comment by ManAnRuck** [comment]
@visionmakery @ulfgebhardt customData.expectedVotingDate ist jetzt drinnen und sortierbar

Um alle Vorgänge zu laden würde ich vorschlagen die Tabellen Inhalte dynamisch zu laden. Dafür wäre ein Query nötig welcher die in der Tabelle vorhandenen Filtermöglichkeiten anbietet.

**Comment by visionmakery** [comment]
Einfache Regel - Datum im Format [tt.mm.jjjj]

grün = in der Zukunft (expected VoteDate)
rot = in der Vergangenheit (definite VoteDate)

**Comment by visionmakery** [comment]
@ManAnRuck Ich habe gerade 5 Seiten Ergebnisse eingetragen und habe mit der aktuellen Darstellung folgendes Usability-Problem:

1. Ich filtere auf 'ohne Daten' und bekomme eine Liste mit Vorgängen ohne Daten
2. Ich klicke auf den ersten Eintrag und trage das Ergebnis ein
3. Ich will mit "Zurück im Browser" bzw. Durch Klick auf "Vorgänge" zurück zur Liste kehren
4. Die Gesamtliste lädt mit Lord-Spinner (10s) und der Datenfilter ist weg
5. Ich muss den Datenfilter 'ohne Daten' neu einstellen um die aktualisierte Liste ohne den soeben eingetragenen Vorgang zu bekommen

Ich bin daraufhin so vorgegangen, dass ich mir die einzelnen Vorgänge aus der Liste in neuen Tabs aufgemacht hab, um sie nacheinander einzutragen. 

Ich schlage deshalb vor, die Weiche Daten (ja/nein) aus der Tabelle herauszuziehen und per CheckBox 'ohne Abstimmungsergebnisse' anzuzeigen, so wie es bisher war.

**Comment by ManAnRuck** [comment]
> @ManAnRuck Ich habe gerade 5 Seiten Ergebnisse eingetragen und habe mit der aktuellen Darstellung folgendes Usability-Problem:
> 
> 1. Ich filtere auf 'ohne Daten' und bekomme eine Liste mit Vorgängen ohne Daten
> 2. Ich klicke auf den ersten Eintrag und trage das Ergebnis ein
> 3. Ich will mit "Zurück im Browser" bzw. durch Klick auf "Vorgänge" zurück zur Liste kehren
> 4. Die Gesamtliste lädt mit Lord-Spinner (10s) und der Datenfilter ist weg
> 5. Ich muss den Datenfilter 'ohne Daten' neu einstellen, um die aktualisierte Liste ohne den soeben eingetragenen Vorgang zu bekommen
> 
> Ich bin daraufhin so vorgegangen, dass ich mir die einzelnen Vorgänge aus der Liste in neuen Tabs aufgemacht hab, um sie nacheinander einzutragen.
> 
> Ich schlage deshalb vor, die Weiche Daten (ja/nein) aus der Tabelle herauszuziehen und per CheckBox 'ohne Abstimmungsergebnisse' anzuzeigen, so wie es bisher war.

@visionmakery das habe ich bereits auch schon festgestellt. ein alleiniges aus der liste raus ziehen wird da nichts bringen. das in neuen taps öffnen ist da schon ein guter workaround. was ich auf die schnelle machen könnte ist, dass es default mäßig in einem neuen Fenster auf geht. andernfalls wäre halt nochmal etwas mehr Arbeit von Nöten die langfristig sicher sinnvoll ist, jedoch sollten wir evaluieren, wann wir dies umsetzen wollen.
