### ISSUE TITLE
DetailScreen: Inhalt/Sachgebiet nicht bündig

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#93]
**Description:**
Inhalt(stext)/Sachgebiet(stext) auf Detailseite linksbündig zum Gesetzestitel/zu den Schlagwörtern ausrichten

**Faulty Behaviour:**
Die Textelemente sind zu weit links

**Expected Behaviour:**
@ReggaePanda Text(e) bündig ausrichten
[
![1](https://user-images.githubusercontent.com/32302889/36585504-6c356c9e-187e-11e8-9619-2b2d7c8b6231.png)
](url)

Commit: [A12B34E](URL)

**Comment by ReggaePanda** [comment]
<img width="559" alt="bildschirmfoto 2018-02-23 um 12 10 58" src="https://user-images.githubusercontent.com/2183135/36591607-d601ed78-1892-11e8-85bc-cbc9c92680ca.png">
