### ISSUE TITLE
🗣Apple Pay (Non Profit) anmelden

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#945]
## 🗣 Suggestion
https://developer.apple.com/apple-pay/nonprofits/
 
um spenden innerhalp der iOS app zu erhalten

**Comment by visionmakery** [comment]
Hab uns gerade bei Benevity registriert. Ich schau mal, wie es dann weiter geht! Bis zur BTW21 muss das funktionieren ;)
