### ISSUE TITLE
🚀 Transfere all required data from BIO to DEMOCRACY

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#948]
## 🚀 Feature

- List all data required
- Transfer all Data
- Store Data (however for now)
- continue here: https://github.com/demokratie-live/democracy-client/issues/949

**Comment by ulfgebhardt** [comment]
Zusätzliche Daten:
- Vote-End Datum
- Heading von Tagesordnung
- KW

**Comment by ManAnRuck** [comment]
wo ist das pr zum approven?

**Comment by ManAnRuck** [comment]
bei mir lokal alles null

![Bildschirmfoto 2019-11-24 um 18.35.36.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/a3c284a4-d28e-4451-b8e9-bd8e2b786023)

muss ich was an den server einstellungen beachten?

**Comment by ulfgebhardt** [comment]
Hat sich geklärt oder? @ManAnRuck

**Comment by ManAnRuck** [comment]
ja jetzt hat es sich geklärt
