### ISSUE TITLE
🚀 Refactor API for DEMOCRACY App - include new Data

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#949]
## 🚀 Feature

Followup of https://github.com/demokratie-live/democracy-client/issues/948

- Define API for new App-Requirements
- Implement API
- Store Data accordingly -> transform

**Comment by ManAnRuck** [comment]
was soll ich hier approven?

**Comment by ulfgebhardt** [comment]
Hierfür gab es kein eigenen PR, habe ich trotzdem mit rübergeschoben.
-> Schließe ich da die Schnittstelle an sich ja funktioniert - es fehlen nur Daten.
