### ISSUE TITLE
📱🛠 Listen Screens

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#957]

**Comment by ManAnRuck** [comment]
Technische Umsetzung führten. Design Anpassungen kommen in einem extra ticket

(Wenn keine technischen Fehler vorhanden)

**Comment by ManAnRuck** [comment]
Testing: funktioniert die Statistik wie in der Alten Version

Chart, Liste, Navigation zur detailansicht

**Comment by ulfgebhardt** [comment]
Changing Filter will prevent loaing of more list elements. Restart of the App is required

1. Filter by Antrag
2. Scroll till end of list
3. Change Filter
4. See first week only
5. Scroll down -> no spinner -> stuck on first batch
6. ...
7. Profit

**Comment by ManAnRuck** [comment]
issue confirmed.

sollte nun behoben sein
