### ISSUE TITLE
📱🛠 Listen Filter

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#958]

**Comment by ManAnRuck** [comment]
Change filter icon (active/not active) in list view is missing

**Comment by ManAnRuck** [comment]
Testing: 
- funktioniert der filter
- wechselt das icon in der Listenansicht

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/72730847-9936f080-3b92-11ea-93ad-170ceedf1860.png)

Checkmarks distorted (or is this intended?)

![image](https://user-images.githubusercontent.com/1238238/72730877-af44b100-3b92-11ea-9595-90144eab09e7.png)

I set the filter to only show "Not voted" -> voted on first thing -> it does not disappear -> List is not updated

**Comment by ulfgebhardt** [comment]
It is also not possible to select "Gesetzgebung" -> The "Vorgangstyp" Filter only has 2 states:
- All(both)
- Antrag(Gesetzgebung deselected)
- Gesetzgebung alone cannot be selected

**Comment by ManAnRuck** [comment]
https://app.zenhub.com/workspaces/democracy-5ca9ff304f32e2352de2e588/issues/demokratie-live/democracy-client/958#issuecomment-576279084 feature or bug? klären im team

https://app.zenhub.com/workspaces/democracy-5ca9ff304f32e2352de2e588/issues/demokratie-live/democracy-client/958#issuecomment-576279813 kann ich nicht reproduzieren. wie ist die genaue klickfolge?

**Comment by ManAnRuck** [comment]
ergänzung zu letztem kommentar:

1. ist ein feature ;)
2. ist nicht reproduzierbar (oder tritt nicht mehr auf)

**Comment by ulfgebhardt** [comment]
scheint ok
