### ISSUE TITLE
📱🛠 Suche

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#959]

**Comment by ManAnRuck** [comment]
Scroll issue: keyboard overlays scroll content

Mehrmaliges eingeben und löschen von „D“ listet Vorschläge mehrfach mit fehlender Segment Headline

Android schnelles tippen und löschen kann in einer Loop enden 🤨

Query zum zählen der gesuchten Begriffe global zu zählen wird noch nicht ausgeführt.

**Comment by ManAnRuck** [comment]
testing: sind oben genanten Fehler in der suche behoben und geht die suche wie gewünscht

**Comment by ulfgebhardt** [comment]
@ManAnRuck Wird der Zähl Query nun ausgeführt? 

Löschen von text führt Teilweise zu einem Loop von hinzufügen und löschen von text:
1. Meistgesucht: demokratie
2. delete key
3. Possible Loop showing
3.1 demokrati
3.2 demokratie
3.3 demokra
3.4 demokrat
3.5 ...
4. Profit

Happens on using delete key

**Comment by ManAnRuck** [comment]
issue reproduzierbar. jedoch wohl Android only

**Comment by ulfgebhardt** [comment]
LineageOS 16

**Comment by ManAnRuck** [comment]
nach ein paar änderungen tritt es im emulator nicht mehr auf

**Comment by ulfgebhardt** [comment]
test: ok
