### ISSUE TITLE
DetailScreen: Sachgebiet, Vorgang, erstellt am, Abstimmung, Inhalt

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#96]
**Description:**
Sachgebiet(stext), Vorgang(stext), erstellt am (Text), Abstimmung(stext) und Inhalt vergrößern?

**Faulty Behaviour:**
Diese Textelemente sind kleiner (11) als die Schlagwörter und der Inhaltstext 

Expected Behaviour:
@ReggaePanda @ulfgebhardt Text(e) auch größer (13) darstellen?
![3](https://user-images.githubusercontent.com/32302889/36586263-6704f66a-1881-11e8-9d80-6a0bcb3a1027.png)

Commit: [A12B34E](URL)

**Comment by ReggaePanda** [comment]
<img width="559" alt="bildschirmfoto 2018-02-23 um 12 10 58" src="https://user-images.githubusercontent.com/2183135/36591568-ae709dfe-1892-11e8-8367-8aa613e7bbc7.png">
