### ISSUE TITLE
📱🛠 Prozedur Detailansicht

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#961]

**Comment by ManAnRuck** [comment]
Es wird derzeit nur das Community Wahlkreis Chart angezeigt. Es fehlt für die gesamte community

Action Button icons fehlen noch (svg)

**Comment by ManAnRuck** [comment]
Testing:
- Detailseite wie bisher
( außname action button icons kommen später)

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/72730702-24fc4d00-3b92-11ea-8df0-2ad01f02a412.png)

Works all fine, but icons(as stated in the issue)  and PDF Viewer. PDF is never loaded and screen is stuck on loading screen. Download works fine

**Comment by ManAnRuck** [comment]
ich erstelle für das pdf Ladeproblem ein neues ticket, da wohl sehr devicespezifisch und nicht im emulator anderem real device reproduzierbar
