### ISSUE TITLE
📱🛠 Voting

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#962]

**Comment by ManAnRuck** [comment]
Es fehlt noch das partychart. Ansonsten soweit technisch durch

**Comment by ManAnRuck** [comment]
Testing: funktionieren das voting inkl der Platzhalter 
- Wahlkreis wählen
- erste Abstimmung nötig
- Fraktionschart

**Comment by ulfgebhardt** [comment]
Cannot test due to Network Error

![image](https://user-images.githubusercontent.com/1238238/72721843-3e46ce80-3b7d-11ea-9b21-b7d03e292041.png)

**Comment by ManAnRuck** [comment]
api error is fixed 👍🏼

**Comment by ulfgebhardt** [comment]
Selecting Wahlkreis works, but upragding from the old to the new app loses the Wahlkreis setting. At least it was the case for me. The verification transfer worked perfectly - just not the Wahlkreis.

**Comment by ManAnRuck** [comment]
ok, ich mach aus dem problem mit dem Wahlkreis ein neues ticket da der rest ok ist schließe ich dieses ticket
