### ISSUE TITLE
📱🛠 Wahl o meter

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#963]

**Comment by ManAnRuck** [comment]
Technische Umsetzung abgeschlossen.
Weitere Design Anpassungen in weiterem Ticket 🎫 mit designänderung der list Pie Chart darstellung

**Comment by ManAnRuck** [comment]
Testing: funktioniert die Technik?
Verschiedene Listen, Navigation to detail pages

**Comment by ulfgebhardt** [comment]
Here also: Main Menu does not close when navigating to this Page.

When scrolling between the 3 Sections (BT, Fraktion, WK) the App often gets stuck in the scoll Animation and its impossible to scroll down. This requires additional horizontal scroll actions between the sections to resolve)

**Comment by ManAnRuck** [comment]
issue ist reproduzierbar gewesen und sollte mit der neuen version behoben sein. 😊

**Comment by ManAnRuck** [comment]
es gab nochmal einige packet updates. 2. Fehler hoffentlich damit behoben

**Comment by ulfgebhardt** [comment]
Problem besteht immer noch - ist aber besser geworden.
