### ISSUE TITLE
📱🛠 Statistik

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#964]

**Comment by ManAnRuck** [comment]
Testing: funktioniert die Statistik wie in der Alten Version

Chart, Liste, Navigation zur detailansicht

**Comment by ulfgebhardt** [comment]
Main Menu does not close when navigating to Statistic, Screen has to be clicked again

**Comment by ManAnRuck** [comment]
da statistik rausfliegt, ist dieses ticket obsolet

der Fehler mit der navigation ist wohl noch ein Fehler der library. (anderes ticket)

**Comment by ManAnRuck** [comment]
reopened, da ich Statistik noch komplett rausschmeißen muss 😅

**Comment by ulfgebhardt** [comment]
Test: ok
