### ISSUE TITLE
📱🛠 Einstellungsscreen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#966]
<img width="402" alt="Bildschirmfoto 2020-01-24 um 12 54 32" src="https://user-images.githubusercontent.com/2183135/73047534-b2001880-3ea8-11ea-9f6b-3c6ddffbac01.png">

**Comment by ManAnRuck** [comment]
@visionmakery (only, da kein bei diesem ticket noch kein codecheck möglich)

Testing:
ist dieser screen + funktionalität umgesetzt?
icons und kleinere designfixes werden nachgezogen.

**Comment by ulfgebhardt** [comment]
Hier gibt es keinen PR, scheint aber funktional.
