### ISSUE TITLE
DetailScreen: inklusives Dropdown

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#97]
**Description:**
"Details" und "Dokumente" im Detailsscreen gleichzeitig aufgeklappt haben

**Faulty Behaviour:**
Aktuell besteht ein exklusives Dropdown: Entweder können die Details (a) aufgeklappt sein oder die Dokumente (b). Mit dem Aufklappen von (a) klappt sich (b) automatisch zu und andersherum

**Expected Behaviour:**
@ReggaePanda (a) und (b) können gleichzeitig aufgeklappt sein; (a) und (b) können jeweils individuell auf- bzw. zugeklappt werden
![4](https://user-images.githubusercontent.com/32302889/36586862-84a2a684-1883-11e8-9ec0-3ce22bb15f3c.png)

Commit: [A12B34E](URL)

**Comment by ReggaePanda** [comment]
<img width="559" alt="bildschirmfoto 2018-02-23 um 12 10 58" src="https://user-images.githubusercontent.com/2183135/36591543-a10538b4-1892-11e8-8bd0-872b3e7b6066.png">
