### ISSUE TITLE
[DAPI] Community vote results in Procedure query object

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#973]
aktuell haben wir die Bundestagsergebnisse im Prozedur Objekt, die der Community müssen derzeit wohl noch in einem eigenen Query abgefragt werden.

für die neue Listenansicht würde es jedoch sehr von Vorteil sein, wenn diese auch im Prozedur Objekt abgerufen werden können

**Comment by ulfgebhardt** [comment]
Ja das ist der Fall, mache ich!
