### ISSUE TITLE
Vote performance testen

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#976]
## 🗣 Suggestion

Vote performance testen

Die aktuelle App hat ein Performance-Problem -> die entsprechenden Queries manuell testen und einmessen.

Testen mit sehr vielen zuvor abgestimmten prozeduren

**Comment by ManAnRuck** [comment]
keine performance Einbußen bemerkbar bis auf probleme bei voller und halber stunde (api timeouts)
