### ISSUE TITLE
List CONFERENWEEK_PLANNED should be sorted by time, not activity

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#978]
## 🐛 Bugreport

List CONFERENWEEK_PLANNED should be sorted by time, not activity

### App-Version & Environment

APP: []

OS:  []

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by ManAnRuck** [comment]
@ulfgebhardt ist das schon deployed? wenn ja sieht es so aus, als ob es nach datum sortiert ist, jedoch in der falschen Reihenfolge.

**Comment by ulfgebhardt** [comment]
Sollte gefixt sein (nach deploy)
