### ISSUE TITLE
🌍 [API] Sitzungswochen Infos

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#982]
![Bildschirmfoto 2019-12-31 um 11.05.14.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/2c451ac6-4af2-417b-92ef-47f7705a6936)

für den leeren Sitzungswochen screen brauchen wir eine Schnittstelle mit den Informationen wann die nächsten Sitzungen stattfinden.

vorschlag.
2 Endpunkte

1. aktuelle/nächste sitzungswochenzeit (sprich, wenn derzeit eine läuft, wird die aktuelle zurückgegeben, falls derzeit keine läuft wird das datum der nächsten Sitzungswoche zurückgegeben)
2. ein array mit allen Sitzungswochen der aktuellen Periode 

CONFERENCE_WEEK_DETAIL object:
- start
- end
- KW

**Comment by ulfgebhardt** [comment]
Die Sitzungswochenzeit lässt sich wie folgt ausrechnen:
```
// Check if we have a ConferenceWeek
  const startOfWeek = moment()
    .startOf('isoweek')
    .toDate(); // Should be Mo
  const endOfWeek = moment()
    .endOf('isoweek')
    .toDate(); // Should be So
```
Siehe: https://github.com/demokratie-live/democracy-server/blob/alpha/master/src/services/notifications/index.js#L201

Um die folgenden Sitzungswochen anzuzeigen müssen wir zuerst den Kalender des Bundestags scrapen/importieren -> d.h wir kennen aktuell die Sitzungswochen nur dann, wenn die Liste nicht leer ist.

**Comment by ManAnRuck** [comment]
wenn ich mich recht erinnere wollten wir das so handeln, dass wir erstmal die Daten händisch Einpflegen (ggf. als json) sind ja nicht so viele.

https://www.bundestag.de/parlament/plenum/sitzungskalender/bt2020-590846

**Comment by ManAnRuck** [comment]
server & client umgesetzt

Testing:
(evtl. filter so einstellen, dass keine listeneinträge anzeigt <- in zukunft sollte hier etwas anderes angezeigt werden. dazu mach ich noch ein ticket)

<img width="584" alt="Bildschirmfoto 2020-02-05 um 21 48 30" src="https://user-images.githubusercontent.com/2183135/73881917-834b5000-4861-11ea-9bea-06317cd6f79b.png">

**Comment by ManAnRuck** [comment]
@ulfgebhardt würdest du hier bitte noch den server part reviewen?
