### ISSUE TITLE
🗣 [Client Query] Get Votes via `votes` field

### ISSUE THREAD

**Issue by ulfgebhardt** [demokratie-live/democracy-client#985]
## 🗣 Suggestion

@ManAnRuck 
Ich habe einen cache-value für `votes`, ähnlich dem `activityIndex` auf dem Procedure-Type eingeführt. Dieser sollte deutlich performanter sein, als das Abrufen über `cummunityVotes.total`.

```
{procedures(listTypes:[TOP100], pageSize: 25, offset: 0){
  title
  voteDate
  votes
  communityVotes{
    total
  }
}
}
```

![image](https://user-images.githubusercontent.com/1238238/71667032-a61aae00-2d63-11ea-9289-230e3d894258.png)

**Comment by ManAnRuck** [comment]
Der ist in der api derzeit nicht nötig, da eh auf die Details der votes zugegriffen wird. Daher lieber wieder raus nehmen, damit der Wert nicht 2x in der api angeboten wird
