### ISSUE TITLE
📱 Splash Screen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#988]
https://medium.com/@ywongcode/how-to-add-android-app-icons-and-splash-screens-for-react-native-projects-2019-edition-77bc6766eee8
or
https://medium.com/@appstud/add-a-splash-screen-to-a-react-native-app-810492e773f9

**Comment by ManAnRuck** [comment]
TESTING:
wird der splashscreen mit dem democracy logo angezeigt

**Comment by ulfgebhardt** [comment]
Splash screen is distorted auf Android

**Comment by ManAnRuck** [comment]
sollte nun gefixt sein

**Comment by ulfgebhardt** [comment]
ist noch schlimmer geworden bei mir - jetzt ist das logo nicht nur nicht mittig, sondern nicht mehr komplett sichtbar

**Comment by ManAnRuck** [comment]
hast du ein screenshot?

**Comment by ManAnRuck** [comment]
Splash Screen nur mit Logo und DEMOCRACY schriftzug
demokratie live raus

**Comment by ManAnRuck** [comment]
![splash_icon](https://user-images.githubusercontent.com/2183135/73817393-17c69b80-47eb-11ea-96a7-666b7f7510a2.png)
neues splashscreen image

**Comment by ulfgebhardt** [comment]
Screen ist mittig, aber viel zu groß (abgeschnitten anden rändern)
