### ISSUE TITLE
📱 Wahlkreis übernehmen bei update der app

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#990]
Ausgewählter wahlkreis wird nach einem Update von der alten auf die neue Version übernommen

Grund:
der key für den async storage ist unterschiedlich `Constituency` (alt) VS `constituency` (neu)

**Testing**:
- Asyncstorage daten löschen
- in alter version wahlkreis auswählen
- updaten und in neuer version gegenchecken

_Tested on iOS by @ManAnRuck_

**Comment by ulfgebhardt** [comment]
scheint nach dem Update zu funktionieren
