### ISSUE TITLE
📱 [Android] PDF reader loading issue

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#991]
Es kommt wohl auf manchen Android geraten zu Schwierigkeiten PDF's über den PDF reader zu laden.

Bleibt hängen mit Ladebalken.
Scheint den Ladevorgang nicht zu beginnen.
Auf anderen Android devices & Emulator funktioniert es.

original: #961

![72730702-24fc4d00-3b92-11ea-8df0-2ad01f02a412.png](https://images.zenhubusercontent.com/5a2e89458a75884b908aae76/829ce7cb-93d8-41db-9dd2-099db3f5c829)

**Comment by ManAnRuck** [comment]
http links wurden auf bestimmten android Versionen nicht geladen (nur https)

Testing:
open an pdf in pdf viewer

**Comment by visionmakery** [comment]
Bei allen Devices, die ich getestet habe, funktioniert es einwandfrei, vgl.
<img width="681" alt="LG G5" src="https://user-images.githubusercontent.com/32302889/73063057-2ed9c500-3e9e-11ea-825b-59979d556739.png">
<img width="644" alt="OnePlus7" src="https://user-images.githubusercontent.com/32302889/73063058-2ed9c500-3e9e-11ea-8558-9b0c755f34ff.png">
<img width="1260" alt="Google Pixel 4" src="https://user-images.githubusercontent.com/32302889/73063059-2ed9c500-3e9e-11ea-932c-da9138566b0a.png">
<img width="642" alt="GalaxyTab S4" src="https://user-images.githubusercontent.com/32302889/73063060-2f725b80-3e9e-11ea-99e1-05981d903541.png">
<img width="1254" alt="Galaxy S7" src="https://user-images.githubusercontent.com/32302889/73063061-2f725b80-3e9e-11ea-8ac9-ea812e6adae3.png">
<img width="1270" alt="Galaxy S8" src="https://user-images.githubusercontent.com/32302889/73063062-2f725b80-3e9e-11ea-899f-105a8268e3b1.png">
<img width="641" alt="Galaxy S10" src="https://user-images.githubusercontent.com/32302889/73063064-2f725b80-3e9e-11ea-8d0b-a287326c428c.png">

**Comment by ulfgebhardt** [comment]
test: ok
