### ISSUE TITLE
Redesign keine sitzungswochendaten vorhanden

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#993]
Sieht aktuell nicht sieht ansprechend aus, daher idealerweise nochmal eine schön aussehende Variante gestalten

**Comment by visionmakery** [comment]
Neues Design liegt in Zeplin
<img width="730" alt="Bildschirmfoto 2020-01-23 um 13 38 48" src="https://user-images.githubusercontent.com/32302889/72989210-23c75c00-3dee-11ea-9307-84baa6724cc9.png">
