### ISSUE TITLE
📱🦋Trenner im header entfernen

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#996]

**Comment by ulfgebhardt** [comment]
Dieses Issue verstehe ich nicht - hier fehlt die Beschreibung und der PR (?)

**Comment by ManAnRuck** [comment]
mein fehler, sorry.

es gab teilweise bei übergroßen headern (suche o. wahlkreissuche) einen dünnen strich im blauen header, der sollte raus sein.

**Comment by ulfgebhardt** [comment]
test: ok
